maidsafe/safe_network

src/node/config_handler.rs
=> fix: node now uses contact config file when no HCC supplied

examples/routing_stress.rs, src/node/network.rs, src/routing/core/api.rs, src/routing/routing_api/mod.rs, src/routing/section/section_keys.rs
- The index was always quired for separately, a potential racing condition.
=> refactor(signing): return index and sig share

Cargo.lock, src/client/client_api/transfers/balance_management.rs
Some small issues encountered when looking through the `balance_management` tests.
---
- 4e1e3d6f2 **chore(client): Fix some comments in tests**
The comments were out of sync with the asserted values.
- 51049baec **test(client): Remove redundant statement**
The loop will continue as long as `receiving_bal != target_tokens` which
subsumes the explicit `receiving_bal > target_tokens` test, making the
latter redundant.
=> Minor test fixes

src/client/connections/messaging.rs
Remove the client timeout (that made many tests fail), and adapt the pattern matching accordingly.
=> fix: remove the client timeout

Cargo.lock, src/node/bin/sn_node.rs
Without this, running `safe node update` will check the now defunct sn_node repo releases, rather than the `safe_network` repo.
=> fix(updater): point self_update to new repo name

src/routing/routing_api/comm.rs
=> fix(comm): properly close temp endpoint created for is_reachable() test

src/client/client_api/blob_apis.rs, src/client/utils/test_utils/mod.rs, src/messaging/node/variant.rs, src/node/metadata/chunk_records.rs, src/node/node_api/messaging.rs, src/routing/core/msg_handling/mod.rs, src/routing/core/msg_handling/user_msg.rs, src/routing/routing_api/dispatcher.rs, src/routing/routing_api/mod.rs
A section that receives a msg from a client, should not raise it to node
layer immediately, but instead check if the dst is in fact some other
section. In that case we will forward the msg instead.
=> fix(routing): forward client msgs when not for us

src/lib.rs
- 8dc76bbff **chore: Remove redundant lint configuration**
Many of the lints specified for `#[warn(...)]` are warn-by-default and
have been removed. Additionally:
- `clippy::wrong_pub_self_convention` is deprecated and is now a no-op.
- comments have been updated to describe the purpose of the
configuration, on the assumption that folk can discover lint meanings
themselves (whereas why we're using them can't be Googled).
- 67bf67d58 **chore: Remove duplicate attributes from crate root**
These were presumably duplicated when the crates were merged.
- 7e02bf3d0 **chore: Update favicon URL**
The old URL no longer exists. The new URL was taken from the
https://maidsafe.net site.
=> Tidy lints

src/client/client_api/blob_apis.rs, src/client/client_api/map_apis.rs, src/client/client_api/mod.rs, src/client/client_api/register_apis.rs, src/client/client_api/sequence_apis.rs, src/lib.rs
- 2d90ec55b **chore: Turn on `unreachable_pub` lint for some modules**
Some modules have already been updated to fix `unreachable_pub`
warnings. We should actually turn on the lint for those modules to make
sure nothing sneaks in.
- 5c0cc3720 **chore(client): Fix `unreachable_pub` in tests**
These were missed before, due to checking without `--all-targets` 😳
=> Unreachable pub

src/routing/section/section_peers.rs
- 828ec58cd **chore(routing): Remove an unused `IntoIter` struct**
Sadly the Rust compiler can't detect this because it is 'used' in its
`Iterator` implementation (even though *that* is unused, Rust can't
tell).
=> chore(routing): Remove an unused `IntoIter` struct

src/node/logging/mod.rs
- 0691b31a5 **chore: Remove a duplicate log call**
This must have sneaked in from a rebase or something.
=> chore: Remove a duplicate log call

src/messaging/authority.rs, src/messaging/mod.rs, src/messaging/msg_kind.rs
- 54356df4b **refactor(messaging): Move `*Signed` types into an `authority` module**
This sets up the contained structures for more general use that within
`MsgKind`.
=> refactor(messaging): Move `*Signed` types into an `authority` module

.github/workflows/all_prs.yml, .github/workflows/main.yml, .github/workflows/pr_client.yml, .github/workflows/pr_messaging.yml, .github/workflows/pr_routing.yml, .github/workflows/pr_url.yml, Makefile, scripts/get_release_description.sh
This target was overlooked when we added the ARM and ARMv7 build and deploy.
Everything here is the same, just with the addition of the new aarch64-unknown-linux-musl target.
Also fixed some errors in the deployment process.
I've tested the updated deploy process on my own fork: https://github.com/jacderida/safe_network/releases/tag/v0.7.26
closes #182
=> Aarch64 builds

src/types/keys/signature.rs
- fca7700fe **fix(types): Fix `Debug` output for `Signature::Ed25519`**
The `#[debug(...)]` annotation was meant to apply to the field, not the
variant. It's a shame `custom_debug` does not emit an error in this
case.
=> fix(types): Fix `Debug` output for `Signature::Ed25519`

src/messaging/data/map.rs, src/messaging/data/register.rs, src/messaging/data/sequence.rs, src/node/metadata/elder_stores.rs, src/node/metadata/map_storage.rs, src/node/metadata/register_storage.rs, src/node/metadata/sequence_storage.rs
- 557994ab6 **refactor(messaging): Remove message info from data write ops**
The `*Write` structs contain the information needed to replay a cmd, the
`write` op itself, and the `client_sig` authorising it. They also
contained message info, the `msg_id` and `origin` of the message that
contained the op.
The message info is used in the initial call to `store.write` to
construct `CmdError` replies for the origin. It was largely unused in
the replication logic, except to add the message ID to some logged
errors (specifically when trying to delete a public register or
sequence). It therefore makes sense to remove these fields from the
replicated ops.
=> refactor(messaging): Remove message info from data write ops

scripts/deployment_test.sh
Adds a utility script for checking that a deployment has all the correct details as we would expect.
It uses the very handy Github CLI tool to get the details and URLs for all the assets on the release, which means you can download and verify them quite easily.
This script will help when changes are made to the deployment, as I had inadvertently broke things when I last made a change.
=> ci: Deployment Test

src/messaging/authority.rs, src/messaging/errors.rs, src/messaging/mod.rs, src/messaging/serialisation/mod.rs, src/messaging/serialisation/wire_msg.rs, src/node/event_mapping/client_msg.rs, src/node/event_mapping/mod.rs, src/node/event_mapping/node_msg.rs, src/node/metadata/chunk_records.rs, src/node/metadata/elder_stores.rs, src/node/metadata/mod.rs, src/node/metadata/register_storage.rs, src/node/metadata/sequence_storage.rs, src/node/node_api/handle.rs, src/node/node_ops.rs, src/routing/core/msg_handling/end_user.rs, src/routing/core/msg_handling/mod.rs, src/routing/routing_api/event.rs
- e355f5628 **feat(messaging): Add a `ClientAuthority` 'proof' struct**
The `ClientAuthority` struct can only be constructed by verifying a
`ClientSigned` for a particular payload. Thus, instances of
`ClientAuthority` can be trusted as proof that the payload indeed had a
valid signature, and was signed by the owner of `public_key` (e.g. a
holder of the corresponding secret key).
Note that it's important that `ClientAuthority` **does not** implement
`Deserialize`, or any other trait that could allow unverified
construction. It therefore cannot be a drop-in replacement for
`ClientSigned`, which is kind of the point as we can now introduce
`ClientAuthority` in areas where we expect the signature to be valid,
then work our way back towards verification. Ideally we should be able
to verify …
=> Client authority by construction

Cargo.lock, Cargo.toml, src/messaging/authority.rs, src/types/keys/signature.rs
- a9dcafdb6 **chore(types): Update `ed25519` to simplify signature serialization**
The upstream `ed25519::Signature` type now implements
`serde_bytes::{Deserialize,Serialize}`, so we can now delegate their
serialization entirely to `serde_bytes`.
=> chore(types): Update `ed25519` to simplify signature serialization

src/client/client_api/commands.rs, src/client/client_api/queries.rs, src/client/connections/messaging.rs, src/messaging/authority.rs, src/messaging/data/register.rs, src/messaging/data/sequence.rs, src/messaging/mod.rs, src/messaging/msg_kind.rs, src/messaging/node/mod.rs, src/messaging/node/node_msgs.rs, src/messaging/serialisation/mod.rs, src/messaging/serialisation/wire_msg.rs, src/node/event_mapping/client_msg.rs, src/node/event_mapping/mod.rs, src/node/event_mapping/node_msg.rs, src/node/metadata/chunk_records.rs, src/node/metadata/elder_stores.rs, src/node/metadata/mod.rs, src/node/metadata/register_storage.rs, src/node/metadata/sequence_storage.rs, src/node/node_api/handle.rs, src/node/node_api/messaging.rs, src/node/node_ops.rs, src/routing/core/msg_handling/end_user.rs, src/routing/core/msg_handling/mod.rs, src/routing/messages/mod.rs, src/routing/routing_api/event.rs
- e25a2878a **chore(messaging)!: Rename `ClientSigned` -> `DataSigned`**
This follows from 7dabc4ff3, since these signatures now cover 'data'
messages, which may not necessarily be signed by a client.
BREAKING_CHANGE: The `ClientSigned` struct is now called `DataSigned`,
and `client_signed` fields have been renamed `data_signed`.
- 015817edb **refactor(messaging)!: Rename `ClientAuthority` -> `DataAuthority`**
This follows from 7dabc4ff3, since these signatures now cover 'data'
messages, which may not necessarily be signed by a client.
BREAKING_CHANGE: The `ClientAuthority` struct is now calle
`DataAuthority`, and `client_auth` fields have been renamed `data_auth`.
=> Rename `Client{Signed,Authority}` -> `Data{Signed,Authority}`

src/messaging/node/mod.rs, src/messaging/node/network.rs, src/routing/network/mod.rs, src/types/mod.rs, src/types/prefix_map.rs
- 104b86894 **refactor!: Move `PrefixMap` to `types` and simplify impls**
The `PrefixMap` type implements a fully generic map-like structure that
only depends on `T: Borrow<xor_name::Prefix>`. As such, it's not really
`messaging`-specific (though it is currently the only call-site).
To keep `messaging` simple, and help with the separation of the
structure of messages from their API, `PrefixMap` has been moved to
`types`. Additionally, `Debug` impls are now derived, the `Hash` impl
has been removed, since it doesn't seem to be used, and serialization is
now transparent (e.g. `PrefixMap<T>` is serialized exactly like
`BTreeSet<T>`).
BREAKING CHANGE: `PrefixMap` has moved from `messaging::node` to
`types`. Additionally, `PrefixMap` and `messaging::node::Network` no
longer implement `Hash`.
=> refactor!: Move `PrefixMap` to `types` and simplify impls

src/dbs/mod.rs, src/dbs/register_op_store.rs, src/node/metadata/register_storage.rs, src/types/register/metadata.rs
When querying storage for register data, we previously did not handle the case
where the cache was empty.
Now we make sure to load from disk, to populate the returned data exchange
struct.
=> fix(register): load from disk if not in cache

Cargo.lock, src/client/config_handler.rs
- 790651ac2 **chore: Update qp2p to get more connection retries**
Hopefully this will make the tests a bit less flaky, though the jury's
still out.
This was also a breaking change for qp2p, but released in a patch
version. Technically though the semver spec says the only rule for
pre-1.0 is "there are no rules". This did require removing a use of the
removed field.
=> chore: Update qp2p to get more connection retries

.github/workflows/e2e.yml
Previously did not recognise the cmd.
Now uses backslash and win equivalent of ´~´.
=> fix(ci): win cmd to remove node dir

.github/workflows/all_prs.yml, .github/workflows/e2e.yml, .github/workflows/main.yml, .github/workflows/pr_client.yml, .github/workflows/pr_data_types.yml, .github/workflows/pr_messaging.yml, .github/workflows/pr_node.yml, .github/workflows/pr_routing.yml, .github/workflows/pr_url.yml
- 8825230fe **ci: Use the rustc version hash in cache keys**
This prevents issues with reusing intermediate build steps when the rust
version changes. This is exacerbated by the fact that caches are not
updated after their first creation, so they would continue to use the
old results, which could never be used.
=> ci: Use the rustc version hash in cache keys

src/dbs/event_store.rs, src/dbs/mod.rs, src/node/metadata/register_storage.rs
This was removed recently, and replaced with an impl limited to register cmds.
But the limitation is unnecessary, and the abstraction will be reused.
=> chore(dbs): bring back the generic event store

.github/workflows/e2e.yml, Cargo.toml, benches/put.rs, examples/client_blob.rs, examples/network_split.rs, src/bin/testnet.rs, src/client/client_api/mod.rs, src/client/config_handler.rs, src/client/mod.rs, src/client/utils/test_utils/test_client.rs
I originally thought I'd have to keep the IGD override in some cases, so spend some time tidying up the `client::Config` APIs (first 3 commits), then decided to just remove the override. The changes are still quite nice though so I've left 'em in.
There will be breakage in `sn_api` and/or `sn_cli` which I'll look at.
---
- a51925c55 **refactor(client)!: Construct `Client` with `Config`**
This changes the signature of `Client::new` to take a `Config` instance
rather than separate optional `config_file_path` and `bootstrap_config`.
This is a better separation of concerns (e.g. set up your configuration,
then constuct a client with that configuration) and will facilitate
further improvements to this API.
BREAKING CHANGE: The signature for `Client::new` has changed to require
a `Config`. …
=> Remove `client` feature and improve client config API

.github/workflows/all_prs.yml, .github/workflows/e2e.yml, .github/workflows/main.yml, .github/workflows/pr_client.yml, .github/workflows/pr_data_types.yml, .github/workflows/pr_messaging.yml, .github/workflows/pr_node.yml, .github/workflows/pr_routing.yml, .github/workflows/pr_url.yml
- 57ac3018a **ci: Fix including Rust toolchain in cache key**
The lookup is missing `outputs` from the path. I miss types.
- c479ac6e3 **ci: Fix/remove use of `matrix.target`**
We were often using `matrix.target` in cache keys, even when there was
no matrix for the target.
In another case (`all_prs.yml`) we had a matrix intended for `os`, but
used the `target` property, so benchmarks were only executed on ubuntu.
=> ci: Fix including Rust toolchain in cache key

examples/client_blob.rs, examples/network_split.rs, src/url/mod.rs, src/url/url_parts.rs
Analogously renames SafeContentType and SafeDataType.
BREAKING CHANGE: Renames the public types
=> refactor: rename SafeUrl to NativeUrl

src/client/client_api/commands.rs, src/client/connections/messaging.rs, src/node/event_mapping/node_msg.rs, src/node/metadata/chunk_records.rs
... also removing aggregation of the ChunkWrites.
Previously we sent to 7 Elders, which lead to a major load on Adults.
3 out of 7 is the smallest number to have at least 1 correctly functioning Elder,
which will forward the msg.
We send to random Elders as to spread the load.
Aggregation of the ChunkWrites are removed both because it's not needed
as the msg has authority from the sender, and also because less than
supermajority of Elders will now be sending the cmds.
=> fix(client): send ChunkWrite to 3 random Elders

examples/client_blob.rs, examples/network_split.rs, src/url/mod.rs
Before, data types were duplicate, as there was one for private, and one
for public.
Now we split out the scope into it's own enum. This makes the structure
more sane.
BREAKING CHANGE: This changes the structure of the NativeUrl.
=> refactor(url): simplify data type, impl scope

src/url/mod.rs, src/url/version_hash.rs
Update versions with VersionHash instead of u64
VersionHash is needed by the new NRS and file containers in `sn_api`
=> VersionHash replacing the u64 versions

Cargo.lock, Cargo.toml, src/client/client_api/mod.rs
From the commit:
```
The tracing crate has a bug when the log feature is enabled. This log
feature is enabled by deep dependencies of self_update. See the issue on
tracing repo here: https://github.com/tokio-rs/tracing/issues/1487
This fix means the API can be used in a Send-context again.
```
This was the bug from a user perspective:
```rust
use std::{collections::HashSet, iter::FromIterator, time::Duration};
use safe_network::client::{Client, Config};
fn main() {
tokio::spawn(async {
let addr = HashSet::from_iter(vec!["172.17.0.2:12000".parse().unwrap()]);
let config = Config::new(None, Some(addr), Some(Duration::from_secs(5))).await;
let c = Client::new(None, config).await;
});
}
```
Yielding:
```
$ cargo check
Checking sn v0.1.0 (~/src/sn)
error[E0277]: `core::fmt::Opaque` cannot be …
```
=> Fix Client::new not being Send

Cargo.lock, Cargo.toml, src/lib.rs
- d88a79c76 **test: Install `color-eyre` for all tests**
This uses [`ctor`] to run a constructor function at the crate root when
compiled for the `test` target. The constructor function simply calls
`color_eyre::install`.
[`ctor`]: https://docs.rs/ctor
=> test: Install `color-eyre` for all tests

src/client/client_api/register_apis.rs, src/types/errors.rs, src/types/register/metadata.rs, src/types/register/mod.rs, src/types/register/reg_crdt.rs, src/url/mod.rs, src/url/version_hash.rs
The pointers are in the form of `NativeUrl`.
This hinders the storage of arbitrary data into the registers,
and moves data storage completely to Adults.
TODO: Use proptest generated data in the tests.
=> refactor(register): make it store pointers only

src/routing/core/msg_handling/mod.rs, src/routing/routing_api/event.rs
=> fix: avoid looping NodeErrorMsg wrapping

examples/client_blob.rs, examples/network_split.rs, src/client/client_api/register_apis.rs, src/types/register/metadata.rs, src/types/register/mod.rs, src/url/mod.rs, src/url/url_parts.rs
`SafeUrl` went `NativeUrl` and by smallest possible vote then to `Url`.
=> rename(nativeurl): rename to url

src/bin/sn_node.rs, src/bin/testnet.rs
- f5534255b **chore: Enable logging in `testnet`**
- d7940639e **chore: Fix log initialisation in `sn_node`**
Contrary to the documentation, `tracing_subscriber::fmt().init()` is not
equivalent to `tracing_subscriber::fmt::init()`, as the former does not
apply env filtering whilst the latter does.
=> Fix log filtering

src/prefix_map/mod.rs
`let descendants: Vec<_> = self.descendants(&prefix).collect();` was holding a read reference to the DashMap while we wrote to it using `let _ = self.sections.remove(&prefix);` sometimes resulting in a deadlock!
=> Fix PrefixMap deadlock

Cargo.lock, src/routing/core/register_storage.rs, src/routing/relocation.rs, src/types/chunk.rs, src/url/mod.rs
- 0a23b8e3e **chore: Update `xor_name`**
Breaking changes were introduced in this minor version which required
some changes at call-sites.
=> chore: Update `xor_name`

src/url/mod.rs
New URLs for NrsMapContainer content were longer than 63 characters and were failing validation when the URL was being parsed while fetching NrsMapContainer content in `sn_api`.
The `set_sub_names` function is only being called in this single place in the API, so the impact of this change should be quite low. It doesn't break the unit test for the function.
=> fix: Setting Sub Names Ignores Url Labels

src/routing/core/messaging.rs, src/routing/core/msg_handling/anti_entropy.rs, src/routing/core/msg_handling/mod.rs, src/routing/routing_api/command.rs, src/routing/routing_api/dispatcher.rs, src/routing/routing_api/mod.rs, src/routing/routing_api/tests/mod.rs
Every time we run `check_for_entropy` we're _reserializing_ the `WireMsg`. 
Now we are not
=> chore: avoid serialise and use original bytes where possible

src/routing/core/messaging.rs, src/routing/core/mod.rs, src/routing/core/msg_handling/anti_entropy.rs, src/routing/core/msg_handling/update_section.rs
- aedbd7176 **chore: Make `clippy` happy again**
These CI checks aren't required atm, so some lint got through.
- b789006fe **refactor: Remove an unnecessary clone of `Section`**
This was being cloned to satisfy the borrow checker, however
`Core::send_ae_update_to_our_section` does not need either `&mut self`
or an owned `Section`, so fixing both of those means we no longer need
the clone.
=> refactor: Remove an unnecessary clone of `Section`

src/client/config_handler.rs, src/node/network.rs, src/routing/routing_api/config.rs
- 8ab3f9096 **refactor: Centralise default node local address**
`routing::Config::default` is now the sole determiner of the default
value for local address, rather than also applying a default in
`node::Network::new`.
- d0f79b1df **fix: Change default local address to `0.0.0.0`**
As part of the recent refactoring of qp2p, the default local address was
changed to `127.0.0.1`, on the basis that it is more secure to require
users to opt-in to public reachability.
Sadly, this change was quite disruptive, and optimises the less common
case. Whilst it may still be desireable to default to local-only, the
specifics of how this is configured needs more thought.
=> Change default local address to `0.0.0.0`

src/routing/core/api.rs, src/routing/core/bootstrap/join.rs, src/routing/core/bootstrap/relocate.rs, src/routing/core/chunk_records.rs, src/routing/core/connectivity.rs, src/routing/core/delivery_group.rs, src/routing/core/messaging.rs, src/routing/core/mod.rs, src/routing/core/msg_handling/agreement.rs, src/routing/core/msg_handling/anti_entropy.rs, src/routing/core/msg_handling/bad_msgs.rs, src/routing/core/msg_handling/dkg.rs, src/routing/core/msg_handling/join.rs, src/routing/core/msg_handling/mod.rs, src/routing/core/msg_handling/relocation.rs, src/routing/core/msg_handling/resource_proof.rs, src/routing/core/msg_handling/service_msgs.rs, src/routing/core/msg_handling/update_section.rs, src/routing/relocation.rs, src/routing/routing_api/dispatcher.rs, src/routing/routing_api/mod.rs, src/routing/routing_api/tests/mod.rs, src/routing/section/mod.rs
- b68f7d47c **refactor: Replace `SectionUtils` trail with an inherent impl**
This is functionally equivalent for our current usage but lets us cut
out a bunch of imports and duplicate signatures, and makes it easier to
identify unused functions (like `extend_chain`).
The methods are all `pub(super)`, which matches the visibility of the
removed `SectionUtils` trait.
=> refactor: Replace `SectionUtils` trail with an inherent impl

.github/workflows/all_prs.yml, Cargo.lock, Cargo.toml
- ba1845740 **ci: Pin specific SHA for `aig787/cargo-udeps-action`**
We should pin by default to ensure CI remains stable. We may want to add
security advisory checking for GitHub Actions in future, to prompt us to
update.
- 4bb18e541 **ci: Use `test-utils` feature when running udeps**
The `test-utils` feature is required for benchmarks and some examples,
and their dependencies are not counted if the feature is not enabled.
- 0e0dcbffb **chore: Remove unused dependencies**
- c9631d047 **ci: Pin specific nightly for cargo udeps job**
This is a slightly speculative fix based on
https://github.community/t/189130 and
https://github.com/rust-lang/cargo/pull/9695. Although it seems this may
have been fixed/worked around in cargo, the latest version of
`cargo-udeps` still depends on cargo 0.54.0 …
=> Fix unused dependency check and remove unused dependencies

.github/workflows/pr_tests.yml
=> ci: disable create_and_retrieve blob tests for stability of CI for now

.github/workflows/commitlint.yml
- 755aa9579 **ci: upgrade `wagoid/commitlint-github-action`**
The new version has tighter defaults, which should prevent us from
committing dodgy commit types like `wip`. The `GITHUB_TOKEN` has also
been removed, since the repository is public and the action is read
only.
=> Upgrade `wagoid/commitlint-github-action`

src/messaging/location.rs, src/routing/core/api.rs, src/routing/core/msg_handling/anti_entropy.rs, src/routing/core/msg_handling/mod.rs
DstLocation name returned an option even though there was no None case in
the method body.
Additional cleanup made as a result of this.
=> fix: remove unnecessary option return value

src/routing/core/comm.rs, src/routing/core/mod.rs, src/routing/core/msg_count.rs, src/routing/core/msg_handling/agreement.rs
Counts incoming and outgoing msgs per node.
Prints out the stats regularily on the following format, for in and out respectively:
```
total
max (address, count)
avg
min (address, count)
```
As a follow up PR there can be expiry/cleanup of the msg counts.
=> feat(msg_count): print stats on in/out going

src/routing/core/comm.rs, src/routing/core/mod.rs, src/routing/core/msg_count.rs, src/routing/core/msg_handling/agreement.rs
- b952ec281 **refactor: remove unnecessary `RwLock` from `MsgCount` state**
`DashMap` itself can synchronise concurrent mutable access to its data,
being based on an `RwLock` internally. As such, we do not need to lock
the individual values and can just use a plain `usize`. This also
removes the need for `async` in that type.
=> refactor: Remove unnecessary `RwLock` from `MsgCount` state

.github/workflows/pr_tests.yml, src/client/client_api/blob_apis.rs, src/client/utils/test_utils/mod.rs
Prior our delay would mean we started querying well before chunks were actually put.
W/ some 20mb testing this seems more reasonable, and initial query doesnt fire until all cmds are complete
=> Ci longer delay before query

.github/workflows/all_prs.yml
- af3485b54 **ci: restore cargo-udeps in a more stable form**
This reverts commit 0a7201e55b461c0a6a21798a5f517601dbe4bbf4.
`CARGO_HTTP_MULTIPLEXING` has been disabled, which seems to have
resolved our network woes, and `-D warnings` is removed from `RUSTFLAGS`
for that job, since new nightlies may introduce additional lints that we
wouldn't otherwise block (the nightly has been 'unpinned' from
`2020-07-05` as well, since this turned out not to be the problem).
=> Stable udeps

.github/workflows/pr_tests.yml, benches/upload_bytes.rs, examples/client_blob.rs, examples/network_split.rs, src/client/client_api/blob_apis.rs, src/client/client_api/data/mod.rs, src/client/client_api/data/pac_man.rs, src/client/client_api/mod.rs
A `Blob` is at least 3072 bytes, as that is min self encryptable bytes.
A `Spot` is smaller than that, and will be encrypted with the client
encryption keys.
Both of these are type safe in that the construction of them will
validate their size.
=> feat(data): distinguish between spot and blob

src/client/client_api/blob_apis.rs, src/client/client_api/mod.rs, src/client/mod.rs
Also changes the misleading name of `encrypt_spot`, to `package_spot`, since
when scope is public, there actually will not be any ecryption.
=> fix: make spot and its address public

src/routing/core/msg_handling/mod.rs
=> fix: ignore proposal from other section to avoid looping on untrusted msg

.github/workflows/digital_ocean_testnet.yml
This can be triggered manually or by commenting `launch-testnet` as a PR review.
=> Add GHA workflow to build a node and run a testnet on Digital Ocean

src/client/connections/messaging.rs
tokio was reporting task JoinError::Cancelled even though the whole task was completed...
As such we move to tracking success, and use that to calculate the failure rate of msg sends
=> fix: avoid client msg sending fake failure

src/client/client_api/mod.rs, src/client/connections/messaging.rs
This triggers an AE flow for the client during creation to get a basic knowledge(at least one valid SAP) of the network before it begins to serve requests from its user.
=> fix(client): send a message to probe the network initially

examples/client_blob.rs, examples/network_split.rs, src/client/client_api/register_apis.rs, src/types/register/mod.rs, src/url/mod.rs
BREAKING CHANGE:
This is to facilitate the new way that files are stored on the network, which was updated to support changes in self encryption.
Self encryption doesn't allow encryption of files less than 3072 bytes in size, so a new type of data was created to support storage of smaller files. This data type is known as a 'spot'.
We need to distinguish between blobs and spots when retrieving files, and the solution is for the DataType on XorUrls to be marked as the Spot type when they are saved (which will be done in the API).
The `encode_blob` and `encode_spot` functions are both introduced for convenience. These accept a BlobAddress and a SpotAddress, respectively. Added a couple of extra tests for checking that `encode_spot` was setting fields correctly.
=> feat: add spot entry to datatype enum

benches/upload_bytes.rs, examples/client_blob.rs, examples/network_split.rs, src/client/client_api/blob_apis.rs, src/client/client_api/data/mod.rs, src/client/client_api/mod.rs, src/client/client_api/register_apis.rs, src/client/mod.rs, src/types/register/mod.rs, src/url/mod.rs
`DataType` enum is simplified to `SafeKey` | `Bytes` | `Register`
`Spot` and `Blob` are - instead of data types - storage mechanisms of `Bytes`.
***
`Bytes` is a simpler, more accurate and direct description
of the "data type", while `Data` is vague and ambiguous
(seems to be what all members of `DataType` are), and
`Spot` and `Blob` are the two size dependent (due to optimisations) 
storage mechanisms for `Bytes`, simply meaning
- `As one chunk, optionally using encryption key`, or
- `As 4+ chunks, using self encryption`.
Fn `read_bytes` (taking `BytesAddress` enum) solves
which underlying storage mechanism is to be used, 
as `BytesAddress` is either `Spot(SpotAddress)` or `Blob(BlobAddress)`
`upload_bytes` uses `bytes.len()` to choose underlying storage
mechanism, and returns …
=> feat(bytes): encapsulate storage mechanism

src/client/client_api/blob_apis.rs
Removes unnecessary calls and waits, with which the parallelisation did not improve speeds - therefore also removed.
Reduces time from ~`40s` to ~`20s` locally (12 threads).
=> refactor(test): optimise seek_in_data test

src/client/client_api/data/pac_man.rs, src/client/errors.rs
Encryption is an option which was passed in when wrapping
bytes in `Chunk`, also when the bytes were self encrypted..
So, since no need to encrypt what is self-encrypted, we pass in
`None` for those cases
Also now propagates any error when packing data map.
=> fix(chunks): do not double-encrypt in packing step

src/client/client_api/blob_apis.rs, src/client/client_api/mod.rs, src/client/client_api/register_apis.rs, src/client/connections/messaging.rs, src/client/utils/test_utils/test_client.rs
adds some client test formatting to aid readability
example for one log line: 
```
DEBUG [src/client/connections/messaging.rs:L373]:
get_register_entry
get_register
send_query
Response obtained for query w/id MessageId(d764..c77d): Some(GetRegister((Ok(Register { authority: Ed25519(PublicKey(311c..d910)), crdt: RegisterCrdt { address: Public { name: 88d289(10001000).., tag: 10 }, data: MerkleReg { roots: {}, dag: {}, orphans: {} } }, policy: Public(PublicPolicy { owner: Ed25519(PublicKey(311c..d910)), permissions: {Key(Ed25519(PublicKey(311c..d910))): PublicPermissions { write: Some(true) }} }) }), "Get-\"hyeyyyyyyyyyybng1tf93a76au7eg3nhuxbtn35o1w4o4fz89c5h9rz7r9dr4farbbeyyyyyyyyyyy\"")))
```
=> chore: add tracing to client messages

src/dbs/errors.rs, src/messaging/data/errors.rs
=> fix: add error message type for ChunkNotFound.

src/bin/log_cmds_inspector.rs, src/client/connections/messaging.rs
Adding some subcommands to the logs inspector tool to be able to generate reports based on a provided msg id or command id. The following three sub-commands are supported with this PR:
- `completed-cmds`: which is the previously existing check on commands spawned/succeeded/failed
- `commands <cmd-id>`: show a report of all commands and sub-commands correlated to the provided id
- `messages <msg-id>`: show a report of all commands/sub-commands correlated to the provided msg id, i.e. commands that were executed as part of handling the message which matches the provided msg id.
```
$ cargo run --release --bin log_cmds_inspector -- ~/.safe/node/local-test-network/ messages 7193..2595
Inspecting testnet logs folder: ~/.safe/node/local-test-network/
...
*** REPORT: The following commands were …
```
=> Feat log analysis tool v2

.github/workflows/digital_ocean_testnet.yml
The PR is misnamed on purpose so the checks are skipped to test out the changes.
EDIT: We can't actually test the condition for the testnet flow since it's triggered by `pull_request_target` and so it uses the workflow file in the default branch.
EDIT 2: See example run [here](https://github.com/lionel1704/safe_network/pull/15)
=> Automated version bump (misnamed on purpose)

sn/src/messaging/system/join.rs, sn/src/prefix_map/mod.rs, sn/src/routing/core/bootstrap/join.rs, sn/src/routing/core/msg_handling/agreement.rs, sn/src/routing/core/msg_handling/join.rs, sn/src/routing/routing_api/tests/mod.rs, sn/src/routing/section/mod.rs
This PR also changes the `JoinResponse::Retry` message to return the expected age for the joining node.
=> fix(routing): don't bail out when handling ElderAgreement if prefix-map is not updated

sn/src/messaging/data/mod.rs
- fcf8f2444 **fix(sn): fix test for `GetChunk` 'data not found' failures**
`QueryResponse::failed_with_data_not_found` is used to prevent sending
'data not found' errors to clients. Clients, in turn, do not retry
errors, only timeouts.
Recently (c0b1770154) the error type returned when a chunk is not found
was changed from `NoSuchData` to `ChunkNotFound`, but the check in
`failed_with_data_not_found` was not updated. This could lead to
spurious client errors when they attempt to read data before it is
available (which would otherwise be covered by the retry on timeout,
since nodes would not forward the data-not-found response).
=> fix(sn): fix test for `GetChunk` 'data not found' failures

sn_api/src/app/files/mod.rs, sn_api/src/app/nrs/mod.rs, sn_api/src/app/resolver/mod.rs, sn_api/src/errors.rs, sn_cli/src/subcommands/nrs.rs, sn_cli/tests/cli_nrs.rs
- `nrs_create` now stops doing the linking logic, it just creates the container
- `nrs_add` API that does like `nrs_associate` but registers topname (`nrs_create`) when needed
- `nrs add -y` flag for CLI to use this functionality
- CLI e2e tests for this
- adapt some `sn_api` tests
=> nrs_add API

sn/src/dbs/kv_store/kv.rs, sn/src/dbs/kv_store/mod.rs, sn/src/dbs/kv_store/tests.rs, sn/src/routing/core/chunk_store/mod.rs
- 41b7e53c6 **refactor(sn): remove redundant `K` type parameter from `KvStore`**
The `Value` trait already included an associated type for the key type,
and this can be referenced directly in signatures without the need for
an additional generic type parameter.
- 75cca06aa **fix(sn): make `KvStore::store` perform atomic immutable writes**
`KvStore` is the database abstraction we use to persist chunks. This is
itself backed by `sled`. `sled` uses a log as one of the underlying
storage primitives, which means that all inserts (even overwrites) will
consume additional space (until the log is compacted, which may happen
irregularly).
However, chunks themselves are write-once which means that we would only
ever need to write a value once. As such, we can use `compare_and_swap`
to write the …
=> Reduce redundant space used by chunks

sn_cmd_test_utilities/Cargo.toml
The `smart-release` tool doesn't support using the `~` method for crates within the workspace.
=> chore: use explicit version for sn_api

sn_cli/Cargo.toml
This way of referencing seems to be required for `smart-release`.
Also took the opportunity to fix the indentation on the other references, as there appeared to be no reason for them to be indented.
=> chore: update sn_api reference style

sn/src/routing/core/api.rs, sn/src/routing/core/bootstrap/join.rs, sn/src/routing/core/bootstrap/relocate.rs, sn/src/routing/core/comm.rs, sn/src/routing/core/delivery_group.rs, sn/src/routing/core/messaging.rs, sn/src/routing/core/mod.rs, sn/src/routing/core/msg_handling/agreement.rs, sn/src/routing/core/msg_handling/anti_entropy.rs, sn/src/routing/core/msg_handling/dkg.rs, sn/src/routing/core/msg_handling/join.rs, sn/src/routing/core/msg_handling/mod.rs, sn/src/routing/core/msg_handling/proposals.rs, sn/src/routing/core/msg_handling/resource_proof.rs, sn/src/routing/dkg/session.rs, sn/src/routing/messages/msg_authority.rs, sn/src/routing/network_knowledge/mod.rs, sn/src/routing/network_knowledge/section_authority_provider.rs, sn/src/routing/routing_api/command.rs, sn/src/routing/routing_api/dispatcher.rs, sn/src/routing/routing_api/mod.rs, sn/src/routing/routing_api/tests/mod.rs
- 6959cbf7f **refactor(sn): replace `(XorName, SocketAddr)` with `Peer`**
In many places, we pass around `Peer`s which were then converted to
`(XorName, SocketAddr)`. Most of the time this ends up at the
`Comm::send*` methods. These methods have been updated to take `Peer`,
and this change has been propagated to anything else that was storing or
passing `(XorName, SocketAddr)`. Overall this is a nice simplification,
and removes more conversions than it introduces.
- e92677fee **refactor(sn)!: remove `SectionAuthorityProviderUtils::elders`**
Since the `elders` field of `SectionAuthorityProvider` is public, this
method is essentially equivalent to `sap.elders.clone()`. Furthermore,
it was barely used (5 call sites).
BREAKING CHANGE: The `SectionAuthorityProviderUtils` trait's `elders` …
=> More peers less problems

sn/src/bin/testnet.rs
Windows OS has an issue of re-building as unable to remove testnet.exe.
=> chore: avoid rebuild on windows for testnet

sn_api/Cargo.toml
- b05f7b64c **fix(sn_api): set `formatting` feature for `time` dependency**
We use time formatting, so this feature should be necessary for the
crate to compile. Weirdly, compilation only fails when publishing, not
when checking or building. It's assumed this has something to do with
feature resolution in workspaces 🤷
=> fix(sn_api): set `formatting` feature for `time` dependency

sn/src/routing/core/messaging.rs, sn/src/routing/core/mod.rs, sn/src/routing/core/msg_handling/agreement.rs, sn/src/routing/network_knowledge/mod.rs, sn/src/routing/routing_api/mod.rs, sn/src/routing/routing_api/tests/mod.rs
This also prevents routing from bailing out fro a command processing when some msgs cannot be sent out, errors are logged but the rest of the process for a commands continues to completion.
=> refactor(routing): use the prefix map updating outcome to decide if current SAP and chain shall be updated

.github/workflows/sn_pr_tests.yml, sn/src/messaging/system/section/mod.rs
- 1fcbabb12 **fix(sn): fix `Eq` for `SectionPeers`**
This would have always returned true, since it was comparing with
itself...
=> fix(sn): fix `Eq` for `SectionPeers`

.github/workflows/release.yml, Makefile, resources/scripts/get_release_description.sh, resources/scripts/insert_changelog_entry.py
The release process is largely the same, but with the introduction of the workspace I've just taken the opportunity to tidy up the workflow a little bit.
To make it a bit more descriptive, the workflow was renamed to 'release' rather than 'main'.
This workflow will be extended to include the changelogs and assets for `sn_api` and `sn_cli`.
I've tested it on my fork:
https://github.com/jacderida/safe_network/releases/tag/v0.38.0
=> ci: release workflow for safe_network crate

.github/workflows/release.yml, resources/scripts/get_release_description.sh, resources/scripts/insert_changelog_entry.py, resources/scripts/output_versioning_info.sh, resources/scripts/publish_crate.sh
The release workflow has been extended to include the sn_api crate.
When there's a release, it's possible that any one, or many crates could have new releases, and the conditions used on jobs have been updated to take this into account. There's been additional scripting added for the changelogs and the release and tag names to be used, that also take this into account.
Tested on my fork:
https://github.com/jacderida/safe_network/actions/runs/1457492565
https://github.com/jacderida/safe_network/releases/tag/safe_api-v0.39.0
=> ci: release workflow for sn_api crate

resources/scripts/output_versioning_info.sh
The intention was for the `gh_release_name` and `gn_release_tag_name` variables to be appended to, and also, the names of the crates were incorrect.
=> ci: fix incorrect github release info

sn/examples/routing_minimal.rs, sn/src/node/event_mapping/mod.rs, sn/src/node/node_api/handle.rs, sn/src/node/node_api/split.rs, sn/src/node/node_ops.rs, sn/src/prefix_map/mod.rs, sn/src/routing/core/mod.rs, sn/src/routing/network_knowledge/mod.rs, sn/src/routing/routing_api/event.rs
=> fix: raise SectionSplit event whenever prefix changed

.github/workflows/bump_version.yml
Incorrect name for the `smart-release` plugin for Cargo, and also updates the name of the job.
=> ci: fix version bump workflow

.github/workflows/bump_version.yml, resources/scripts/bump_version.sh
Also adds some debugging text to try and determine exactly where a failure is.
=> ci: git push without using origin remote

.github/workflows/release.yml, resources/scripts/bump_version.sh
The release workflow now requires the release commit before it will run. This is to prevent the
build stage from running on any push to main, which will include a PR merge that doesn't have a
release commit.
Also added some debugging text for the version bump workflow, which is still failing on the GHA
build agent.
=> ci: prevent release workflow from running

.github/workflows/bump_version.yml
As of today, there's been a newly published version of `smart-release`, 0.6.0, which is newer than
the version I had installed on my development machine. This was the one being installed on the build
agent. Sadly, the behaviour of the 2 are different, and this was what was causing a problem in the
process.
It now looks like they expect you to run the tool by knowing in advance which crates have changes,
which doesn't work for our automated process. After playing around with it for about 20/30 minutes,
I couldn't quite get what it was expecting me to do. This could well be wrong though. It needs
further investigation.
For now, I'm just going to stick with the same version I was running locally.
=> ci: use specific version of smart-release

sn/Cargo.toml, sn/src/bin/testnet.rs, sn/src/routing/core/bootstrap/join.rs, sn/src/routing/core/chunk_records.rs, sn/src/routing/core/comm.rs, sn/src/routing/core/connected_peers.rs, sn/src/routing/core/messaging.rs, sn/src/routing/core/mod.rs, sn/src/routing/core/msg_handling/mod.rs, sn/src/routing/core/msg_handling/service_msgs.rs, sn/src/routing/log_markers.rs, sn/src/routing/mod.rs, sn/src/routing/network_knowledge/peer.rs, sn/src/routing/routing_api/command.rs, sn/src/routing/routing_api/dispatcher.rs, sn/src/routing/routing_api/mod.rs, sn/src/routing/routing_api/tests/mod.rs
- 64373af6f **refactor(sn): add a feature to disable connection pooling**
The feature is named with `unstable-` to indicate that it may be removed
at any time. This allows us to better test changes to connection
management, since we know that all reuse must be coming from connection
management rather than pooling.
- 99fc5e735 **refactor(sn): add a log marker for reusing a connection**
This is mostly informational, but it gives a good indication that
connection reuse is occurring, and how many new connection attempts have
been saved.
- 817099893 **refactor(sn): add an `Option<qp2p::Connection>` to `Peer`**
This allows the `Peer` struct to carry an existing connection to the
peer, if one exists. Currently, the connection must be set on
construction with `Peer::connected`. A reference to the …
=> Connection management

sn/src/client/client_api/queries.rs, sn/src/client/connections/listeners.rs, sn/src/client/connections/messaging.rs, sn/src/client/errors.rs, sn/src/routing/routing_api/tests/mod.rs
=> chore: fail query if we cannot send to more than 1 elder

.github/workflows/bump_version.yml, resources/scripts/bump_version.sh
Removes the use of the `--no-isolate-dependencies-from-breaking-changes` argument, which then performs 'safety bumps' for crates that are dependent on other crates which have had breaking changes, even if that crate has no changes itself. The tool seems better designed to work this way.
=> ci: update use of smart-release for new version

resources/scripts/bump_version.sh
Need to exit when the smart release command fails, as otherwise the script will amend the latest commit (which is not the one we're expecting smart-release to generate).
=> ci: add some debugging and exit on failure

.github/workflows/bump_version.yml
This is now done as per the old workflow. Looks like I missed it.
=> ci: set the github token variable

sn/src/routing/core/mod.rs
- 0b504a471 **fix(sn): fix a compilation error introduced by merge**
PR #743 removed the `SectionAuthorityProvider::peers` method, but a new
call-site was introduced in #740, which was merged first. Thus,
compilation broken when `main` was merged into #743 and this wasn't
noticed in CI.
=> fix(sn): fix a compilation error introduced by merge

.github/workflows/bump_version.yml
It looks like this action quite nicely wraps pushing changes for the version commit and the new tags. I'm still not sure about the use of the token, or whether that's correct, but this token is definitely still enabled.
=> ci: use action to push changes

.github/workflows/bump_version.yml
This may change the GITHUB_ACTOR, which may well be the problem. This variable was getting set to my own username.
=> ci: set token on checkout

resources/jq-filters/connection-tracing.jq, sn/Cargo.toml, sn/src/bin/testnet.rs, sn/src/messaging/serialisation/wire_msg.rs, sn/src/routing/core/bootstrap/join.rs, sn/src/routing/core/comm.rs, sn/src/routing/core/messaging.rs, sn/src/routing/core/msg_handling/mod.rs, sn/src/routing/messages/mod.rs, sn/src/routing/mod.rs, sn/src/routing/network_knowledge/peer.rs, sn/src/routing/network_knowledge/section_authority_provider.rs, sn/src/routing/routing_api/command.rs, sn/src/routing/routing_api/mod.rs, sn/src/routing/routing_api/tests/mod.rs
- 3693f8eb6 **refactor(sn): replace `Sender` with `UnknownPeer`**
The `UnknownPeer` struct is more general, and will make it easier to
propagate connections into more places (e.g. this already propagates
connections into `HandleSystemMsg`). It's also generally easier to use
than `Sender`, and doesn't need any special casing for test-only
purposes.
The downside is that we lose the 'sending to ourself' representation.
This wasn't being used so far though, so it's only a hypothetical. The
comment on `UnknownPeer` attempts to document that 'rough edge' (since
we would otherwise expect to only know peers either through
advertisement, where the name would be known, or through direct
connection, where the connection would be present).
- 92a077572 **chore(sn): add a feature for increased …
=> Join flow connection management

.github/workflows/bump_version.yml, resources/scripts/bump_version.sh
If smart-release doesn't detect any changes, we want the version bumping workflow to just complete without any errors.
=> ci: exit successfully if no changes detected

sn/src/client/client_api/register_apis.rs, sn/src/types/errors.rs, sn/src/types/register/metadata.rs, sn/src/types/register/mod.rs, sn/src/url/mod.rs, sn_api/src/app/files/mod.rs, sn_api/src/app/multimap.rs, sn_api/src/app/nrs/mod.rs, sn_api/src/app/register.rs, sn_api/src/app/resolver/handlers.rs, sn_api/src/app/safe_client.rs, sn_api/src/errors.rs
- adapted registers to hold `Vec<u8>` instead of `Url` in both `sn` and `sn_api`
- did some renaming in the `sn_api` register function names to clear up some confusion because of duplicate names
- higher level register methods in the `register` module are now all prefixed with `register_*`
- lower level register methods in `safe_client` are NOT prefixed with `register_*`
- register entries are size-limited (check is on reg write) at `MIN_ENCRYPTABLE_BYTES`
=> Register entries contain Vec<u8> instead of Url

sn/src/routing/core/comm.rs, sn/src/routing/network_knowledge/mod.rs, sn/src/routing/network_knowledge/peer.rs, sn/src/routing/network_knowledge/section_authority_provider.rs
- 11a328ae0 **refactor(sn): replace `Comm::send` closure with normal `fn`**
The closure was rather massive. Separating out makes it easier to see
what's going on.
- 334f5d353 **refactor(sn): simplify `Comm::send` error handling**
There's now a dedicated error type for `Comm::send_to_one` that better
represents the possible states. In particular, a connection error could
never be from a reused connection, and we avoid having to wrap errors as
much.
- 62908feef **refactor(sn): only recreate failed connections in `Comm::send`**
`Peer`s may hold connections that have been lost due to timeouts etc. As
such, we want to handle connection loss when sending by trying again and
forcing a reconnection. We would previously do this by passing a
`force_reconnection` flag, however in the event of …
=> Connection management part 6

.github/workflows/sn_pr_tests.yml, sn/src/messaging/authority.rs, sn/src/messaging/serialisation/wire_msg.rs
- 3a5622fdf **fix(sn): restore `ServiceMsg` authority check**
The `AuthorityProof` struct is designed to be a proof of valid
authority, by ensuring all possible constructors either generate or
validate a signature. This can only be guaranteed if the field remains
module-private. At some point it seems the field was made `pub(crate)`,
which meant we were missing an authority check for some `ServiceMsg`s,
- 97c540e68 **ci(sn): merge paths filter steps**
The `dorny/paths-filter@v2` action can be configured with multiple named
filters, which is a bit more concise and should be more efficient than
running multiple steps.
In the process, some redundant entries have been removed:
- `url` is no longer present in `sn` (removed in 3fe9d7a66).
- doctests have been removed, as we no longer have any …
=> Trivial miscellania

sn/src/routing/core/msg_handling/agreement.rs, sn/src/routing/core/msg_handling/anti_entropy.rs, sn/src/routing/network_knowledge/mod.rs
=> fix: avoid use outdated keyshare status

.github/workflows/sn_pr_tests.yml, sn/src/bin/sn_node.rs, sn/src/routing/core/bootstrap/join.rs
=> Fix dont fail on join sig agg

.github/workflows/sn_pr_tests.yml
=> ci: limit windows ci checks

sn_cli/tests/cli_cat.rs, sn_cli/tests/cli_dog.rs, sn_cli/tests/cli_files.rs, sn_cli/tests/cli_files_get.rs, sn_cli/tests/cli_nrs.rs, sn_cmd_test_utilities/src/lib.rs
- 9497e671e **refactor: parse different output from `nrs create`**
This command now returns a `Url`, along with a tuple of 3 strings. The strings are:
* a "+" sign to indicate the addition of new content
* the NRS name that was created
* the Safe URL the entry points to
The test helper function that parses the output of the command was updated to return these types and
any callers were updated to use a `Url` directly. Previously, the caller was expecting the Url back
as a `String`, and most were then creating a `Url` from that `String`, so this cuts the
intermediate step.
- 6d0c6b985 **tests: minor changes for out of date tests**
A few things were changed here:
* Use correct method to parse output from `nrs create` commands.
* Update expectations for minor changes in error messages.
* …
=> tests: misc test updates for CLI test suite

sn/src/routing/core/msg_handling/dkg.rs, sn/src/routing/core/msg_handling/mod.rs, sn/src/routing/dkg/session.rs, sn/src/routing/dkg/voter.rs
=> fix: avoid network_knowledge lookup when sending DKGNotReady or DkgSessionUnknown

sn/src/routing/core/msg_handling/dkg.rs, sn/src/routing/dkg/session.rs
- discard DKG session info for older sessions
- skip DkgStart and DkgRetry messages for expired sessions
=> Fixes to DKG Anti-entropy

sn/src/client/connections/messaging.rs
=> fix: order of target length in ElderConn error corrected

sn/src/client/client_api/mod.rs, sn/src/client/client_api/register_apis.rs, sn/src/client/mod.rs, sn_api/src/app/files/mod.rs, sn_api/src/app/multimap.rs, sn_api/src/app/nrs/mod.rs, sn_api/src/app/register.rs, sn_api/src/app/safe_client.rs
- implement basic layout for register operation batching as a WriteAheadLog (`sn` and `sn_api`'s low level register API)
- implement (or fix broken/unimplemented) dry runs for:
- NRS
- FileContainers
- Registers (high level register API)
- Multimap
=> Register op batch, dry runs

Makefile
All of a sudden, the release workflow started failing on Windows because it couldn't upload this file. This file doesn't need to be part of the artifacts anyway, so we can just try to delete it.
=> ci: remove lock file in artifacts

.github/workflows/sn_pr_tests.yml, sn/src/client/client_api/blob_apis.rs, sn/src/client/config_handler.rs, sn/src/client/errors.rs, sn_api/src/app/resolver/mod.rs, sn_api/src/app/resolver/safe_data.rs, sn_api/src/app/safe_client.rs
This also has a minor refactoring in sn_api moving the `SafeData` struct into its own file.
=> fix(client): read_from client API was incorrectly using provided length value as an end index

.github/workflows/release.yml
Trying to delete this file didn't work, so going to attempt to exclude it from the list of files that are uploaded.
=> ci: exclude .cargo-lock file from artifact upload

.github/workflows/release.yml, Makefile, resources/scripts/get_release_description.sh
A lot of work had already been done for this previously, so this commit is just filling in the missing gaps:
* Include the CLI in the release description
* Package the CLI artifacts for deploy
* Upload the artifacts to the GH release
For now I'm avoiding extending publishing for `sn_cli` because we don't have any crates up yet, and we can't get one up until we resolve the issue with the `self_update` reference. We need to get this done because `smart-release` won't work properly until a crate is published.
I've tested this with a dummy release on my fork:
https://github.com/jacderida/safe_network/releases/tag/safe_network-v0.48.0
=> ci: include sn_cli in release process

sn/src/client/client_api/queries.rs, sn/src/client/connections/messaging.rs, sn/src/client/errors.rs
Some situations were mislabelled as InsuffcientElderConnection, implying failed connections, but it was actually a failure in our network knowledge.
This commit adds clarifying error types for this situation
=> chore: add in distinct client errors for comms failure

Cargo.lock, sn_cli/Cargo.toml, sn_cli/src/subcommands/files.rs, sn_cli/src/subcommands/files_get.rs
This was another crate that was using a git reference. It provides progress bars and other
mechanisms for updating terminal user interfaces with progress on long running tasks. We were using
this crate to display some progress bars during the `files get` command.
Obviously, removing the crate means we no longer have the progress bars in the UI, but we already
had a text-based mechanism for displaying progress, so for the time being, we can fall back on this.
We can look at other progress bar crates or refactor `files get` to work in parallel.
The main crate used a design that made use of threads for handling the display and update of
multiple progress bars, but our code for `files get` is synchronous. The forked crate was used
because it had a mechanism for updating the display in a …
=> chore: remove use of `indicatif` crate

.github/workflows/daily_droplet_run.yml, .github/workflows/lands_in_staging.yml
This should run a live WAN testnet, across many droplets whenever we push to the given branch
=> ci: run a droplet testnet daily on main

sn/src/dbs/mod.rs, sn/src/routing/core/chunk_records.rs, sn/src/routing/core/msg_handling/mod.rs, sn/src/routing/core/msg_handling/service_msgs.rs
We a) ensure we choose only adults with space for chunks
and b) when we do hit a DbError for any chunk put, we republish that chunk via elders
=> fix: adult choice per chunk and handling db errors

.github/workflows/daily_droplet_run.yml
=> ci: add missing master to tstnet action call in daily droplet run

resources/scripts/install.sh
Modify the install process so that it downloads the CLI directly from the Github release rather than
an S3 bucket, which doesn't get updated any more.
Unfortunately, we lose some functionality here, namely, the ability to install a specific version of
the CLI. The reason for this is because of the way the release process is currently setup to assign
the tag name to the Github Release. Since we now have 3 crates in the same repo, the tag name that
we're currently assigning is just the version of the `safe_network` crate. So we can't query for a
specific version of the CLI. We can perhaps change the release process so that the tag name is
assigned the version number of each component, and then we'd be able to go for a specific CLI
version.
=> chore: update cli install script for single repo

.github/workflows/release.yml, Makefile, resources/scripts/get_release_description.sh, resources/scripts/insert_changelog_entry.py, resources/scripts/install.sh, resources/scripts/output_versioning_info.sh, sn_cli/Cargo.toml, sn_cli/src/operations/helpers.rs, sn_cli/src/operations/node.rs, sn_cli/tests/cli_node.rs, sn_cmd_test_utilities/src/lib.rs
- 30950813c **ci: release tag_name to include 3 crate versions**
Rather than just having the `safe_network` crate version, the tag name field will now include the
version numbers of the 3 crates. This will enable us to be able to install a specific version of the
CLI. This tag name should always be unique, since there will always be at least 1 crate with a
change in it.
The title of the release will also include the names and versions of each of the components, even if
one crate didn't change.
The commit message will still just include the crates that changed, so that we know which publishing
stages to run.
Also fixes a little bug here with one of the asset hashes not being set correctly.
- c4fd95037 **chore: remove `self-update` feature from `node install`**
This feature should really …
=> Release Process and Specific Version Updates

Cargo.lock, sn_cli/CHANGELOG.md, sn_cli/Cargo.toml
This was a manually generated commit, because smart-release didn't detect any changes in the sn_cli crate.
=> chore(release): sn_cli-v0.39.2

sn_api/src/app/files/file_system.rs, sn_api/src/app/files/files_map.rs, sn_api/src/app/files/mod.rs, sn_api/src/app/multimap.rs, sn_api/src/app/register.rs, sn_api/src/app/safe_client.rs, sn_api/src/errors.rs
This also improves error reported by files container api. Example output when uploading a file is uploaded but verification fails:
```
FilesContainer created at: "safe://hyryyryynzxkzkmpixzurnfyqziabtgpqc9bp6zbsdixmrf1h9paiaz9fc9myeuy?v=hgip1akd6y1eg5cnzxjfqayrb7yyyobuttozu3uwcoggpcnoq1aho"
E  README.md  <Content may have been correctly stored on the network, but verification failed: safe://hy8oyeyybd55gmbsw43438bu1zmn5xk1yqtiicdj6hce7t5rsu41om5ps6ecy> 
```
=> fix(api): when in dry-run was still requiring a connection by some APIs

Cargo.lock, sn_api/Cargo.toml, sn_api/src/app/consts.rs, sn_api/src/app/files/file_system.rs, sn_api/src/app/files/files_map.rs, sn_api/src/app/files/metadata.rs, sn_api/src/app/files/mod.rs, sn_api/src/errors.rs, sn_cli/src/subcommands/files.rs, sn_cli/src/subcommands/files_get.rs, sn_cli/src/subcommands/helpers.rs, sn_cli/src/subcommands/xorurl.rs, sn_cli/tests/cli_cat.rs, sn_cli/tests/cli_dog.rs, sn_cli/tests/cli_files.rs, sn_cli/tests/cli_nrs.rs
BREAKING CHANGE: change in sn-api ProcessedFiles which is part of public API.
=> refactor(api): make ProcessedFiles to contained fully typed elements instead of simply strings

sn_cli/README.md
The CLI user guide hadn't been updated for some time, so I brought it it in line with current features. Where relevant so far, I also trimmed the text to make it more concise.
The following updates were made:
* Reduce the indentation levels of the whole document.
* Add a Quickstart section to get users going with a single command if they want to avoid reading lots of setup text. Windows
was explicitly left out because having a Git Bash installation does not constitute the ability to quick start.
* Re-work the previous 'Download' section to an 'Installation and Setup' section.
* Restructure the 'Networks' section with a new example using remote networks.
* Temporarily remove the 'Interactive Shell' section. This was using a feature that didn't exist any more.
* Temporarily remove the …
=> docs: align cli user guide with current features

sn_api/examples/file_upload.rs, sn_api/src/app/files/file_system.rs, sn_api/src/app/files/mod.rs, sn_api/src/app/nrs/mod.rs, sn_api/src/app/resolver/mod.rs, sn_cli/README-symlinks.md, sn_cli/src/subcommands/files.rs, sn_cli/src/subcommands/xorurl.rs
- Changed the `files_container_create` API to now create just an empty FilesContainer
- Adding a new `files_container_create_from` API which creates a FilesContainer with files uploaded from a local folder.
- All path args passed to files container APIs can either be &str, std::Path, or std::PathBuf
BREAKING CHANGE: changes to the files public API.
=> feat(api): change files APIs to accept std::Path for path args rather than only &str

sn/src/bin/sn_node.rs, sn/src/node/cfg/keypair_storage.rs, sn/src/node/error.rs
BREAKING CHANGE: some public API error types were removed, and others were changed.
=> refactor(node): removing unnecessary Error type definitions

sn/src/client/client_api/commands.rs, sn/src/client/connections/listeners.rs, sn/src/lib.rs, sn/src/node/routing/core/capacity/mod.rs, sn/src/node/routing/core/chunk_records.rs, sn/src/node/routing/core/msg_handling/service_msgs.rs
- Adds max_num_faulty_elders based on const assumption for
max number of faulty Elders as 1/3.
- Adds at_least_one_correct_elder based on max_num_faulty_elders.
These numbers were made dependent on global consts, as was asked for in
the todo comment prior to this change.
Also, the number of Elders to whom a client sends a chunk is not based
on the chunk copy count, but on our assumptions on max number of faulty
Elders, hence renaming the variable.
=> refactor(elder targets): rename + use glob const

.github/workflows/sn_pr_tests.yml, sn/src/client/client_api/blob_apis.rs
We've seen occasionally flakey e2e tests. This sets the basic e2e tests to run 5 times back to back, which should increase confidence in each PR being merged and reduce fluke ci-passes
=> ci: use zsh to repeat e2e tests

sn/src/client/connections/listeners.rs, sn/src/client/connections/messaging.rs, sn/src/client/connections/mod.rs
That could cause issues if another query _starts_ before the prior listener has been removed.
This is not a complete fix to concurrent clients here. But should at least get tests in line with expectations.
A larger rework will be needed for query repsonse handling
=> fix: dont remove listener on a thread

sn/src/node/routing/core/mod.rs
Eliminates the redundant AE rounds that happen with the DataExchange messages on every churn.
On a 11 node network:
```
Before
-------------------------
AeResendAfterRetry found: 161 times
AeSendRetryAsOutdated found: 157 times
After
-------------------------
AeResendAfterRetry found: 12 times
AeSendRetryAsOutdated found: 9 times
```
=> fix(churn): use latest PK to send DataExchange messages

resources/scripts/bump_version.sh
- 2eaca4479 **ci: version bumping process to use 3 crates**
Previously we had an issue where `smart-release` would error if `sn_api` or `sn_cli` had a change,
but `safe_network` didn't. If it's invoked using all 3 crates, this doesn't happen. I was sure I had
tried this mechanism before and it didn't work, but that may have been with an earlier version.
I also instructed the script to exit with an error when the `smart-release` output contains
'Manifest version of provided package' in its output. This is intended to detect such output as:
```
[INFO ] Manifest version of provided package 'sn_cli' at 0.43.1 is sufficient to succeed latest
released version 0.43.0, ignoring computed version 0.43.2
```
What this means is, a crate had its version bumped, a tag was pushed and created, but it …
=> ci: version bumping process to use 3 crates

.github/workflows/sn_pr_tests.yml
Sometimes, we could get slight delays which might push the repeat tests over 5 minutes
=> ci: increase testnet initial client tests timeout for a bit more margin

sn_cli/README.md
The `files sync` command is described, but this time a bit more succinctly. The `--update-nrs` argument was omitted because it doesn't seem to be working any more.
Also changed:
* Fixed the indentation levels for the table of contents.
* Provide a small section to describe an example directory used by all commands.
* Update other sections to use the above examples directory.
* Clarify description of container base paths.
* Move the `files ls` section immediately after `files put`, as I think it makes sense to introduce the concept of listing files after you've uploaded them.
* Trim down the `files get` section.
* Trim down the `files tree` section.
=> docs: reintroduce the `files sync` command

README.md
This is updated to reflect the fact that the repository is now a workspace and to provide a very small 'elevator pitch' type description of the network.
=> docs: describe workspace repository in main readme

sn/src/client/client_api/queries.rs, sn/src/client/config_handler.rs, sn/src/node/routing/api/dispatcher.rs, sn/src/node/routing/core/comm.rs
The last comnet showed that for larger files we want a larger query timeout. This seems like it should probably be the default. So that's addressed here, alongside some query timeout jitter to help smooth out request barrages
This should help prevent nodes being hammered over the same period.
This PR also increases the default client query time to 500s.
=> feat(sn/client): Add jitter into client query request timing

.github/workflows/daily_droplet_run.yml, Makefile, sn_cli/tests/cli_files.rs, sn_cli/tests/cli_node.rs, sn_cmd_test_utilities/src/lib.rs
- 3b4069427 **ci: nightly release run**
Sets up a release build to run nightly. It runs as follows:
* Build the node binary using the latest code
* Launch the testnet on Digital Ocean using our custom action
* Run the client tests against the testnet
* Run the API tests against the testnet
* Run the CLI tests against the testnet
* Kill the testnet
* Bump any version numbers and push a new release commit to `main`
The push to `main` should then trigger the release workflow, which will run as usual.
A few noteworthy points:
* In theory, the testnet custom action can build the node on a large Digital Ocean VM, but I found
it unreliable.
* The 3 test suites _could_ run in parallel, but for now they run sequentially.
* All test suites get the opportunity to run, even if the previous one fails. …
=> ci: nightly release run

.github/workflows/daily_droplet_run.yml, resources/scripts/cli_tests.sh
- 199100a4b **ci: run nightly tests in same fashion as pr tests**
The nightly client tests were running slightly differently from the same tests in the PR run. This
brings them into parity.
- 1ea810af6 **ci: switch off verbose logging for cli tests**
The CLI tests parse output from the CLI and they expect it to be in a certain form, so any
additional logging needs to be switched off.
The other tests in the PR workflow switch verbose logging on because it's useful for those tests and
there are also some scripts that parse the output to try and determine if the network is ready.
=> ci: run nightly tests in same fashion as pr tests

resources/scripts/bump_version.sh
The `crate_name` local variable is reintroduced to perform this check properly. This was accidentally removed in 2eaca44794e330420511e625a430005635f520ba.
=> ci: fix crate change check in version bumping

sn/src/node/cfg/config_handler.rs
=> chore: keep all logs by default

sn/src/client/connections/messaging.rs
Priously we always took the first 3 from the SAP's elders vec. This should spread
commands out over all elders more fairly.
=> feat(sn/client): randomize elder contact on cmd.

.github/workflows/sn_pr_tests.yml, sn/src/bin/sn_node.rs, sn/src/node/core/msg_handling/service_msgs.rs
=> fix: make log files rotate properly

.github/workflows/daily_droplet_run.yml, resources/scripts/bump_version.sh
- 4dbda7363 **ci: remove smart release dry run**
Previously, the dry run was being used to detect a string of text I had seen appear when version
bumping succeeded but publishing of one or more crates failed.
Two days ago, Smart Release had a new release (v0.8.0) and it seems this assumption no longer holds.
The text is appearing now, but the version it's referring to has had its crate published. This was
the only thing the dry run was checking, so it doesn't serve any purpose now.
The scheduled time for the nightly run was also pushed back a couple of hours, as we'd seen Bors
still running and pushing to main after 0230.
=> ci: remove smart release dry run

resources/scripts/api_tests.sh, sn_api/src/app/multimap.rs, sn_api/src/app/nrs/mod.rs, sn_api/src/app/nrs/nrs_map.rs, sn_api/src/app/resolver/handlers.rs, sn_api/src/app/resolver/mod.rs, sn_api/src/app/resolver/safe_data.rs, sn_cli/src/subcommands/cat.rs, sn_cli/src/subcommands/dog.rs, sn_cli/tests/cli_cat.rs, sn_cli/tests/cli_nrs.rs
- 2b06d802c **refactor: nrs map fetch and rename multimap**
The `MultimapKeyValues` type alias was renamed to `Multimap` to make it easier to work with. Some
functions were also renamed to the same effect, e.g., `fetch_multimap_values` -> `fetch_multimap`.
The function for retrieving the NRS map was also refactored. Some aspects were broken down into
smaller functions to reduce some complex if/else cases. Things were also setup for the version in
the last entry in the Multimap to be collected. This is going to be used with the returned
NrsMapContainer, to facilitate returning links to immutable content, which doesn't have a version.
Currently the code isn't setup to support that scenario.
- e87774f48 **feat: retrieve immutable content via nrs**
Changes the resolver to enable retrieval of …
=> feat: retrieve immutable content via nrs

sn/src/client/connections/messaging.rs
=> Chore client improvement

sn_api/examples/fetch_file.rs, sn_api/examples/file_upload.rs, sn_api/src/app/files/file_system.rs, sn_api/src/app/files/files_map.rs, sn_api/src/app/files/mod.rs, sn_api/src/app/mod.rs, sn_api/src/app/multimap.rs, sn_api/src/app/nrs/mod.rs, sn_api/src/app/register.rs, sn_api/src/app/resolver/mod.rs, sn_api/src/app/test_helpers.rs, sn_cli/src/cli.rs, sn_cli/src/operations/auth_and_connect.rs, sn_cli/src/operations/mod.rs, sn_cli/src/subcommands/cat.rs, sn_cli/src/subcommands/dog.rs, sn_cli/src/subcommands/files.rs, sn_cli/src/subcommands/files_get.rs, sn_cli/src/subcommands/keys.rs, sn_cli/src/subcommands/nrs.rs, sn_cli/src/subcommands/xorurl.rs
BREAKING CHANGE: changes in `Safe` public API.
=> fix(api): dry-runner was making a connection to the network

sn/src/client/client_api/file_apis.rs, sn/src/messaging/data/data_exchange.rs, sn/src/messaging/data/errors.rs, sn/src/messaging/data/mod.rs, sn/src/messaging/serialisation/mod.rs, sn/src/messaging/system/mod.rs, sn/src/messaging/system/node_msgs.rs, sn/src/node/core/data_records/mod.rs, sn/src/node/core/data_storage/mod.rs, sn/src/node/core/messaging.rs, sn/src/node/core/mod.rs, sn/src/node/core/msg_handling/agreement.rs, sn/src/node/core/msg_handling/anti_entropy.rs, sn/src/node/core/msg_handling/dkg.rs, sn/src/node/core/msg_handling/mod.rs, sn/src/node/core/msg_handling/service_msgs.rs, sn/src/types/log_markers.rs
We had `StoreData`, `ReplicateData` and `RepublishData`, where it was a bit confusing what did what.
It is now simplified to `ReplicateData` cmd and `CouldNotStoreData` event, where one is
used to send data to Adults, and the other is sent by Adults to Elders
when they can't handle the data.
=> chore: simplify data replication cmds and flow

.github/workflows/sn_pr_tests.yml
=> fix: different artifact name

Makefile, resources/scripts/api_tests.sh, resources/scripts/cli_tests.sh, sn_api/src/app/files/mod.rs, sn_api/src/app/multimap.rs, sn_api/src/app/nrs/mod.rs, sn_api/src/app/nrs/nrs_map.rs, sn_api/src/app/resolver/mod.rs, sn_cli/src/subcommands/cat.rs, sn_cli/src/subcommands/dog.rs, sn_cli/src/subcommands/files.rs, sn_cli/src/subcommands/helpers.rs, sn_cli/src/subcommands/nrs.rs, sn_cli/tests/cli_cat.rs, sn_cli/tests/cli_dog.rs, sn_cli/tests/cli_files.rs, sn_cli/tests/cli_nrs.rs
- 1115093a4 **feat: store full public name in nrs map**
Entries will now use the full public name reference, rather than the just subname. Like so:
* example -> link
* a.example -> link
* b.example -> link
* a.b.example -> link
This is to facilitate resolving NrsMapContainer content using its XorUrl, which effectively prints
the NRS map. It was a feature we had that broke at some point. Right now, the XorUrl of the
container will resolve the content the topname is linked to, or will result in an error if the
there's no topname link.
- effc6fa5a **tests: rework nrs tests and provide more coverage**
Added more coverage for code paths that weren't being tested:
* `nrs_create` duplicate topname
* `nrs_associate` with non-versioned files container link
* `nrs_associate` with non-versioned NRS …
=> Store Full Public Name in NRS Map and Remove API URL Sanitise

Cargo.lock, sn/Cargo.toml, sn/src/client/client_api/mod.rs, sn/src/node/api/dispatcher.rs, sn/src/node/api/tests/mod.rs, sn/src/node/core/api.rs, sn/src/node/core/connectivity.rs, sn/src/node/core/delivery_group.rs, sn/src/node/core/messaging.rs, sn/src/node/core/mod.rs, sn/src/node/core/msg_handling/agreement.rs, sn/src/node/core/msg_handling/dkg.rs, sn/src/node/core/msg_handling/join.rs, sn/src/node/core/msg_handling/relocation.rs, sn/src/node/core/relocation.rs, sn/src/node/network_knowledge/mod.rs, sn/src/node/network_knowledge/section_authority_provider.rs, sn/src/node/network_knowledge/section_peers.rs, sn/src/node/node_info.rs
Also, removing an archived section member when its state is previous to last five Elder churn events.
=> refactor(node): keep section Left/Relocated members in a separate archive container

.gitignore, Cargo.lock, Cargo.toml, sn/Cargo.toml, sn/src/bin/testnet.rs, sn/src/lib.rs, sn/src/node/core/comm.rs
uses the launcher option to enable flamegraph generation per node
=> feat(testnet): add `flame` arg to use cargo flamegraph

sn/src/lib.rs
BREAKING CHANGE: piggybacking on arbitrary typo fix in sn
to cause a version bump
=> feat: fix typo

sn_api/src/app/mod.rs, sn_cli/src/cli.rs, sn_cli/src/operations/auth_and_connect.rs, sn_cli/src/shell.rs, sn_cli/src/subcommands/xorurl.rs
When CLI is run in shell mode (i.e. no args passed), it now keeps a Safe API instance and connection in its internal state, so it doesn't need to connect to the network for every command.
=> fix(cli): CLI shell was creating a new Safe API instance, and connecting to the net, for every command

sn/src/messaging/serialisation/mod.rs, sn/src/node/api/cmds.rs, sn/src/node/api/dispatcher.rs, sn/src/node/core/data_records/mod.rs, sn/src/node/core/mod.rs, sn/src/node/core/msg_handling/mod.rs, sn/src/node/core/msg_handling/service_msgs.rs
chore(node): Batch pending requests together per name 9bb839e7ad35bd06472807601ca1500e7c5b4502
Previously we were only allowing one operation id, which could be overwritten by new clients.
This allows client requests to await one response together
chore(sn/node): only prioritise service cmd/query with permits. 75efdb52cbc403f916e1780a27fa00b91a722da8
Previously we were holding permits in a RwLock struct for any command.
Now we remove both the conecpt of permits here, removing one potential
locking loction, and the unused message prioritisation is removed to
clean that up.
Now we simply check if we have max allowed pending queries at any one
time, and if so, we drop inbound queries.
=> Feat no permits any more

resources/scripts/api_tests.sh, sn/src/client/client_api/register_apis.rs, sn_api/src/app/multimap.rs, sn_api/src/app/nrs/mod.rs, sn_api/src/app/nrs/nrs_map.rs, sn_api/src/app/resolver/handlers.rs, sn_api/src/app/resolver/mod.rs, sn_api/src/app/resolver/safe_data.rs, sn_api/src/app/test_helpers.rs, sn_cli/src/subcommands/cat.rs, sn_cli/src/subcommands/dog.rs, sn_cli/src/subcommands/helpers.rs, sn_cli/src/subcommands/nrs.rs, sn_cli/tests/cli_cat.rs, sn_cli/tests/cli_dog.rs, sn_cli/tests/cli_files.rs, sn_cmd_test_utilities/src/lib.rs
- ced0f6631 **feat: retrieve subname version**
The `nrs_get` function is changed to make use of the version argument to retrieve a subname at a
specific version.
A helper struct was created to reduce test verbosity. It uploads a file container and stores file
path/URL pairs in a hash table.
- b9ceb2290 **tests: update nrs tests to use helper**
The helper was moved into the test_helpers module and renamed to TestDataFilesContainer, since this
seems more accurate.
A test was added for retrieving a topname link. This is arguably covered by the `nrs_associate`
tests, but I think it's good to have this test to call it out as functionality we don't want to
break.
- 0bc50ae33 **feat: resolve nrs map container content**
The resolver can now return `NrsMapContainer` content, which can then be …
=> Resolve NRS Map Container Content

.github/workflows/daily_droplet_run.yml, resources/scripts/install.sh, sn_cli/README.md
Give users the option to run the CLI installer as sudo.
In this case, the CLI will be installed to /usr/local/bin, which is very common for installations on
Linux. That location is almost always already on PATH, even in minimal setups. This removes the need
for modifying any of the user's shell configurations, which some users don't like. I've also
personally dealt with users who had a problem when the installer wasn't modifying their shell
configuration correctly.
Some simple installer tests were added to the nightly configuration and the README was also updated
with new instructions, which included fixing an invalid link to the install script.
I tested the install tests on my fork:
https://github.com/jacderida/safe_network/actions/runs/1829688162
=> chore: sudo based installation for cli

.github/workflows/daily_droplet_run.yml, resources/scripts/install.ps1, sn_cli/README.md
Provide a Powershell install script for Windows users. This removes the requirement for using Git
Bash or other Linux emulation to setup the CLI.
The install process is:
* Download and install the Visual C++ Redistributable
* Create the `%USERPROFILE%\.safe\cli` directory
* Add `%USERPROFILE%\.safe\cli` to the user `PATH` variable
* Download and unpack the latest version of `safe` to `%USERPROFILE%\.safe\cli`
A few points worth noting. First, the script can run without admin access, but the VC++ install
requires that, so it will elevate to admin to run that. Second, the script is idempotent, so it will
run OK, if, e.g., VC++ is already installed. Third, the addition of the `PATH` variable
unfortunately requires users to start a new Powershell session. Finally, if VC++ was installed, that …
=> chore: powershell install script for cli

sn/src/messaging/system/node_msgs.rs, sn/src/node/core/data/records/liveness_tracking.rs, sn/src/node/core/data/storage/mod.rs, sn/src/node/core/messaging/handling/mod.rs, sn/src/node/core/messaging/handling/service_msgs.rs, sn/src/node/core/messaging/handling/update_section.rs, sn/src/types/log_markers.rs
Tweaks the liveness tracker to detect nodes that begin to accumulate pending operations. These deviant nodes' data are pre-emptively replicated to avoid data loss and improve fault tolerance in the network.
=> Active Data Republishing

Makefile
I just read on the forum that some version were not release and my PR was the culprit. I indeed think it was me! Sorry!
It seems there are generally [two better solutions](https://sourcegraph.com/search?q=context:global+SHELL%5C+%3D.*%5B%5E/%5Dbash+file:%5EMakefile&patternType=regexp), one is `SHELL = bash`, the other is `SHELL = /usr/bin/env bash`.
I have opted for `SHELL = bash` as it seems more portable. I assume this takes the `bash` from the `PATH` environment variable, so should be good to go on Linux, Windows and MacOS.
@jacderida @joshuef Let me know what you guys think. (What is `bash` needed for, actually?)
=> Sorry! Fix Makefile shell for real this time?

.github/workflows/bors.yml, .github/workflows/sn_pr_checks.yml, .github/workflows/sn_pr_tests.yml, sn/examples/put_get.rs, sn/src/lib.rs
Adds an example to launch many clients uploading many files, and then
verify those uploads.
This is handy to test node load and client throughput.
Currently it's not used in CI anywhere.
=> chore: add put_get chunk soak example

.github/workflows/bors.yml, .github/workflows/sn_pr_tests.yml, sn/src/client/client_api/register_apis.rs
Previously we needlessly attempt to check for a reg which
didnt exist, to confirm that it didnt.
This took a QUERY_TIMEOUT length of time, and was obviously slow.
This speeds up the test from ~4 mins to 7secs
=> chore: remove pointless and long checks in reg batch

sn_cli/tests/cli_files.rs
=> fix: char string updates after 1.59 rust

Cargo.lock, sn/src/client/connections/listeners.rs, sn/src/client/connections/messaging.rs, sn/src/dbs/chunk_store.rs, sn/src/node/api/cmds.rs, sn/src/node/api/dispatcher.rs, sn/src/node/api/mod.rs, sn/src/node/core/comm/mod.rs, sn/src/node/core/data/records/liveness_tracking.rs, sn/src/node/core/data/records/mod.rs, sn/src/node/core/data/storage/chunks.rs, sn/src/node/core/data/storage/mod.rs, sn/src/node/core/data/storage/registers.rs, sn/src/node/core/messaging/handling/anti_entropy.rs, sn/src/node/core/messaging/handling/mod.rs, sn/src/node/core/messaging/handling/service_msgs.rs, sn/src/node/core/messaging/handling/update_section.rs, sn/src/node/core/mod.rs, sn/src/types/cache/mod.rs, sn/src/types/connections/link.rs, sn/src/types/connections/mod.rs, testnet/bin.rs
=> Remove Unused Links

.config/nextest.toml, .github/workflows/pr_test_results.yml, .github/workflows/sn_pr_tests.yml, sn_cli/src/operations/config.rs
The PR tests have been changed to use Nextest to perform the test runs. Nextest can produce test
reports in the popular Junit format, which means we can publish the test results along with the PR.
Since it was tedious to copy and upload the reports as artifacts, this was encapsulated in a custom
`cargo-nextest` action.
The following changes were made to the existing run:
* Remove the `build` job. Everything performed in this job is also now performed in the test stages,
so as far as I can see, it doesn't serve a purpose any more. Since it was running concurrently,
removing it won't save any time, but it was now using unnecessary resources.
* Remove use of the `paths-filter` action. The unit tests are quick to run, so we may as well just
run all of them.
* The client tests are performed in …
=> ci: use nextest as test runner

.github/workflows/daily_droplet_run.yml, .github/workflows/pr_test_results.yml
Like CI, the nightly release run has now been updated to use Nextest.
Each of the three test runs are now performed in parallel and we're going to attempt to use ten
threads for the CLI run.
The network we perform the tests against has been updated to use 15 nodes.
=> ci: use nextest for nightly runs

.github/workflows/daily_droplet_run.yml
Running all three jobs at the same time didn't seem to be stable.
Going to try now with the client and API tests running at the same time, then let the CLI tests run
on their own, but still try with 10 threads.
Also added an explicit build step to the client tests, to avoid timeouts when performing the test
run.
=> ci: run cli tests after api and client

.github/workflows/daily_droplet_run.yml, .github/workflows/sn_pr_tests.yml
Foolishly, I had forgotten to include key generation before the test run, which hopefully explains
the failures I was seeing in the previous runs.
This has also been included for the nightly run too.
With this done, the CLI tests should be able to run for PRs, as it was before.
=> ci: re-enable cli tests for pr tests

Cargo.lock, sn/Cargo.toml, sn/examples/routing_stress.rs, sn/src/client/client_api/mod.rs, sn/src/client/client_api/register_apis.rs, sn/src/dbs/event_store.rs, sn/src/dbs/lru_cache.rs, sn/src/messaging/msg_id.rs, sn/src/messaging/serialisation/wire_msg.rs, sn/src/node/api/tests/mod.rs, sn/src/node/core/bootstrap/join.rs, sn/src/node/core/comm/mod.rs, sn/src/node/core/data/records/liveness_tracking.rs, sn/src/node/core/data/storage/registers.rs, sn/src/node/core/delivery_group.rs, sn/src/node/core/messaging/handling/anti_entropy.rs, sn/src/node/core/mod.rs, sn/src/node/ed25519.rs, sn/src/types/address/mod.rs, sn/src/types/keys/public_key.rs, sn/src/types/prefix_map/mod.rs, sn/src/types/register/mod.rs, sn_api/Cargo.toml, sn_api/src/app/register.rs, sn_api/src/app/resolver/mod.rs, sn_cli/Cargo.toml
This is a step towards integrating sn_dbc into safe_network.
Changes:
* bump bls_dkg from 0.9.0 to 0.9.2
* bump self_encryption from 0.27.1 to 0.27.4
* bump xor_name from 4.0.0 to 4.0.1
* code fixups to use updated deps
=> chore: bump bls_dkg, self_encryption, xor_name

.github/workflows/release.yml, resources/scripts/bump_version.sh, resources/scripts/get_release_description.sh, resources/scripts/insert_changelog_entry.py, resources/scripts/output_versioning_info.sh, sn_dysfunction/README.md
The release workflow is extended to include the dysfunction crate. Add dysfunction to:
* Version bumping
* Version outputs for release process
* The release changelog
* Publishing as the first crate
A basic README was also added to the dysfunction crate as this seems to be a prerequisite for a
publish.
Got the OK from Josh to merge this one, so I'll go ahead and merge it so I can do the first publish of dysfunction.
=> ci: add sn_dysfunction to release process

sn_dysfunction/CHANGELOG.md
This is a manually generated commit to try and get the first release and publish of dysfunction.
=> chore(release): sn_dysfunction-0.1.0/safe_network-0.58.8/sn_api-0.58.0/sn_cli-0.51.0

.github/workflows/release.yml
This wasn't included previously because the safe_network crate used to be the first crate published and it didn't require other version numbers.
=> fix: output version info in sn publish stage

.github/workflows/release.yml
This needs to be the directory of the crate in the workspace and not the actual name.
=> fix: use correct crate name/path in publishing

.github/workflows/daily_droplet_run.yml
github ui cant manually trigger actions until they've run,
sor reverting this for now so we can trigger a release to debug
that flow
=> ci: revert nightly release run naming

sn/src/node/core/data/storage/mod.rs, sn/src/node/core/messaging/handling/mod.rs
Otherwise the suspects will be the new holders again.
Also renames republish to replicate, as per previous conversations (discourse 10th Feb).
=> fix(replication): exclude suspects from current

sn_cli/src/operations/helpers.rs, sn_cli/tests/cli_node.rs, sn_cmd_test_utilities/src/lib.rs
With the addition on the dysfunction crate, this introduced a new version number into the tag name.
The parsing had to be updated for this.
I've also re-enabled the test that would have caught this. It shouldn't be as much of a problem with
nextest, which has the ability to retry tests. I've seen the rate limited stuff passing ok on
retries. If we see it fail, we can disable it again.
=> fix: node install command to use correct version

resources/scripts/bump_version.sh
When the release process was updated for the dysfunction crate, the part of the script that detects
which crate has changes wasn't correctly updated.
This meant we weren't detecting changes in the safe_network crate and last night's release commit
didn't have any crates listed in the commit message.
=> fix: detect changes to safe_network crate

.github/workflows/daily_droplet_run.yml
Though the test jobs have the `launch-testnet` job as a dependency, they still run even if `launch-testnet` fails. Since there is no prospect of a successful test run if we have no testnet, it would be better if the whole workflow was just cancelled.
=> ci: abandon nightly run if testnet launch fails

sn_cli/tests/cli_node.rs
Sadly, this test is subject to rate limiting and sometimes fails, even with retries. It's not worth having the nightly release fail because of this test, so I'm just disabling it again.
=> tests: disable node install test

resources/scripts/bump_version.sh
The version bumping script was using a new variable without initialising it correctly. This was
causing smart-release to run when there were no changes for any crates, which smart-release treats
as an error.
Also changed the script to unambiguously treat these variables as strings.
=> fix: define variable before use

resources/scripts/bump_version.sh
This was causing the tags to be created incorrectly and a run failed because a tag that already
existed was being pushed.
Also changed 'boolean' references to unambiguously refer to them as strings.
=> fix: incorrect variable ref in version bumping

.github/workflows/benchmark_prs.yml, .github/workflows/benchmarks.yml, .github/workflows/benchmarks_pages.yml, Cargo.lock, sn/benches/upload_bytes.rs, sn_api/Cargo.toml
=> Chore bench improvement

Cargo.lock, sn_api/Cargo.toml, sn_api/src/app/helpers.rs, sn_api/src/app/wallet.rs, sn_api/src/errors.rs, sn_cli/src/subcommands/dog.rs, sn_cli/src/subcommands/wallet.rs, sn_cli/tests/cli_wallet.rs
This is a follow up PR (2nd PR) to PR #1097 , introducing first and basic implementation of Wallet reissue API and CLI cmd.
- Reissue an output DBC from a Wallet (using [sn_dbc::TransactionBuilder](https://github.com/maidsafe/sn_dbc/blob/d275810f33376acc34cf7fd3f8045f585b264791/src/builder.rs#L36)) for a provided amount
- Reissue the change DBC which is automatically stored in the source Wallet the reissue was made from
- Spent DBCs are automatically soft-removed from the source Wallet (Multimap)
- Reissued DBCs are all bearer at this instance
The CLI `wallet reissue` and `wallet deposit` commands are currently compatible with the DBC's generated and printed out by the [mint-repl](https://github.com/maidsafe/sn_dbc#mint-repl-example) and [DBC …
=> feat(api): first and basic implementation of Wallet reissue API and related CLI cmds

sn_node/Cargo.toml
Currently smart-release doesn't support the `~` style of reference; the `^` style must be used. This
caused the last nightly run to fail at version bumping.
=> fix: use supported referencing style

.github/workflows/release.yml, Makefile, resources/scripts/bump_version.sh, resources/scripts/get_release_description.sh, resources/scripts/insert_changelog_entry.py, resources/scripts/output_versioning_info.sh, sn_api/Cargo.toml, sn_cli/Cargo.toml, sn_cli/src/operations/helpers.rs, sn_client/Cargo.toml, sn_cmd_test_utilities/src/lib.rs, sn_dysfunction/Cargo.toml, sn_interface/Cargo.toml, sn_node/Cargo.toml
- 3cf6d6c03 **chore: tidy references in cargo manifests**
All references are organised alphabetically, and random usage of long-form references are removed in
favour of the short-form version, unless the long-form style is justified, e.g., when lots of
features are being used.
- fabb6b8b4 **ci: incorporate sn_client and sn_node in release process**
The `sn_client` and `sn_node` crates had to be included for publishing in the release process.
There were a few other changes I made to support this:
* The title of the release, with all the crate names, was getting too large. I changed it to just
include the version numbers. The description of the release now includes the list of crates and
the version numbers they relate to.
* Stop passing the version numbers around for the changelog …
=> ci: incorporate sn_client and sn_node in release process

sn_node/src/node/api/tests/mod.rs
Makes sure that the `nonce_signature` is signed by the correct peer.
=> tests(resource_proof): test valid nonce signature

sn_node/src/bin/sn_node.rs
=> fix: use the config verbosity if no env var present

sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_interface/src/messaging/auth_kind.rs, sn_interface/src/messaging/mod.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/messaging/serialisation/wire_msg_header.rs, sn_node/src/node/api/dispatcher.rs, sn_node/src/node/api/tests/mod.rs, sn_node/src/node/core/bootstrap/join.rs, sn_node/src/node/core/comm/mod.rs, sn_node/src/node/core/messaging/handling/anti_entropy.rs, sn_node/src/node/core/messaging/sending/services.rs, sn_node/src/node/core/messaging/sending/system.rs, sn_node/src/node/messages/mod.rs
This feels more correct given that the kind is actually about the authority that
the message carries.
=> chore(messaging): rename MsgKind -> AuthKind

.github/workflows/benchmark_prs.yml
we were seeing fails when no related code was touched,
this should hopefully keep that noise from affecting the CI too badly
=> ci: increase alert threshold

sn_interface/src/messaging/serialisation/mod.rs, sn_interface/src/messaging/system/mod.rs, sn_interface/src/types/log_markers.rs, sn_node/src/node/core/messaging/handling/anti_entropy.rs, sn_node/src/node/core/messaging/handling/dkg.rs, sn_node/src/node/core/messaging/handling/membership.rs, sn_node/src/node/core/messaging/handling/mod.rs, sn_node/src/node/error.rs, sn_node/src/node/membership/mod.rs
=> Membership ae fixes

.github/workflows/sn_pr_tests.yml
Also use Cargo to install ripgrep, which is a cross-platform solution.
=> chore: use different retry count for certain runs

sn_api/src/app/register.rs, sn_client/src/api/cmds.rs, sn_client/src/api/register_apis.rs, sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_node/src/node/core/messaging/handling/mod.rs, sn_node/src/node/core/messaging/handling/service_msgs.rs
Resolve PR #836.
Note that commands creating a Register don't fail as the network doesn't return any type of errors (by design) but only an ACK that the message was delivered to the section. However, we can perform checks locally on CRDT operations, like in the case of a Register operation, so any permissions issue is detected locally on the client side before the operation is sent/broadcasted to the network. This PR, does simply that, it makes sure the permissions are checked locally when building the Register CRDT operation.
=> fix(client): check Register permissions on ops locally to prevent failures when broadcasted to the network

.github/workflows/daily_droplet_run.yml, .github/workflows/release.yml, Makefile, sn_node/src/node/cfg/config_handler.rs
A few changes for things spotted in the last nightly/release run:
* Use `usize::MAX` for max capacity on ARM/ARMv7. A change to use a max capacity of 10GB wouldn't
compile on these 32-bit architectures, since the value exceeded 2^32.
* Exit on error if ARM builds fail. Even though compilation failed, the release process didn't
report an error for the failure. The outer process must be disabling the `set -e` effect.
* During the publishing process, instruct `sn_node` to wait on `sn_interface` rather than
`sn_dysfunction`, since `sn_interface` is published immediately before `sn_node`. The last release
failed when it tried to publish `sn_node` because `sn_interface` wasn't available yet.
* Use 30 nodes in the testnet for the nightly run.
* Run the CLI test suite in parallel with the API and …
=> ci: nightly improvements and fix release process issues

sn_dysfunction/src/detection.rs
Increases 10x the amount of conn or knowledge issues. We've been voting
off nodes far too quickly, even on droplet testnets
=> fix(dysfunction): relax dysfunction for knowledge and conn issues

sn_node/src/node/core/messaging/handling/handover.rs, sn_node/src/node/core/messaging/handling/mod.rs, sn_node/src/node/error.rs
- Make sure incoming vote's auth'd SAPs are correctly signed by elders before we forward them to consensus.
=> Check incoming authed SAP in signed votes

sn_interface/src/types/log_markers.rs, sn_node/Cargo.toml, sn_node/src/node/api/dispatcher.rs, sn_node/src/node/api/mod.rs, sn_node/src/node/core/comm/back_pressure/mod.rs, sn_node/src/node/core/comm/mod.rs, sn_node/src/node/core/dbc_spentbook.rs, sn_node/src/node/core/messaging/handling/handover.rs, sn_node/src/node/core/messaging/handling/mod.rs
Previously we had backpressure running in response to every single message that came in. 
This was somehow disrupting section formation and DKG. Moving it to an optional feature helped stabilise the base test cases in `main` w/ the membership changes.
Here, I look to reenable backpressure as a default feature. 
I've moved it away from being triggered on _every_ incoming message, to be a periodic check on a loop over an interval.
It also now _only_ fires back pressure messages to the same section. 
(As things stand, intersection comms is currently limited to AE messages flows which should not overwhelm our nodes if backpressure within the section - which is where most messages arise - is working properly).
(We _could_ fire backpressure to every connected node peer eg, but we don't know if …
=> Back pressure debug

sn_node/src/bin/sn_node.rs, sn_node/src/node/api/dispatcher.rs, sn_node/src/node/core/comm/mod.rs, sn_node/src/node/core/messaging/handling/service_msgs.rs
The if statement could hold the lock on each until it's done. here we get
our bool statements before the if, meaning no locks should be held.
This may hopefully prevent deadlock on PeerSessions read/write
=> chore: refactor CleanUpPeerLinks

sn_node/src/node/core/comm/mod.rs
It's still not clear if this is where we may be deadlocking. But moving to hold the lock over a shorter duration certainly seems sensible
=> chore(node): dont hold comms session lock over session cleanup

resources/scripts/bump_version.sh
Previously we were checking for a particular piece of text in the smart-release output, but it turns
out there can also be other text that indicates that a crate will have changes. Not sure how it was
missed until this point.
=> ci: additional check in version bumping process

sn_interface/src/network_knowledge/errors.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/node_state.rs, sn_node/src/node/core/mod.rs, sn_node/src/node/membership/mod.rs
This is part of the work to move membership history to NetworkKnowledge. By moving NodeState validations to the NodeState struct, we have less code in Membership and so, less code to move to NetworkKnowledge.
=> refactor(node_state): move NodeState validations to NodeState struct

.github/workflows/sn_pr_tests.yml, sn_node/src/bin/sn_node.rs, sn_node/src/node/api/mod.rs, sn_node/src/node/core/comm/mod.rs
Add more logs to aid debugging
=> chore: explicitly drop Node on join retry

.github/workflows/release.yml
In the last release run, the release failed because it attempted to publish sn_cli, which did not
have its version bumped.
The reason was because the test for doing a publish is to check the commit message contains the
crate name, and it just so happens that "sn_cli" is contained in "sn_client". In the case of this
release, sn_client had changes, but sn_cli didn't, so the attempted publish of sn_cli failed.
=> ci: prevent sn_cli being published incorrectly

sn_cli/src/subcommands/wallet.rs, sn_cli/tests/cli_wallet.rs
It's possible for files to be written out with some whitespace or newline characters. These need to be stripped away or the DBC data won't be interpreted correctly.
=> fix: strip whitespace from dbc data file

sn_node/src/bin/sn_node.rs, sn_node/src/node/error.rs, testnet/Cargo.toml, testnet/bin.rs
Previously an error from the node was not triggering the restart of the
node instance. (eg, ChurnJoinMiss).
Here, the node bin start process has been tweaked. Kepeing all
node processes within the sn_node spawned thread. But, each 'node'
with its own runtime, to aid in shutting down any background processes
between restarts.
=> fix: Node init and restart on error

sn_cli/src/operations/config.rs, sn_client/src/connections/messaging.rs, sn_interface/src/lib.rs, sn_interface/src/network_knowledge/prefix_map/mod.rs
=> fix(sn_client): sending cmds to a supermajority of Elders

Cargo.lock, sn_api/Cargo.toml, sn_cli/Cargo.toml, sn_client/Cargo.toml, sn_interface/Cargo.toml, sn_node/Cargo.toml
There were various other crates that had to be upgraded in this process:
* secured_linked_list to v0.5.2 because it was also upgraded to reference v6.0.0 of blsttc
* bls_dkg to v0.10.3 because it was also upgraded to reference v6.0.0 of blsttc
* sn_consensus to v2.1.1 because it was also upgraded to reference v6.0.0 of blsttc
* sn_dbc to v4.0.0 because it was also upgraded to reference v6.0.0 of blsttc
=> chore: upgrade blsttc to 6.0.0

sn_interface/src/network_knowledge/mod.rs, sn_node/Cargo.toml, sn_node/examples/routing_minimal.rs, sn_node/examples/routing_stress.rs, sn_node/src/bin/sn_node.rs, sn_node/src/dbs/chunk_store.rs, sn_node/src/node/api/dispatcher/background_tasks.rs, sn_node/src/node/api/dispatcher/mod.rs, sn_node/src/node/api/mod.rs, sn_node/src/node/api/tests/mod.rs, sn_node/src/node/cfg/keypair_storage.rs, sn_node/src/node/core/bootstrap/join.rs, sn_node/src/node/core/comm/back_pressure/load_monitoring.rs, sn_node/src/node/core/comm/listener.rs, sn_node/src/node/core/comm/mod.rs, sn_node/src/node/core/comm/peer_session.rs, sn_node/src/node/core/data/storage/registers.rs, sn_node/src/node/core/messaging/handling/anti_entropy.rs, sn_node/src/node/core/mod.rs, sn_node/src/node/logging/mod.rs, sn_node/src/node/tests/bootstrap.rs, sn_node/src/node/tests/drop.rs, sn_node/src/node/tests/messages.rs
=> Even slimmer single thread start pr

sn_client/examples/network_split.rs, sn_client/src/connections/messaging.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/messaging/serialisation/wire_msg_header.rs, sn_node/examples/routing_stress.rs, sn_node/src/bin/sn_node.rs, sn_node/src/node/api/cmds.rs, sn_node/src/node/api/dispatcher.rs, sn_node/src/node/core/api.rs, sn_node/src/node/core/bootstrap/join.rs, sn_node/src/node/core/comm/link.rs, sn_node/src/node/core/comm/listener.rs, sn_node/src/node/core/comm/peer_session.rs, sn_node/src/node/core/data/records/mod.rs, sn_node/src/node/core/messaging/handling/anti_entropy.rs, sn_node/src/node/core/messaging/handling/mod.rs, sn_node/src/node/core/messaging/handling/service_msgs.rs, sn_node/src/node/core/messaging/sending/dkg_start.rs, sn_node/src/node/core/messaging/sending/proposal.rs, sn_node/src/node/core/messaging/sending/services.rs, sn_node/src/node/core/messaging/sending/system.rs, sn_node/src/node/dkg/session.rs, sn_node/src/node/messages/mod.rs
- Complete `msg_kind` => `auth_kind` renaming.
- Fix broken `routing_stress` startup.
- Clarify context of `HandleTimeout` and `ScheduleTimeout` by
inserting `Dkg`.
- Tweak `network_split` example.
- Set various things, such as payload debug, under `test-utils` flag.
- Fix comments/logs: the opposite group of `full` adults are
`non-full`, not `empty`.
=> chore(misc): misc cleanup and fixes

Cargo.lock, sn_api/src/app/keys.rs, sn_api/src/app/wallet.rs, sn_api/src/errors.rs, sn_cli/src/cli.rs, sn_cli/src/operations/auth_and_connect.rs, sn_cli/src/operations/config.rs, sn_cli/src/subcommands/dog.rs, sn_cli/src/subcommands/keys.rs, sn_cli/src/subcommands/wallet.rs, sn_cli/tests/cli_cat.rs, sn_cli/tests/cli_dog.rs, sn_cli/tests/cli_keys.rs, sn_cli/tests/cli_wallet.rs, sn_cmd_test_utilities/src/lib.rs, sn_interface/src/types/errors.rs, sn_interface/src/types/keys/keypair.rs
- 554c9d688 **chore: upgrade sn_dbc to 3.3.0**
This version contains an update for converting an owned DBC to a bearer DBC.
- 23802f8e3 **feat!: extend wallet_deposit for owned dbcs**
BREAKING CHANGE: the `wallet_deposit` function now provides an `Option<bls::SecretKey>` argument for
providing a secret key when depositing an owned DBC.
The owned DBC is changed to a bearer by providing the secret key, and the resulting DBC is then
stored in the wallet. This means you don't need to provide the secret key at reissue time, where
there is an issue with mapping input DBCs to secret keys.
A couple of misc changes:
* Extra test cases were added here to cover assigning the name to the deposit.
* More instances of "Wallet" were converted to "wallet", because "wallet" is not a proper noun.
As an …
=> feat: deposit owned dbcs

sn_api/src/app/keys.rs, sn_cli/src/main.rs, sn_cli/src/subcommands/nrs.rs, sn_client/src/api/file_apis.rs, sn_dysfunction/src/detection.rs, sn_dysfunction/src/lib.rs, sn_interface/src/network_knowledge/utils/mod.rs, sn_interface/src/types/connections/link.rs, sn_node/src/bin/sn_node.rs, sn_node/src/comm/link.rs, sn_node/src/node/api/flow_ctrl/cmd_ctrl.rs, sn_node/src/node/core/data/records/mod.rs, sn_node/src/node/core/data/storage/registers.rs, sn_node/src/node/core/messaging/handling/update_section.rs
seems like two new lints came in that affects us:
1. let bindings for unit return values.
2. favoring `write!(str, ..)` over `str.push_str(&format!(..)`
=> Address lints from clippy update

sn_api/src/app/wallet.rs, sn_cli/src/subcommands/wallet.rs, sn_node/src/node/api/mod.rs, sn_node/src/node/api/tests/mod.rs, sn_node/src/node/core/api.rs, sn_node/src/node/core/messaging/handling/anti_entropy.rs, sn_node/src/node/core/mod.rs, sn_node/src/node/error.rs, sn_node/src/node/mod.rs
This is a follow up PR (5th PR) to PR https://github.com/maidsafe/safe_network/pull/1235, PR https://github.com/maidsafe/safe_network/pull/1097, PR https://github.com/maidsafe/safe_network/pull/1105, and PR https://github.com/maidsafe/safe_network/pull/1143.
The Genesis DBC is generated and owned by the genesis PK of the network's section chain, i.e. the very first section key in the chain. 
The first node mints the genesis DBC (as a bearer DBC) and stores it in a file named `genesis_dbc`, located at it's configured root dir, e.g. when using the `sn_launch_tool` the genesis DBC will be stored at `~/.safe/node/local-test-network/sn-node-genesis/genesis_dbc`.
In this implementation the amount owned by the Genesis DBC is set to `4,525,524,120,000,000,000` individual units.
As per current …
=> feat(node): generate the genesis DBC when launching first node

rustfmt.toml, sn_client/examples/churn.rs, sn_client/examples/network_split.rs, sn_dysfunction/src/detection.rs, sn_dysfunction/src/lib.rs, sn_interface/src/lib.rs, sn_node/src/bin/sn_node.rs, sn_node/src/node/core/relocation.rs, sn_node/src/node/membership/mod.rs, testnet/bin.rs
No need for rustfmt to check/replace this, as the compiler will already
warn for this. Deprecated since 1.39.
Removing the option seems to trigger a couple of formatting changes that
rustfmt did not seem to pick on before.
=> chore(rustfmt): `try!` macro is deprecated

sn_cli/src/operations/config.rs, sn_client/src/api/file_apis.rs, sn_client/src/connections/listeners.rs, sn_interface/src/messaging/msg_id.rs, sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/api/flow_ctrl/mod.rs, sn_node/src/node/core/data/records/mod.rs, sn_node/src/node/core/messaging/anti_entropy.rs, sn_node/src/node/core/messaging/system_msgs.rs, sn_node/src/node/core/messaging/update_section.rs, sn_node/src/node/mod.rs
This PR contains the work to passing the churn test.
There are mainly two fixes:
1, Only trigger data reorganization when there is membership update.
Previously, data reorganzation get undertaken whenever there is
incoming message. Which result in a looping of messaging among
nodes.
2, Only broadcast result when the QueryResponse is not an error.
Previously, this will cause the client thinking the whole query
is failed whenever an error response received.
=> fix: passing the churn test

.github/workflows/sn_pr_tests.yml, resources/scripts/wait_for_nodes_to_join.sh, sn_node/src/bin/sn_node.rs
=> chore: increase wait on ci & decrease delay before node retry

sn_node/src/node/membership/mod.rs, sn_node/src/node/messaging/membership.rs
Previously we were re-processing each membership decision on every new vote that comes in.
This was a hack to simplify the initial membership integration, but it is causing nodes to do a lot of extra work.
This PR massages our decision processing logic so that we only process a decision once when it first happens.
=> fix(membership): only process each membership decision once

sn_client/src/api/mod.rs, sn_client/src/connections/messaging.rs, sn_client/src/connections/mod.rs
Also remove `Session::genesis_key` as it's unused. Can be obtained from `NetworkPrefixMap` if required.
=> chore(client): remove extra bootstrap step

.github/workflows/daily_droplet_run.yml
The sn_testnet_tool has been updated to retrieve the genesis DBC and upload it to S3.
The nightly run is now being updated to pull the DBC from S3 and then pointing to it using the environment variable that will be read by the testing process.
=> ci: copy and set path to genesis dbc

sn_node/src/bin/sn_node.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/messaging/system_msgs.rs, sn_node/src/node/node_api/cmds.rs, sn_node/src/node/node_api/dispatcher.rs, sn_node/src/node/node_api/flow_ctrl/mod.rs, sn_node/src/node/node_api/tests/mod.rs
Deserializes and validates at lower prio, to cut off an overload attack angle.
After validity of msg has been established, the msg is dealt with according to its type prio.
=> feat(msgs): validate w low prio before handling

sn_dysfunction/src/detection.rs
We've seen some CI nodes being booted due to knowledge issues, so relaxing
this should help there'
=> chore(dsyfunction): relax knowledge penalty.

Cargo.lock, sn_api/Cargo.toml, sn_api/src/app/nrs/mod.rs, sn_api/src/app/test_helpers.rs, sn_api/src/app/wallet.rs, sn_cli/Cargo.toml, sn_client/Cargo.toml, sn_client/src/api/mod.rs, sn_client/src/connections/mod.rs, sn_interface/Cargo.toml, sn_node/Cargo.toml
Refactoring sn_api wallet related tests so they have some setup stage where:
- the genesis DBC from the first node in a testnet is read and kept in memory.
- a set of (bearer) DBCs is reissued up front from genesis DBC, with random balances, to allow all tests to use different DBCs that were not spent by other tests.
- utility function to keep track of which DBCs were already used by some tests and assign unused ones.
=> refactor(sn_api): setup step for tests to reissue a set of DBCs from genesis only once

Cargo.lock, log_cmds_inspector/Cargo.toml, sn_client/Cargo.toml, sn_interface/Cargo.toml, testnet/Cargo.toml
=> chore(dependencies): remove unused console-subscriber

sn_node/src/node/messaging/proposal.rs, sn_node/src/node/node_api/cmds.rs, sn_node/src/node/node_api/dispatcher.rs, sn_node/src/node/node_api/tests/mod.rs
`HandleNewEldersAgreement` variant of `Cmd` had an unnecessary wrapper
of `Proposal` around the actual object being conveyed.
=> refactor: remove one layer of indirection

sn_node/src/comm/mod.rs, sn_node/src/node/api.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/node_api/cmds.rs, sn_node/src/node/node_api/dispatcher.rs
This is not needed or really utilised in any real way.
We can just use SendMsg cmds
=> chore: remove SendMsgDeliveryGroup Cmd

Cargo.lock, sn_node/Cargo.toml, sn_node/README.md, sn_node/src/bin/sn_node/log/mod.rs, sn_node/src/bin/sn_node/main.rs
OTLP is a protocol that logs tracing spans to an endpoint. This OpenTelemetry Protocol is supported by quite some vendors that can process these logs.
At the moment, the OTLP logging layer for `tracing` seems to require it to be initialized within a Tokio runtime, which is why the node was refactored to start a main runtime that also instantiates the logging. This is because logging is integral to the startup and must be done early, so the runtime it is instantiated in also needs to be in or close to `main` in the node binary.
=> sn_node OTLP support

sn_client/Cargo.toml, sn_client/src/api/cmds.rs, sn_client/src/api/queries.rs, sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_interface/Cargo.toml, sn_interface/src/messaging/data/mod.rs, sn_interface/src/messaging/mod.rs, sn_interface/src/messaging/msg_type.rs, sn_interface/src/messaging/serialisation/mod.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/messaging/serialisation/wire_msg_header.rs, sn_interface/src/messaging/system/mod.rs, sn_node/Cargo.toml, sn_node/src/node/data/records/mod.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/messaging/system_msgs.rs, sn_node/src/node/messaging/update_section.rs, testnet/Cargo.toml, testnet/bin.rs
Implements a feature to trace a message's flow through the network. `WireMsgHeader` piggybacks a list to which entities(Clients, Elders, Adults) attach their identities(PublicKey) wherever they process the message.
This is currently implemented for Client's queries, commands, and commandACKs(all of which fall under `ServiceMsg`). This will be extended to support inter-node messages(`SystemMsg`) in the near future.
Build and run with `--features=traceroute` to log traceroutes.
=> feat(traceroute): trace a message's flow in the network

Cargo.lock, sn_api/Cargo.toml, sn_cli/Cargo.toml, sn_client/Cargo.toml, sn_interface/Cargo.toml, sn_node/Cargo.toml
This version has a more helpful error message for the shares interpolation problem.
=> chore: upgrade blsttc to 7.0.0

sn_client/src/connections/messaging.rs, sn_interface/src/messaging/system/join.rs, sn_interface/src/messaging/system/node_state.rs, sn_interface/src/network_knowledge/errors.rs, sn_interface/src/network_knowledge/node_state.rs, sn_interface/src/network_knowledge/prefix_map/mod.rs, sn_interface/src/network_knowledge/section_authority_provider.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/cfg/config_handler.rs, sn_node/src/node/delivery_group.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/membership/mod.rs, sn_node/src/node/messaging/agreement.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/join.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/relocation.rs, sn_node/src/node/proposal.rs, sn_node/src/node/relocation.rs
This PR changes our Join approval flow to include the membership decision that approved the node to join the section.
Also we remove support for rejoins since that turns out to be unsound
=> feat(membership): join approval has membership decision + remove support for rejoins

sn_node/src/node/data/storage/mod.rs, sn_node/src/node/data/storage/registers.rs
Gets/Reads should not mutate, and nothing here did require mut access,
so it could be removed.
=> fix(datastorage): remove unused get mut access

sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/messaging/join.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/system_msgs.rs
The method can be called directly instead of passing known keys in the
cmds.
=> refactor: expose known keys on network knowledge

sn_client/src/connections/messaging.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/messaging/serialisation/wire_msg_header.rs, sn_node/src/comm/listener.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/messages.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/messaging/system_msgs.rs
The type is named Kind but the semantics of it is Auth.
Often we mindlessly name things after the type names instead of what they
represent in the domain.
BREAKING CHANGE: fields of public msg renamed
=> chore(naming): reflect the semantics not the type

sn_node/benches/data_storage.rs
=> fix: improve the accuracy of data_storage bench tests

.github/workflows/daily_droplet_run.yml
Previously the file was being placed under the profile directory, but the test process was
complaining it couldn't find the file. The custom action for running Nextest should be running on
the same machine and user, meaning it really shouldn't be a problem to put the file there, but
nonetheless it apparently couldn't be found. Thus, I'm going to try a system-wide location.
Also changed the mechanism for setting the variable to be defined on the invocation of the Nextest
action.
=> ci: use system-wide location for genesis dbc

sn_client/Cargo.toml, sn_node/Cargo.toml
This reverts commit 175d1b909dff8c6729ac7f156ce1d0d22be8cc12.
=> Revert "feat: make traceroute default for now"

sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/mod.rs
This adds a new Cmd for tracking dysfunction, so we can pull the
write locks out of longer running Cmd processes
=> chore: remove the write lock on node while validating msgs

.github/workflows/daily_droplet_run.yml, sn_node/src/comm/mod.rs, sn_node/src/node/flow_ctrl/dispatcher.rs
Previously we've had a send to client and a send ot nodes, the latter
which would only send to a subset (with the delivery group setting), and
reported errors.
We've stripped out the delivery group stuff already as unnecessary. So here
we just have one function to send from nodes, any errors are handled
appropriately if the recipient is in our section, otherwise ignored.
=> chore(node): simplify the send funcitonality

sn_node/src/node/flow_ctrl/mod.rs
=> chore: dont send health checks as an adult

testnet/bin.rs
This not only removes the ci join issues, but also the fairly common other test errors (not enough spendproof shares, failed to obtain response, not enough chunks etc - seems this could be due to ghost nodes).
With this we do not need to override our ci all the time due to these tests failing.
Also it removes the risk of hiding new bugs introduced, behind what we assume were those join related errors.
***
Interval could probably be lowered some. But that'd optimally be done while working on fixing the underlying problem.
Goal for that would be to not have any join-rate that is capable of throwing off the network like that.
=> chore(ci): increase node startup interval to 5s

README.md
The `safe_network` crate is not published anymore, thus a few references
to this crate are removed.
=> Tweak README to lose `safe_network` crate reference

.github/workflows/benchmark_prs.yml, .github/workflows/sn_pr_tests.yml
Stops the old CI run on force push/ new commit.
Eg: any push to `my_branch` will create group with name,
"PR Check-my_branch" and subsequent updates to the branch
will stop any running CI for the same group.
=> chore(CI): cancel old CI run on new commit

sn_interface/src/messaging/system/join.rs, sn_interface/src/messaging/system/mod.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/join.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/resource_proof.rs, sn_node/src/node/messaging/system_msgs.rs
Remove optional field and model the actual requests separately, instead of combining two types of requests into one.
=> Refactor joinrequest

sn_interface/src/types/cache/mod.rs, sn_interface/src/types/log_markers.rs, sn_node/examples/routing_stress.rs, sn_node/src/node/data/records/mod.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/messaging/service_msgs.rs
This creates the `AddToPendingQieries` cmd, which adds asyncly to the
list.
Also cleans up the `read_data_from_adults` fn a bit.
=> Remove node write lock on query

sn_node/src/node/flow_ctrl/cmd_ctrl.rs
Now actually adds the parent id.
It tried to add parent id of parent, which would always be None.
=> Fix cmd ctrl parent

sn_dysfunction/src/detection.rs, sn_dysfunction/src/error.rs, sn_dysfunction/src/lib.rs, sn_node/src/comm/mod.rs, sn_node/src/node/api.rs, sn_node/src/node/connectivity.rs, sn_node/src/node/data/records/mod.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/messaging/agreement.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/mod.rs
These were remaining in places where there was no path for None or
Error.
Cleaning these up removes accidental complexity.
=> chore: cleanup unnecessary options and results

sn_interface/src/messaging/data/cmd.rs, sn_interface/src/messaging/data/errors.rs, sn_interface/src/messaging/data/mod.rs, sn_interface/src/types/address/mod.rs, sn_node/benches/data_storage.rs, sn_node/src/dbs/errors.rs, sn_node/src/dbs/file_store.rs, sn_node/src/node/data/storage/chunks.rs, sn_node/src/node/data/storage/mod.rs, sn_node/src/node/data/storage/registers.rs, sn_node/src/node/error.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/system_msgs.rs, sn_node/src/node/messaging/update_section.rs
The type including `SafeKey` had been incorrectly used (since it is not
a network side concept), which caused a lot of `Result` return values
bloating the upstream call tree unnecessarily.
=> fix(file_store): use correct data address type

sn_cli/src/operations/config.rs, sn_cli/src/subcommands/wallet.rs, sn_cli/tests/cli_wallet.rs
Allows to pass a file path to write the output DBC when reissuing with `wallet reissue` CLI cmd. If there is a problem writing to the file the CLI falls back to print the DBC data out. This arg can be extended to also support a wallet xorurl, so the user can reissue and get the output DBC either written to a file, or automatically deposited to another wallet the user owns.
This PR also renames the `--public-key` argument of `wallet reissue` command to `--to` as agreed in the review herein.
Example outputs:
```
$ safe wallet reissue 3.5 --save ./reissued_dbc.txt --from safe://hyryynywwgpr4yofnhpsm8kkcskjmtu6bq8m8834j88qia9djdzxfhy7mdhb6o
DBC content written at './reissued_dbc.txt'.
Reissued DBC with 3.5 safecoins.
This is a bearer DBC that can be spent by anyone.
```
```
$ safe wallet …
```
=> feat(cli): wallet CLI cmd to allow storing output DBC to a file upon reissuing it

Cargo.lock, sn_cli/Cargo.toml, sn_cli/src/operations/config.rs
Fixes the write corruption when running CLI tests using multiple threads.
=> chore(cli): make writes atomic

sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/relocation.rs
We previously allowed any length vec, while we only based it on
signatures. Therefore, we could restrict it to the signature contents
boundary.
=> feat(churnid): make the content explicit

sn_client/src/connections/messaging.rs, sn_interface/src/messaging/mod.rs, sn_interface/src/messaging/serialisation/mod.rs, sn_node/src/node/bootstrap/relocate.rs, sn_node/src/node/data/records/mod.rs, sn_node/src/node/dkg/session.rs, sn_node/src/node/dkg/voter.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/messaging/system_msgs.rs, sn_node/src/node/mod.rs, sn_node/src/node/node_test_api.rs
- Removes some boilerplate, using fn of `Cmd` to instantiate a send cmd.
- Housekeeping, continuing to minimize bloat of usings, by colocating
them.
- Housekeeping, continuing keeping positions of usings in a file
according to a system, from closest (self) on top, down to furthest
away (3rd part).
=> chore(style): organise usings, cleanup

.github/workflows/daily_droplet_run.yml
For a failed run, before the testnet is killed, the node logs are retrieved and uploaded to S3.
Along with the logs, the prefix map, the genesis key and the genesis DBC will also be uploaded.
This is all to facilitate debugging test failures.
=> ci(nightly): upload logs for failed run

sn_client/src/connections/listeners.rs, sn_interface/src/messaging/system/mod.rs, sn_interface/src/network_knowledge/mod.rs, sn_node/examples/routing_minimal.rs, sn_node/src/bin/sn_node/main.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/event.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/agreement.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/system_msgs.rs, sn_node/src/node/mod.rs
This reduces the `SystemMsg::AntiEntopy{Update|Retry|Redirect}` msgs to a single `SystemMsg::AntiEntropy {.. kind }` msg to allow for de-duplication of logic.
=> refactor(anti-entropy): reduce AE msgs to one msg with a kind field

Cargo.lock, sn_api/src/app/helpers.rs, sn_api/src/app/mod.rs, sn_cli/Cargo.toml, sn_cli/src/cli.rs, sn_cli/src/operations/config.rs, sn_cli/src/subcommands/wallet.rs, sn_client/Cargo.toml, sn_client/src/api/mod.rs, sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_client/src/connections/mod.rs, sn_client/src/errors.rs, sn_client/src/lib.rs, sn_interface/Cargo.toml, sn_interface/src/network_knowledge/utils/mod.rs, sn_node/src/node/cfg/config_handler.rs, sn_node/src/node/mod.rs, sn_node/src/node/node_starter.rs, testnet/Cargo.toml, testnet/bin.rs
This depends on https://github.com/maidsafe/sn_launch_tool/pull/119
- Nodes don't share a file for their own cache of the `PrefixMap`, they keep their own file stored at the node's root storage dir named `prefix_map`.
- The `sn_node` binary now requires a file path to be provided with `--network-contacts-file` argument where to read the network contacts from, unless it's meant to be the first node on the network.
=> refactor(node): nodes to cache their own individual prefix map file on disk

Cargo.lock, sn_api/Cargo.toml, sn_cli/Cargo.toml, sn_cli/src/operations/config.rs, sn_client/Cargo.toml, sn_dysfunction/Cargo.toml, sn_interface/Cargo.toml, sn_interface/src/network_knowledge/utils/mod.rs, sn_node/Cargo.toml
Depends on https://github.com/maidsafe/bls_dkg/pull/134 and https://github.com/maidsafe/self_encryption/pull/356 
- serialize `NetworkPrefixMap` into JSON
- Also fixes the case where we will loose the network pointed by `default` prefix map if the original file is absent.
=> cli: serialize NetworkPrefixMap into JSON

Cargo.lock, sn_cli/Cargo.toml, sn_cli/src/operations/node.rs, sn_cli/src/subcommands/node.rs, sn_client/Cargo.toml, sn_client/src/api/spentbook_apis.rs, testnet/Cargo.toml
- Since the sn_lauch_tool now copies the genesis node's prefix map file to `~/.safe/prefix_maps/default` (PR #1447), have the CLI to back it up using genesis key if not found after running a local testnet, i.e. copying the default prefix map to `~/.safe/prefix_maps/<genesis PK>`, before inserting the testnet to the CLI networks list.
- Fix CLI to convert nodes joining `interval` to millis before passing it to launch-tool.
- Also pass the default prefix map file path as the network contacts file path to CLI `node join` cmd.
=> fix(cli): backing up default prefix map file with genesis key in filename if not found

sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/prefix_map/mod.rs, sn_node/src/node/api.rs, sn_node/src/node/messaging/agreement.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/join.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/system_msgs.rs, sn_node/src/node/mod.rs, sn_node/src/node/node_test_api.rs
- Removes `NetworkKnowledge::chain` field as it can be obtained from `NetworkPrefixMap::sections_dag`
=> refactor(network_knowledge): remove NetworkKnowledge::chain

sn_node/src/node/error.rs, sn_node/src/node/messaging/join.rs
Previously we were occasionally seeing _large_ expected ages (246 eg),
here we add braces for clarity and hopefully prevent such calculatory oddness.
We also use membership to know the current section size instead of SAP which
may well be outdated.
=> fix(node): Add braces around expected age calc; use membership

sn_client/src/connections/messaging.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/types/connections/link.rs, sn_node/src/comm/mod.rs, sn_node/src/comm/peer_session.rs
Remove the Wiremssg priority as it's not actually used in sending from the nodes and can be quite CPU intensive. (accounting for 35% of CPU time here)
The Cmds themselves are prioritised in the node, so they should all get sent out in that order anyway
=> chore: remove wiremsg.priority as uneeded

sn_api/src/app/mod.rs, sn_cli/src/cli.rs, sn_cli/src/operations/config.rs, sn_cli/src/subcommands/node.rs, sn_client/src/api/client_builder.rs, sn_client/src/api/mod.rs, sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_client/src/connections/mod.rs, sn_client/src/lib.rs, sn_interface/src/network_knowledge/utils/mod.rs, sn_interface/src/types/errors.rs
- CLI to cache the up to date PrefixMap after all commands were executed and right before exiting.
- Refactoring sn_cli::Config to remove some redundant code.
=> refactor(client): sn_client to only read a default prefix map file, updates to be cached on disk by user

sn_interface/src/types/keys/secret_key.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_utils.rs, sn_node/src/node/messaging/anti_entropy.rs
The unit tests in the `flow_ctrl` module provide coverage for messaging handling in the node. To run
each test, a `Node` must constructed, and this involves a lot of tedious setup code.
A `network_utils` testing module is introduced to organise the code related to this setup and to
also provide a `TestNodeBuilder` to reduce duplication and hopefully make it easier to provide more
coverage for message handlers. The doc comments should hopefully make clear how the struct can be
used in various different testing contexts. I will also be looking to extend its functionality a bit
further when I come to unit testing the message handlers for the DBC spentbook commands.
There were a few tests whose setup was too complex to use the builder because they require too much
customisation and seem best …
=> refactor(tests): reorganise flow control unit tests

sn_node/src/bin/sn_node/main.rs
=> chore: print full error during node startup fail

sn_node/src/node/data/records/mod.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/mod.rs
We previously were merging all client requests for responses coming in, now we have adult indexes in queries, but were still doing this at nodes... now it's per adult.
=> chore(node): do not merge client requests to different adult indexes

sn_dysfunction/src/detection.rs, sn_node/src/bin/sn_node/main.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/cmd_ctrl.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/messaging/system_msgs.rs, sn_node/src/node/mod.rs, sn_node/src/node/node_starter.rs, sn_node/src/node/node_test_api.rs, testnet/bin.rs
Removes a lot of node cmd looping, and the `Clone` requirement on `CmdCtrl`, which will hopefully let us remove `RwLock` inside there in a follow up PR.
=> Simplified cmd ctrl refactor

sn_client/src/api/client_builder.rs
=> fix: reduce client qp2p default idle timeout

sn_client/src/api/mod.rs
No longer relevant, client conns can be cleaned up by nodes every X time.
So clients have to be resilient and retry (which they do). So this (long)
test can be dropped
=> tests(client): remove long lived client conn test

sn_interface/src/lib.rs
I've found our logging format to be very difficult to parse, IMO it's cluttered with a ton of unnecessary information making command line tools ineffective following what's going on.
The format proposed in this PR is:
[<timestamp> LEVEL module::path/span1/span2/span3] <msg>
e.g.
```
[2022-08-16T13:58:25.869826Z TRACE sn_node::node::messaging/validate_msg/apply_ae] Entropy check skipped for MsgId(d6aa..ccd7), handling message directly
```
The entire log is on one line making it simple to filter down a large collection of logs using the unix tools.
e.g. `rg -v` can be used to prune out messages we don't care for:
```
tail -f .../sn-node-*/*.log | rg -v 'qp2p|quinn|sn_node::comm'
```
This will filter out logs related to `qp2p`, `quinn`, `sn_node::comm`, you can add to this set interactively …
=> feat(logging): simplify log format to '<timestamp> [module] LEVEL <msg>'

sn_api/src/app/mod.rs, sn_api/src/app/wallet.rs, sn_cli/src/cli.rs, sn_client/src/api/mod.rs, sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_client/src/connections/mod.rs
The RwLock was mistakenly removed by me. This meant that network updates
to the section tree were not propagated back to the client's session.
=> fix: reintroduce Arc<RwLock> for section tree

.github/workflows/daily_droplet_run.yml
When the run fails, use a custom action to post a message to a Slack incoming webhook. For some
reason the content of the message to be sent is defined using environment variables, so you are
limited in terms of the amount of information that can be included in the notification. I checked a
few more actions and they all operated in this fashion. With that in mind, the best thing I thought
to do was for the failure to have a direct link to the run, so we can get people to the logs as
quickly as possible.
Also made a little change to output the direct URL of the server logs that get uploaded.
=> ci(nightly): slack notifications for nightly run

Cargo.lock, sn_interface/Cargo.toml
I'm building a tauri app using sn_api and came across a conflict in dependencies that prevented the tauri build from completing:
```text
error: failed to select a version for `tokio`.
... required by package `tauri v1.0.5`                                                                                                  
... which satisfies dependency `tauri = "^1.0.5"` of package `app v0.1.0 (/home/ian/code/tauri-app/src-tauri)`                          
versions that meet the requirements `^1.19` are: 1.20.1, 1.20.0, 1.19.2, 1.19.1, 1.19.0
all possible versions conflict with previously selected packages.
previously selected package `tokio v1.17.0`
... which satisfies dependency `tokio = "~1.17.0"` of package `sn_interface v0.9.0`
... which satisfies dependency `sn_interface = "^0.9.0"` of …
```
=> chore: update tokio

.github/workflows/benchmark_prs.yml, sn_cli/src/operations/config.rs, sn_cli/src/subcommands/node.rs
- Make a copy of the `default` network contact when switching networks and not during `sync()`
- Remove a redundant file read during `sync()`
- Include `sn_cli` bench during PR run. Takes ~11 minutes to complete including compilation
=> sn_cli: changes to Config::settings

sn_client/src/api/register_apis.rs, sn_interface/src/messaging/data/mod.rs, sn_interface/src/messaging/data/register.rs, sn_interface/src/types/register/mod.rs, sn_node/benches/data_storage.rs, sn_node/src/dbs/errors.rs, sn_node/src/node/data/storage/registers.rs, sn_node/src/node/messaging/service_msgs.rs
- Removing some unused `sn_node::dbs::Error` variants.
- Removing `RegisterExtend` cmd and related code as it's currently not used, plus we'll need to work on a CRDT-compliant implementation of such a feature when required.
- Removing unused `CreateRegister::Populated` msg type.
=> refactor(types)!: removing unused sn_node::dbs::Error variants and RegisterExtend cmd

sn_interface/src/messaging/system/mod.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/system_msgs.rs
Now we have periodic health checks and dysfunciton, this
check should not be needed, and can cause network strain
with the frequent DKG we have now
=> feat(node): remove ConnectivityCheck

.github/workflows/daily_droplet_run.yml, resources/scripts/cli_tests.sh
=> ci: dont change default QUERY_TIMEOUT on ci

sn_client/src/connections/messaging.rs, sn_interface/src/messaging/data/errors.rs, sn_interface/src/network_knowledge/section_authority_provider.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/types/keys/secret_key.rs, sn_node/src/node/api.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/data/records.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/dbc_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_utils.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/proposal.rs, sn_node/src/node/relocation.rs
- 50f3d94f3 **tests(messaging): unit tests for spentbook handler**
Provide unit test coverage for the `SpentbookCmd::Spent` message handler.
It's important to note that at this point, the failure cases only assert that no commands were
returned from the handler, because this is the way we deal with failures at the moment.
Unfortunately this means it's easy for there to be false positives because you can't check the error
type or message. I will look into changing this as a separate PR.
Most of the changes here are related to testing infrastructure:
* Support setting a threshold when a secret key set is generated for the section. For use with the
genesis DBC generation, the threshold had to be set to 0.
* Support adults in the test section. The spent message generates data to be replicated …
=> feat: return error to client on unknown section key

Cargo.lock, sn_cli/Cargo.toml, sn_cli/src/operations/config.rs, sn_cli/src/subcommands/node.rs
- `sn_cli` can fetch "Network Contacts" present on a remote server. To test this feature, `network_contact` files were uploaded to an actual server and the URLs were used inside the tests.
- So any changes made to the struct of the `SectionTree` can render the previous test files useless. Hence use a mock server instead of an actual one for the tests.
=> test(cli): use `httpmock` to test remote network contacts

sn_api/src/app/wallet.rs, sn_api/src/lib.rs, sn_cli/src/main.rs, sn_cli/src/operations/config.rs, sn_cli/src/subcommands/node.rs, sn_client/src/lib.rs, sn_client/src/testnet_grep/mod.rs, sn_dysfunction/src/detection.rs, sn_dysfunction/src/lib.rs, sn_interface/src/lib.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/network_knowledge/section_authority_provider.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_interface/src/types/keys/ed25519.rs, sn_interface/src/types/keys/signature.rs, sn_node/src/bin/sn_node/main.rs, sn_node/src/lib.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/node_starter.rs, sn_node/src/node/relocation.rs, sn_node/src/storage/mod.rs, sn_node/src/storage/registers.rs
sn_interface:
All usages were in testing code. They were either removed in favour of using the `?` operator or an
`ok_or_else` with an error message. The `allow` attribute was applied for a couple of cases where
the usage was in a `proptest!` macro. This was agreed to be preferable to using `except`.
sn_dysfunction:
All usages were in `proptest!` macros and therefore the `allow` attribute was applied.
sn_node:
A conversion from `sn_dbc::Error` to `sn_node::storage::Error` was added to remove an unwrap in
the bootstrapping process. The remainder were in test cases, with one `allow` added for use in a
`proptest!` macro.
sn_client:
A couple of usages were found in little pattern matching functions. They were changed to return an
IO error, which is the error type in the `Result`, the return …
=> chore: switch on clippy::unwrap_used as a warning

sn_client/src/connections/messaging.rs, sn_interface/src/lib.rs, sn_interface/src/messaging/data/mod.rs, sn_interface/src/network_knowledge/section_authority_provider.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_interface/src/types/cache/item.rs, sn_interface/src/types/connections/link.rs, sn_interface/src/types/errors.rs, sn_interface/src/types/keys/public_key.rs, sn_interface/src/types/keys/secret_key.rs, sn_node/src/comm/link.rs, sn_node/src/node/flow_ctrl/tests/mod.rs
Apply lints used in other crates, as far as they can easily be applied.
The `unused_results` lint has been left out, as that is too much
cleaning up to do, just like adding documentation to all the public
interfaces.
=> chore: sn_interface lints and fixes

resources/scripts/statemap-preprocess.sh, sn_node/Cargo.toml, sn_node/src/node/flow_ctrl/cmd_ctrl.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/mod.rs, sn_node/src/node/statemap.rs, testnet/Cargo.toml, testnet/bin.rs
usage:
0. install `statemap`
git clone git@github.com:TritonDataCenter/statemap.git
cd statemap
cargo install --path .
2. startup a network as usual
3. extract the states file from a log using:
./resources/scripts/statemap-preprocess.sh
4. run `statemap` on the generated `safe_states.out` file:
statemap -c 300000 safe_states.out > safe.svg
5. open `safe.svg` in a browser
issues with this approach:
- `statemap` wants all state entry timestamps to be monotonically increasing, my method of extracting states from logs can mess that up when you combine logs form multiple nodes and/or log rotation kicks in
- would be nicer if we have some state constants instead of using magic numbers throughout the code.
=> feat(statemaps): some minimal infrastructure for generating statemaps

Makefile, sn_node/src/comm/mod.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/cmd_ctrl.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/proposal.rs
- 6c6efb5c1 **feat: use err result to send errors back to client**
Previously the mechanism for handling errors in `handle_valid_service_msg` was to return an `Ok`
result with an empty list of commands, or if you wanted to send an error response back to the
client, to include a command in that `Ok` result.
A new `CmdProcessingClientRespondError` variant is added to `Error` to enable returning an `Err`
result when we want to return an error back to the client. When the command processing code
encounters this error variant, it will process the commands included in the error, which will be the
information to send back to the client.
The intention is also to return `Err` results from `handle_valid_service_msg` when any errors are
encountered, not just for the limited few we want to send back …
=> feat: use err result to send errors back to client

sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/flow_ctrl/cmd_ctrl.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/mod.rs
Adults were skipping AE probes before splits for some reason
Also included in this PR:
- move AE probe building to network knowledge
- remove the unused `stopped` state from cmd ctrl which removes some error cases for us.
=> Ensure adults are probing for AE updates before first split

sn_client/benches/serialize.rs
use Bytes.len, not the size of the Bytes struct!
=> chore: change throughput measure

sn_interface/src/messaging/data/errors.rs, sn_interface/src/types/mod.rs, sn_node/src/node/error.rs, sn_node/src/node/messaging/system_msgs.rs, sn_node/src/storage/chunks.rs, sn_node/src/storage/errors.rs, sn_node/src/storage/mod.rs, sn_node/src/storage/register_store.rs, sn_node/src/storage/registers.rs
- Changing some internal store APIs to avoid cloning some objects.
- Removing some unused storage Error types, while adding more context information to others.
- Allowing the Register storage to store register edit cmds even when the creation cmd is not found in the local replica/store yet.
- Skip Spentbook Register creation if it already exists.
- Unit tests for register storage key internal helper functions.
=> refactor(node): optimise the way we apply and save replicated Register cmds on local storage

sn_node/src/node/data/records.rs
Remove a potential source of errors. We _always_ send on queries now. Regardless if the client already exists in `pending_queries`. There's a reason they're re-requesting.
When we have cache implemented at elders we can short circuit this there... but otherwise we should treat each request equally.
=> fix: always resend query to adults

sn_api/src/app/wallet.rs, sn_interface/src/messaging/data/errors.rs, sn_interface/src/messaging/data/mod.rs, sn_node/src/comm/mod.rs, sn_node/src/node/data/records.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/cmd_ctrl.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/proposal.rs, sn_node/src/storage/chunks.rs, sn_node/src/storage/errors.rs, sn_node/src/storage/mod.rs, sn_node/src/storage/registers.rs
- Removing several unused sn_node::Error types.
- Adapting sn_api wallet and sn_node spentbook unit tests for new error msgs/cmds.
- Removing some unused sn_interface Error types.
- Minor refactor to how we convert sn_node modules Error types to sn_interface::Error types.
=> feat(node): report any error occurred when handling a service msg back to the client

.github/workflows/sn_pr_tests.yml, README.md, resources/scripts/statemap-preprocess.sh, sn_client/examples/churn.rs, sn_node/Cargo.toml
Statemaps are now generated for each integration test and uploaded as artifacts after the workflow completes.
Sample run, see `statemap_*.svg` artifacts on: https://github.com/maidsafe/safe_network/actions/runs/3011677860
=> feat(statemap): run statemap in CI

sn_interface/src/messaging/data/mod.rs, sn_interface/src/messaging/system/mod.rs, sn_node/examples/routing_stress.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/messaging/system_msgs.rs
Also:
- Avoiding unnecessary operation id generation upon query response at elder since it's expensive (serialisation involved)
- Removing unused `SystemMsg::NodeMsgError` msg type
=> feat(node): return error to client when it cannot accept a query

.gitignore, resources/scripts/statemap-preprocess.sh
This allows us to generate statemaps when we don't have a node named `genesis`
=> fix(statemap): allow generating statemaps from non genesis nodes

.github/workflows/README.md, .github/workflows/arm_tests.yml, .github/workflows/benchmark_prs.yml, .github/workflows/benchmarks_pages.yml, .github/workflows/sn_client_tests_against_do_testnet.yml, .github/workflows/sn_pr_tests.yml
=> Remove rustflags

sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/messaging/agreement.rs, sn_node/src/node/messaging/anti_entropy.rs
By moving these checks into `sn_node`, we no longer need a `SectionKeysProvider` to update `NetworkKnowledge`.
This makes it easier to use network_knowledge from outside of `Node`. For example, in bootstrapping, we can create a `NetworkKnowledge` instance and bring it up to date before we construct a full `Node` instance.
=> Move "will-be-elder" check from `network_knowledge` to `sn_node`

sn_api/src/app/nrs/mod.rs, sn_client/src/api/cmds.rs, sn_client/src/api/file_apis.rs, sn_client/src/api/queries.rs, sn_client/src/api/register_apis.rs, sn_client/src/api/spentbook_apis.rs, sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_client/src/connections/mod.rs, sn_client/src/errors.rs, sn_dysfunction/src/detection.rs, sn_dysfunction/src/lib.rs, sn_interface/src/messaging/data/errors.rs, sn_interface/src/messaging/data/mod.rs, sn_interface/src/messaging/data/query.rs, sn_interface/src/messaging/data/register.rs, sn_interface/src/messaging/data/spentbook.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/messaging/system/mod.rs, sn_interface/src/messaging/system/node_msgs.rs, sn_interface/src/messaging/system/op_id.rs, sn_node/src/node/data/records.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/messaging/service_msgs.rs, sn_node/src/node/messaging/system_msgs.rs, sn_node/src/node/mod.rs, sn_node/src/storage/mod.rs, sn_node/src/storage/registers.rs
- Use the query msg id to generate the operation id to track the response from Adults
- Remove peers from pending data queries when response was obtained from Adults
- Removing correlation id from SystemMsg node query/response
- Redefine system::NodeQueryResponse type just as an alias to data::QueryResponse
=> refactor(messaging)!: removing op id from query response

sn_client/src/api/spentbook_apis.rs, sn_client/src/connections/messaging.rs, sn_client/src/errors.rs, sn_interface/src/messaging/data/errors.rs, sn_interface/src/messaging/data/spentbook.rs, sn_interface/src/network_knowledge/section_authority_provider.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/dbc_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_utils.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/service_msgs.rs
- bdcbeefd6 **feat: dbc spend can update network knowledge**
When a DBC is submitted for spending, there are a set of spent proofs sent along with the request,
one for each input for the DBC being spent. It's possible that these proofs were signed with a
section key that the section processing the request is not aware of. In this case, the request
processing section needs to be updated with new network knowledge. Therefore, we add a couple of
fields to the spend command to give it the option to send new network knowledge, namely the updated
proof chain and the signed section authority provider.
If the node detects the spend command has been sent with these, it will create a new type of
internal command, `UpdateNetworkAndHandleValidServiceMsg` which will be returned for processing.
This …
=> feat: retry dbc spend on unknown section key

sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/api.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/tests/dbc_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/dkg.rs
For more information, see the comment on the diff.
The generation of the DBC was also updated to use non-zero values for the `alpha` and `r` fields of `MlsagMaterial`, because zeroes and ones are special values in elliptic curve cryptography.
Also fixed a Clippy warning.
=> feat: use separate genesis dbc and section keys

sn_interface/src/network_knowledge/section_tree/mod.rs, sn_node/src/comm/mod.rs, sn_node/src/comm/peer_session.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_utils.rs, sn_node/src/node/node_starter.rs
Two changes
1. remove some unnecessary error handling in Comm
2. Remove the `bootstrap_node` argument to the join process.
The `bootstrap_node: SocketAddr` was there as a backup in case we did not have any peer entries in our SectionTree, but if you trace the logic all the way through, you can see that the `bootstrap_node` was being pulled from our `SectionTree`! So the fallback address is a fallback to itself?
=> Remove bootstrap node from join process; remove unneeded error handling in Comms

.github/workflows/sn_pr_tests.yml
You need to explicitly add `-- -Dwarnings` to get Clippy to exit with a non-zero code. Not sure if this is behaviour that just changed recently or we've always just missed it.
Also fixed a warning here.
=> ci: cause clippy step to fail on warnings

sn_interface/src/messaging/auth_kind.rs, sn_interface/src/messaging/authority.rs, sn_interface/src/messaging/mod.rs, sn_interface/src/messaging/serialisation/mod.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/flow_ctrl/event.rs, sn_node/src/node/messages.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/signing.rs
Nodes signs messages they send.
This signature is irrefutable proof of the nodes actions & is used to penalise bad behaviour.
BREAKING CHANGE:
=> refactor: NodeAuth -> NodeEvidence

sn_client/src/connections/listeners.rs, sn_interface/src/messaging/serialisation/mod.rs, sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/signing.rs
Removes the confusion @dirvine pointed out around:
```rust
pub fn verify_src_section_key_is_known(&self, known_keys: &BTreeSet<bls::PublicKey>) -> bool {
let section_pk = match &self {
// NB TODO this shouldnt be true! Remove all this
Self::Node(_) => return true,
```
=> refactor: adapt confusing auth related code

.github/workflows/sn_pr_tests.yml, sn_node/src/node/bootstrap/join.rs
This PR contains two main work:
1, liftup the joining node restart threshold, as with the feature branch with slower communication, the previous threshold is too sensetive that will restart BEFORE receive the approval. 
2, an attempt to expand range of changed code file that will trigger the fmt/clippy check.
=> Accumulate retry

sn_node/src/node/data/records.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/node_starter.rs
This also moves the logic to spawn the task to start processing messages and periodic checks onto a `FlowCtrl::start` instance constructor.
=> refactor(node): defining a private type to hold periodic checks timestamps within the FlowCtrl instance

sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/node_starter.rs
Packed channels may give us inintentional waits
=> chore(node): increase channel sizes.

sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/node_state.rs, sn_interface/src/network_knowledge/section_peers.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_interface/src/network_knowledge/test_utils.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/flow_ctrl/tests/mod.rs
- Also removes an unused match arm from `SectionPeers::update`
=> Unit tests for Network Knowledge modules

sn_interface/src/messaging/signature_aggregator.rs, sn_interface/src/messaging/system/section_sig.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/proposal.rs, sn_node/src/node/mod.rs
- Simplifies `SignatureAggregator`'s innards
- Removes timers
- Distinguish the case when the aggregation is still waiting for more share from `Error`s by returning `None` instead of an `Error`
- Make DKG use this one now that timers are gone
=> Refactored Aggregator

sn_interface/src/messaging/auth_kind.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_node/src/comm/listener.rs, sn_node/src/node/messages.rs
Removes `AuthKind::SectionShare` and all the awkwardness that came with it.
=> Remove section share auth

sn_node/src/storage/chunks.rs, sn_node/src/storage/register_store.rs
- Syncing data to disk right after writing reduces the changes of another task/thread reading the file obtains an empty content.
- Also this change checks the address of recreated Chunk after read from disk to make sure the content read is complete and matching the expected address.
=> fix(node): call to File::sync_data right after writing a Chunk or Register op to disk

Cargo.lock, sn_client/src/connections/listeners.rs, sn_dysfunction/Cargo.toml, sn_interface/Cargo.toml, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_peers.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_interface/src/network_knowledge/test_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_utils.rs, sn_node/src/node/relocation.rs
- `assert_lists` checks if two lists have the same elements independent of order. It was returning Result's but it should really be asserting.
- SectionPeer reads and writes are single threaded so no need to use dashmap
=> (tests): assert_lists actually asserts; switch SectionPeers to using BTreeMap's instead of DashMaps

.github/workflows/sn_pr_tests.yml, sn_api/src/app/files/mod.rs, sn_client/src/api/cmds.rs, sn_client/src/api/file_apis.rs, sn_client/src/api/queries.rs, sn_client/src/bin/query-adult/main.rs, sn_client/src/connections/messaging.rs, sn_client/src/errors.rs, sn_client/src/utils/test_utils/mod.rs, sn_client/src/utils/test_utils/test_client.rs, sn_node/src/bin/sn_node/main.rs
- This shouldn't only reduce the amount of memory used when uploading large files, but it shall also be more precise as to when a Chunk is ready for verification after uploading it, and which chunk specifically failed the verification.
- Sending a DataCmd now is not retried but only make sure it returns within the configured cmd timeout window.
- Using `expect()` in some client file tests to make sure Rust return useful info when errors occur, there is an issue with Rust test when Err is returned not showing enough failure info.
Also some changes are included to improve CI stability until some performance/design issues are solved:
- Run sn_client tests in single-threaded mode.
- Nodes to wait 30secs before retrying to joining the network when rejected.
- Testnet to launch nodes with an …
=> refactor(client): verify each Chunk individually in the `upload_and_verify` API

sn_client/src/connections/listeners.rs, sn_interface/src/messaging/mod.rs, sn_interface/src/messaging/msg_type.rs, sn_interface/src/messaging/serialisation/mod.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/node_msgs.rs
Remove signatures from node messages
- remove `msg_authority` from `MsgType::Node`
- remove the `NodeMsgAuthority` type altogether
=> Remove node auth

sn_node/README.md
fixes    [GRPC server 16685 connection refused ](https://github.com/jaegertracing/jaeger/issues/3852) issues with the  jaeger all-in-one image preventing sn_node traces being visible on the Jaeger UI
=>  Add port 16685 to docker run command for OTLP

.github/workflows/sn_pr_tests.yml, sn_cli/tests/cli_node.rs, sn_client/src/api/register_apis.rs, sn_client/src/api/spentbook_apis.rs, sn_client/src/connections/listeners.rs, sn_client/src/errors.rs, sn_client/src/utils/test_utils/mod.rs, sn_cmd_test_utilities/src/lib.rs
- Also removing unused test utilty from sn_api and unused sn_client::Error types.
- Disabling log instrumentation for large args of `spend_dbc` API.
- Re-enable CLI tests, single-threaded mode, disabling RUST_LOG. Also adds a note about this to errors.
=> refactor(client): test helper function for sleeping before querying published Register ops

sn_node/src/comm/mod.rs
We are currently closing our endpoint when we dropp a comms instance. This could lead to closed connections and other unintended consequences if we drop a clone while another instance persists
=> chore(node): Comm is clone. Dont close endpoint on drop.

sn_client/src/api/queries.rs, sn_client/src/api/spentbook_apis.rs, sn_client/src/connections/messaging.rs, sn_client/src/errors.rs, sn_interface/src/types/connections/mod.rs
Also including additional contextual information for a few `sn_client::Error` types.
=> feat(client): try to reconnect once when the client lost a connection to a peer

sn_node/src/comm/link.rs, sn_node/src/comm/peer_session.rs
This was currently potentially a blocker if there'd been connection issues. And might prevent other messages being sent
=> chore(node): move conn acquisition off thread too.

.github/workflows/sn_pr_tests.yml, Cargo.lock, sn_api/src/app/test_helpers.rs, sn_client/src/connections/listeners.rs, sn_client/src/utils/test_utils/mod.rs, sn_node/src/comm/listener.rs, sn_node/src/comm/mod.rs
- Upgrading qp2p to v0.30.1.
- Include bi-stream id in logs both on client and node sides.
- Removing unused sn_api and sn_client test helpers.
- Adding a 1sec delay in sn-api tests before querying uploaded data to potentially reduce the number of retrying queries.
=> chore(ci): set nodes join interval to 30secs for testnet in sn-api tests job

sn_cli/tests/cli_node.rs, sn_interface/src/messaging/system/join.rs, sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/join.rs, sn_node/src/node/mod.rs
There used to be a worry about too many nodes being relocated at the same time but that is no longer a concern there since we only relocate one node at a time.
This PR remove the age stepping logic so that the genesis sections do not have a special join process.
=> feat(join): remove age stepping in genesis sections

sn_interface/src/messaging/system/mod.rs, sn_interface/src/messaging/system/section_sig.rs, sn_interface/src/network_knowledge/node_state.rs, sn_interface/src/network_knowledge/section_authority_provider.rs
~~- Readable `AntiEntropyKind` debug messages; previously it printed out the entire binary~~
- `NodeState` is compacted to use half the characters
- `SectionAuthorityProvider` now provides more information while being compact
=> chore: impl custom `Debug` trait to compact the logs

sn_node/src/node/flow_ctrl/cmd_ctrl.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/node_starter.rs, sn_node/src/node/node_test_api.rs
Used for logging purposes.
***
The id of a cmd is a vec, where first entry represents the sequential nr of incoming cmds (does not increment by subsequent cmds - i.e. child cmds - spawned from such a cmd). 
I.e. `[0]` is the first cmd, `[235]` is the 235th cmd.
Second entry is the sequential nr of the child cmd spawned from the cmd at first entry, i.e. `[0, 2]` is the third child cmd of the first cmd, `[235, 0]` is the first child cmd of the 235th cmd.
And the first child cmd resulting from child `[235, 0]` would have the id `[235, 0, 0]`.
And so on. 
The trace back to the initial cmd is preserved, by entering the sequence nr of each child at every level of new children.
=> Reenable cmd ids and child ids

sn_client/src/connections/messaging.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_peers.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_interface/src/network_knowledge/test_utils.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/bootstrap/relocate.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_utils.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/proposal.rs, sn_node/src/node/relocation.rs
This PR makes a few test helpers panic instead of returning Result.
All the helpers changed would never return Err if the tests are written correctly, so a panic here is justified I think.
i.e. `prefix(&str)` takes a string of 0's and 1's, and returns a `Prefix`. passing anything other than 0's and 1's, i.e. `prefix("abc")` is a bad test ==> panic early.
This reduces some symbol noise in the tests, some tests are more affected than others but I think it generally reduces load when reading through.
=> refactor(tests): remove some `?` noise in tests

sn_node/src/node/cfg/config_handler.rs
=> fix(sn_node): avoid mem size change across compiler version update

Cargo.lock, sn_api/Cargo.toml, sn_api/src/app/wallet.rs, sn_cli/Cargo.toml, sn_client/Cargo.toml, sn_interface/Cargo.toml, sn_node/Cargo.toml
This resolves the large err variant clippy failures
```
warning: the `Err`-variant returned from this function is very large
--> sn_node/src/node/membership/mod.rs:403:51
|
403 |     fn sign_vote(&self, vote: Vote<NodeState>) -> Result<SignedVote<NodeState>> {
|                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 152 bytes
|
= help: try reducing the size of `node::membership::Error`, for example by boxing large elements or replacing it with `Box<node::membership::Error>`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
```
=> chore(deps): bump blsttc to 8.0.0

Cargo.lock, log_cmds_inspector/Cargo.toml, sn_cli/Cargo.toml, sn_cli/src/main.rs, sn_client/Cargo.toml, sn_interface/Cargo.toml, sn_node/Cargo.toml, sn_node/examples/routing_stress.rs
I noticed quite a few duplicated dependencies being pulled in i.e. `dirs-next = 0.1` and `dirs-next = 0.2`. You can see the full list with `cargo tree -d`.
With this PR, we consolidate quite a few dependencies which should net us a small improvement in compilation time.
A weak measure of how much duplication there is in our dependencies can be gotten by counting number of lines produced by  `cargo tree -d`
```bash
$ cargo tree -d | wc -l
800
```
```bash
$ cargo tree -d | wc -l
720
```
=> Reduce duplicate dependencies

Cargo.lock, sn_client/src/connections/messaging.rs, sn_interface/src/lib.rs, sn_interface/src/messaging/system/section_sig.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_authority_provider.rs, sn_interface/src/network_knowledge/section_peers.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_interface/src/network_knowledge/test_utils.rs, sn_interface/src/types/keys/mod.rs, sn_interface/src/types/keys/secret_key.rs, sn_interface/src/types/mod.rs, sn_node/Cargo.toml, sn_node/benches/data_storage.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/bootstrap/relocate.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/dbc_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_utils.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/proposal.rs, sn_node/src/node/relocation.rs, sn_node/src/storage/mod.rs
- Removes a test utility wrapper for `bls::SecretKeySet` . It was previously wrapped because there was no way to get `SecretKey` from the set. The current version of `bls::SecretKeySet` provides a method to do so.
- Organizes test utility functions into their own structs, e.g., `TestKeys` for all the key related utils, etc,. 
- Adds an utility to get `SecretKeySet` from a list of `SecretKeyShares`
- Adds an utility to get `NodeInfo` with varying age
- Removes unused dependency from `flow_ctrl/tests/`
=> refactor: test utilities

sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_client/src/connections/mod.rs, sn_client/src/errors.rs
- Also additional errors are defined now for the responses listener to report any type of failure so they are not considered as a lack of response.
- Setting a limit to the number of retries upon AntiEntropy responses received for a msg.
=> refactor(client): remove client internal channels from within Session mod

sn_node/src/comm/mod.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/anti_entropy.rs
- https://github.com/maidsafe/safe_network/pull/1750/commits/502a9769cdd786b2b5b2c3c559854355d2b64444  The `Comm` module does not use `spawn_local` anymore, hence we do not need to use a local task set for the tests
=> refactor(tests): remove `tokio::LocalSet`

sn_client/src/api/cmds.rs, sn_client/src/connections/listeners.rs, sn_client/src/errors.rs, sn_interface/src/messaging/data/mod.rs, sn_interface/src/messaging/msg_kind.rs, sn_interface/src/messaging/msg_type.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_node/src/comm/link.rs, sn_node/src/comm/listener.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/data/records.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/serialize.rs
- A new messaging type `ClientMsgResponse` is introduced explicitly for client msg responses.
- With new msg type, a new msg kind `MsgKind::ClientMsgResponse` is introduced which removes the need of providing a fake client authority in each of the responses sent by nodes to clients.
Nest step would be to have all types of Anti Entropy responses for clients to be part of `ClientMsgResponse` instead of having clients to accept `NodeMsg::AntiEntropy` messages.
=> refactor(messaging)!: breaking up client msg type separating requests from responses

sn_client/src/connections/messaging.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_authority_provider.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_utils.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/proposal.rs
- https://github.com/maidsafe/safe_network/pull/1755/commits/cd0b27a3aed7bb10a7bb1ab933bea208fb17b432 feat(test_utils): introduce `TestSapBuilder` to generate custom SAPs
Replaces the standalone utils into a single one to generate random
SAPs for testing.
- https://github.com/maidsafe/safe_network/pull/1755/commits/08054dbdb4d34cb7fc045189316d322f02d1c629 chore(test_utils): replace `TestSAP` with `TestSapBuilder`
=> chore(test_utils): use `TestSapBuilder`

sn_cli/src/operations/node.rs, sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_client/src/connections/mod.rs, sn_interface/src/messaging/data/errors.rs, sn_interface/src/messaging/data/mod.rs, sn_interface/src/messaging/msg_kind.rs, sn_interface/src/messaging/msg_type.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/messaging/system/mod.rs, sn_interface/src/messaging/system/node_msgs.rs, sn_interface/src/types/errors.rs, sn_interface/src/types/log_markers.rs, sn_interface/src/types/mod.rs, sn_node/examples/routing_stress.rs, sn_node/src/comm/listener.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/data/records.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/serialize.rs, sn_node/src/node/messaging/update_section.rs
- Returns the correct response type corresponding to the cmd.
- Adds the data address in question to the ack.
- Renames `ClientMsgResponse` to `ClientDataResponse`.
- Adds `NodeDataResponse` and aligns it to the pattern of `ClientDataResponse`.
- Moves data write acks to `NodeDataReponse`.
- Makes `NodeEvent` only be Adult to Elder notifications.
- Removes the `NodeQueryResponse` dead code path from `NodeMsg`.
- Removes some unnecessary derive macros from `QueryResponse`, `CmdResponse` and `sn_interface::messaging::data::Error`,
=> refactor(responses): return correct cmd response

sn_client/examples/churn.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_utils.rs, sn_node/src/node/mod.rs, sn_node/src/node/node_starter.rs
Moves the replication flow to be outwith of node, using channels to gather data and send it in another thread entirely. This should remove another cause of serious node.write().lock usage
=> chore(node): Remove locks in data replication flows.

sn_node/src/node/messaging/agreement.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/node_msgs.rs
previously we locked on handling _all_ anti entropy messages. now we pass in the `Arc<RwLock<MyNode>>` and only take the write lock if there _would_ be an update.
This should reduce the amount of write locks needed significantly as we have many more anti entropy messages that go out and may do _nothing_ (as only the first received for any message sent out will trigger an update... and we send messages to many nodes at once)
=> Ae lock reduction2

sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/mod.rs
Heaptracking has shown this to be ~80% of mem used, and moost of the time membership in the context is unused. Instead we now manually clone membership as/when we need it.
=> chore(node): remove Membership from NodeContext.

sn_client/src/connections/messaging.rs
If a Register's replica is found to contain more entries than another replica retrieved from another Adult, it doesn't necessarily mean it's a more up to date version of it, it could be the case that the last operation the user has made was to remove an entry from such Register.
=> chore(client): don't assume Register response with more entries as its most up to date replica

sn_node/src/node/flow_ctrl/tests/network_builder.rs
This module will replace the `TestNodeBuilder`.
- **feat(network_builder): define `TestNetwork` and `TestNetworkBuilder`**
The `TestNetwork` utility will facilitate setting up the environment for tests that make use of `MyNode` instances. We can tell the builder to generate a network with a specific SAP in a prefix and it will create a functional network with all the gaps filled in. It also allows us to retrieve a `MyNode` instance from any SAP with valid `Comm`, `NetworkKnowledge`, `SectionKeyProvider` etc.
- **feat(network_builder): build `TestNetwork` utility**
Calling the `build()` method will process the SAPs that the caller has provided and also generate SAPs for the missing prefixes. These are prefixes for which the SAPs are not provided by the caller, but are still required to …
=> feat(test_utils): Generate functional test Network

sn_client/src/api/cmds.rs, sn_client/src/connections/messaging.rs, sn_interface/src/messaging/data/mod.rs
Client should keep track of this, no need to burdon the network with more data transmission.
=> feat(ack): remove dataaddress from ack

.github/workflows/daily_droplet_run.yml, .github/workflows/release.yml
- 590df4d1b **ci: use s3_deploy user for nightly and release workflows**
In the nightly workflow, this user gets used to launch the testnet (really just reading the tfstate
file) and to upload node logs to the `sn-node` bucket when a run fails.
In the release workflow it's used to upload the built artifacts to the same `sn-node` bucket.
The names of the variables were changed to make it more specific about which user we were referring
to.
The keys being used previously have been deleted.
- f6d4cdd32 **ci: specify branch/user for testnet tool on nightly**
This allows forks of the testnet tool to be tried and tested.
Also fix references to S3 buckets in the nightly workflow.
=> ci: use s3_deploy user for nightly and release workflows

.github/workflows/run_pr_checks.yml, testnet/bin.rs
We now have infrastructure to spin up an EC2 instance if the job has been marked with `runs_on:
self-hosted`. These larger instances can help reduce the time taken for the overall workflow run.
In light of this, the jobs for the PR workflow have been redefined as follows:
* Various checks: a series of miscellaneous checks like `cargo fmt` and `cargo clippy`. The job for
linting the commits was combined into this job since there didn't seem to be a good reason for it
to use its own machine.
* Unused dependency check: as before. It would have been good to combine this job in the one above,
but it needs the nightly toolchain.
* Build node and testnet binaries: use an EC2 instance to quickly build the node and testnet
binaries, then upload the artifacts to S3. The purpose is to reduce build …
=> ci: reorganise jobs in pr workflow

sn_interface/src/statemap.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/node_msgs.rs
- `ValidateMsg` can be replaced with `HandleMsg`.
=> refactor(msgs): remove one layer of indirection

sn_client/src/api/mod.rs, sn_client/src/api/queries.rs, sn_client/src/connections/messaging.rs, sn_client/src/connections/mod.rs
It also fixes the private `send_query_without_retry` API which is currently ignoring the no-retry flag.
=> refactor(client): use internal send_query API to send initial probe msg to the network

sn_client/src/api/cmds.rs, sn_client/src/api/spentbook_apis.rs, sn_client/src/errors.rs, sn_node/src/comm/peer_session.rs, sn_node/src/node/data/records.rs, sn_node/src/node/messaging/client_msgs.rs
- Initialising logger in sn_client spentbook API tests.
- Including stream id in log messages.
- Report the error when a stream couldn't be finished when sending a response since that could mean the recipient didn't received it.
=> feat(node)!: adding more context info to some node Error types

.github/workflows/daily_droplet_run.yml
- 0ee62251a **ci: reference inputs correctly**
It looks like these inputs were always referenced incorrectly. A recent change for passing the user
and branch for the testnet tool has exposed this, because null values were being passed and causing
the testnet launch to fail.
- 8d2088c23 **ci: run node build job on ec2 for nightly**
This job is quite slow on the GHA infrastructure, particularly when debugging the workflow. This
seems like a good place to make use of an EC2 instance.
- 4126a08b6 **ci: use single thread for cli/api tests**
There are issues on Windows with the `fs::rename` function when the test suite is running with
multiple threads.
Code in the CLI related to the config file is calling this API to rename a temporary file to
`config.json` and on Windows you get an access …
=> Misc Nightly Run Modifications

sn_client/src/api/file_apis.rs, sn_client/src/connections/listeners.rs, sn_client/src/connections/messaging.rs, sn_client/src/errors.rs, sn_interface/src/types/connections/link.rs, sn_interface/src/types/connections/mod.rs
Also, adding more context info to sn_client `Error::FailedToInitateBiDiStream` and `Error::ChunkUploadValidationTimeout` error variants.
=> feat(client): retry once if connection was lost when trying to send on a bi-stream

.github/workflows/daily_droplet_run.yml
On the scheduled run the defaults from the `workflow_dispatch` inputs are not provided.
=> fix: pass defaults for testnet action inputs

sn_interface/src/messaging/system/mod.rs, sn_interface/src/messaging/system/proposal.rs, sn_interface/src/network_knowledge/section_authority_provider.rs, sn_interface/src/types/log_markers.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/agreement.rs, sn_node/src/node/messaging/handover.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/proposal.rs
This PR lets both children get the sibling sap at split.
When sending a msg that was intended for the sibling, and expecting an ae update with the sibling sap, it would instead return the sap of the first section itself (because it didn't know its sibling).
With the changes, both children are aware of each other from start, and we now get the sibling sap returned in the ae update.
=> feat(knowledge): update sibling on split

.github/workflows/daily_droplet_run.yml
The workspace name is appended to the URL when the network contacts and genesis DBC are retrieved.
=> fix: workspace folders are now used on S3

sn_node/src/node/data/records.rs, sn_node/src/node/flow_ctrl/dysfunction.rs, sn_node/src/node/mod.rs
- Prevents the logs from getting printed to the stdout while running node unit tests
=> chore(node): warn if dysf channels are closed

.github/workflows/run_pr_checks.yml, sn_cli/benches/files.rs, sn_cli/src/cli.rs, sn_cli/tests/cli_cat.rs, sn_cli/tests/cli_dog.rs, sn_cli/tests/cli_files.rs, sn_cli/tests/cli_files_get.rs, sn_cli/tests/cli_keys.rs, sn_cli/tests/cli_nrs.rs, sn_cli/tests/cli_wallet.rs, sn_cmd_test_utilities/src/lib.rs
- 20996c68e **feat: provide `--config-dir-path` arg for `safe`**
Add a global `--config-dir-path` argument that will set the location of the config directory. If
it's not set, the `SAFE_CONFIG_DIR_PATH` environment variable will be used, and if that's not set,
we will default to `$HOME/.safe`.
The purpose of this customisation is for integration testing so that each test can use an isolated
configuration directory, but users can apply it too if they wish.
- fb887ede4 **tests: use isolated config dir for cli tests**
A function is added to the test utils library for creating a temporary directory that functions as
the config directory for the CLI. It uses `assert_fs`, so the directory will be automatically
deleted when the reference to it is dropped. This enables each test case to use its …
=> tests: use isolated config dir for cli tests

sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/api.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/handover/handover_consensus.rs, sn_node/src/node/membership/mod.rs, sn_node/src/node/messaging/agreement.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/mod.rs
Currently we have logic that avoids updating the signed sap in Network-knowledge if we were an elder and we had not received our section key share yet.
This PR removes this logic as it was preventing other changes I was trying to make and it doesn't actually seem to be what we want: If a SAP update has occurred, then hanging on to the old SAP until we finish DKG does little to help the network as the other elders will update soon if they hadn't already, any signature shares this elder is creating with the old section key will only have a potential to be aggregated for that short period while we still have a threshold of old elders around still using the old SAP.
On a more philosophical point, we probably don't want elders to be signing anything after we've agreed to a handover.
=> Always update sap in network knowledge when we receive an AE update.

.github/workflows/daily_droplet_run.yml
Need to sort some publishing issues before a release runs again.
=> ci: temporarily disable nightly run

sn_interface/src/types/register/mod.rs
With the 1024 bytes per entry, that's 1mb per reg tops
=> feat: limit registers to 1024 entries

.github/workflows/run_pr_checks.yml, sn_api/src/authd_client/notifs_endpoint.rs, sn_client/src/connections/link.rs, sn_node/src/comm/link.rs, sn_node/src/comm/peer_session.rs, sn_node/src/node/data/records.rs, sn_node/src/node/messaging/client_msgs.rs
They dont mean a msg was not sent.
=> ignore qp2p::SendStream::finish errors, make the call non-blocking

.github/workflows/merge.yml, sn_client/src/connections/link.rs, sn_client/src/sessions/messaging.rs, sn_node/src/comm/link.rs, sn_node/src/storage/register_store.rs
- When writting Register cmds log to disk, we log and return the error for any of them failing, but we don't prevent the rest to be written to disk.
- Enable multi-threaded mode for sn_api tests in Bors.
- Some minor improvements to log msgs.
=> fix(storage): write all Register cmds to disk even if one or more fail

.github/workflows/version_bump.yml
The version bumping process will run on a push to `main`.
This will generate a `chore(release):` commit, which will be pushed to `main`, which will then kick off the release workflow.
=> ci: version bump on push to main

sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/membership/mod.rs
This reverts commit 38ebca089ed7134a63d9fefbf69f4f791b5858fb.
=> chore: Revert change split detection instead of size

sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/mod.rs
=> Chore improve replication batching

sn_interface/src/messaging/system/join.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/messaging/join.rs
This PR adds the joining nodes address to the join request.
If the address is different from the connection address, then this node is behind NAT 🙅
=> feat(join): prevent joins from nodes behind NAT

.github/workflows/version_bump.yml
This should only run when we do *not* have a release commit.
=> ci: prevent version bump running on release commit

sn_api/Cargo.toml, sn_api/src/app/test_helpers.rs, sn_cli/src/operations/config.rs, sn_client/src/sessions/messaging.rs, sn_interface/src/lib.rs, sn_interface/src/network_knowledge/errors.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_node/src/node/api.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/flow_ctrl/tests/network_builder.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/relocation.rs
Fixes https://github.com/maidsafe/safe_network/issues/1810 
Fixes https://github.com/maidsafe/safe_network/issues/1798
- fix(section_tree): genesis_sap is required to create the `SectionTree`
- The fields of the tree are assumed to be in sync. But it is not the case for a newly created tree.
- This can be fixed by accepting the genesis sap while creating the tree.
- refactor(network_knowledge): rework constructor
- Allows us to create a minimal `NetworkKnowledge` by just providing the genesis SAP. This will be set as our current `signed_sap`. A new `SectionTree` is also created with the provided SAP.
- Optionally, we can provide a `SectionTree` which will replace our current tree. In this case, the provided SAP is considered to be part of the tree and is set as our current `signed_sap`
=> fix: remove dummy SectionTree update

sn_node/src/comm/mod.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/network_builder.rs, sn_node/src/node/messaging/dkg.rs
- **fix(network_builder): fix edge case while calculating max_prefixes**
- When `max_bit_count == 0 (or) 1`, the logic for calculating the permutations failed, this fixes it.
- **feat(test): synchronously send `NodeMsg` to other nodes**
- This allows us to control the flow of msgs in certain tests allowing us to avoid using custom msg queues.
- **refactor(test): pass `NodeMsgs` via the `Comm` module**
- The dkg tests bypassed the `Comm` module and used a queue to pass along the `NodeMsgs` for testing. This was due to the fact that the msgs were sent asynchronously, preventing any control of the flow.
- Hence using the test-only synchronous msg sender allows us to do the above without using any extra queues.
=> tests: replace msg_queue with `Comm`

sn_node/src/bin/sn_node/main.rs
=> fix: persist log guard

sn_interface/src/messaging/serialisation/wire_msg.rs, sn_node/src/node/data/records.rs
- Also removing some minor but unnecessary WireMsg caching, and some objs cloning.
=> refactor(node): serialise the msg header only once when replicating data to holders

sn_interface/src/lib.rs, sn_node/src/bin/sn_node/log/mod.rs, sn_node/src/node/mod.rs, testnet/Cargo.toml, testnet/bin.rs
- fix(log): use vector of `Layers` to build the `Subscriber`
- Replaces the macros with a vector containing boxed Layers
- chore(testnet): enable otlp feature flag
- fix(log): prevent panic when we have multiple tracing subscribers
- When we have the `otlp` feature enabled, we effectively have
multiple subscribers consuming the logs.
- Under rare circumstances, we get a panic with the following msg,
`Format: was already formatted once`
- Turns out it's because the `itertools::format()` is being called
multiple times
- Was not able to reproduce the issue with a minimal setup, but this
gets rid of the panic.
- chore(log): remove unused event formatting option
- the `.event_format()` overrides the `.with_thread_names()` option,
hence remove it
=> fix(log): build tracing `Subscriber` without custom macros + small fixes

sn_node/examples/config_handling.rs, sn_node/src/node/cfg/config_handler.rs, sn_node/src/node/node_starter.rs
- We used to keep an instance of qp2p::Config within sn_node::Config which required to keep in sync when modifying/reading network related config, we now simply build a qp2p::Config just when is queried from sn_node::Config.
=> refactor(node): simplify logic retrieve qp2p config from sn_node::Config

.github/workflows/merge.yml, Cargo.lock, sn_client/src/api/client_builder.rs, sn_client/src/connections/link.rs, sn_client/src/sessions/messaging.rs, sn_interface/src/types/log_markers.rs, sn_node/src/comm/mod.rs
- By default the sn_client keep_alive msgs interval will now be set to 1/2 the value set for the
idle_timeout value.
- Removing unused ClientBuilder::cmd_ack_wait config value.
- Decreasing the CI timeout for sn_client, sn_api, and CLI tests, to 7mins.
- New LogMarker::IncomingConnection logged by sn_node.
- Minor improvements to some log msgs.
With PR #1927 we may be able to actually remove keep-alive msgs from client (if testing is successful), but this PR already introduces an improvement by reducing the amount of QUIC msgs sent to the network.
=> fix(client): set default keep-alive interval to be 1/2 of idle_timeout value set

sn_interface/src/network_knowledge/errors.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_node/src/node/api.rs, sn_node/src/node/data/records.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/update_section.rs
- [chore(errors): fix naming](https://github.com/maidsafe/safe_network/commit/224a669222396827336248f80eed9e2ffeda3079) 
-> There was an aiming error in the sentence structure. It's not the
proof chain that is not covered, it's the key that is not covered.
- [chore(unused): remove unused argument](https://github.com/maidsafe/safe_network/commit/f001f1d1bb26e15b8a8b4ccc03a23fa9a86ef161)
- [fix(name): rename from interrogative to imperative](https://github.com/maidsafe/safe_network/commit/98e051ec3f89b58d0304170f2e6433dfc835efb6) 
-> The naming was confusing as to what the method actually did.
- [chore(comments): remove outdated comment](https://github.com/maidsafe/safe_network/commit/70442ff64963ba46c4ec62e2fac5850ece26c2ee)
=> Minor fixes on post merge reviews

sn_client/src/api/client_builder.rs, sn_node/src/node/cfg/config_handler.rs, sn_node/src/storage/register_store.rs
- Setting sn_node idle-timeout to 70secs (to match ADULT_RESPONSE_TIMEOUT), which allows the node to keep client connections a bit longer since it may need more time (when under stress) to send back a response before closing them.
- Setting sn_client default idle_timeout to match query/cmd timeout values.
=> chore(client): disabling keep-alive msgs from client to nodes

sn_interface/src/messaging/system/node_msgs.rs, sn_node/src/comm/peer_session.rs, sn_node/src/node/data/records.rs, sn_node/src/node/messaging/node_msgs.rs
Dont return the full data, just the address. No
need to fill up other nodes as removing this one will trigger that flow
=> chore(node): lighten the CouldNotStoreData flow

sn_interface/src/messaging/serialisation/wire_msg.rs, sn_node/src/comm/listener.rs, sn_node/src/comm/mod.rs, sn_node/src/comm/peer_session.rs, sn_node/src/node/data/records.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/node_msgs.rs
Each `SendStream` is now moved into either `Cmd`s or functions instead of being shared using a `Mutex` around it.
=> refactor(node): removing mutex from SendStream

sn_interface/src/network_knowledge/section_peers.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/network_knowledge/sections_dag.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/flow_ctrl/tests/network_builder.rs, sn_node/src/node/messaging/agreement.rs, sn_node/src/node/messaging/dkg.rs
AE back and forth and other messaging can mean we make a good amount of partial_dags. Before this, we were pulling from a verified section_dag and verifying _every_ insert into our fresh partial dag.
This was costly. So now we avoid it.
=> fix(network_knowledge): avoid reverifying for partial dag creation

.github/workflows/merge.yml, .github/workflows/run_pr_checks.yml
hopefully should avoid random fails due to https://github.com/aig787/cargo-udeps-action/issues/2
=> ci(fix): use manual cargo udeps

sn_node/src/node/flow_ctrl/periodic_checks.rs
Move a DKG stalled msg to where it should be! Should declutter the logs.
=> fix: adapt logging to be less confusing

sn_node/src/node/data/records.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/streams.rs
Having these internal sn_node::Cmds to handle sending msg responses to clients and nodes over their bi-stream allow us to decouple such logic from the rest, but it also allows us to have unit tests within sn_node which verify the outcome of processing Cmds without sending any msg over the wire.
=> feat(node): adding SendClientResponse, SendNodeResponse, and SendMsgAndAwaitResponse cmds

Cargo.lock, sn_fault_detection/Cargo.toml, sn_fault_detection/src/detection.rs, sn_fault_detection/src/lib.rs, sn_node/src/node/flow_ctrl/fault_detection.rs, sn_node/src/node/messaging/streams.rs
We use bidi now, so we can report after any failure, no need for double accounting
=> chore(faults): Remove OpId for failed request tracking

sn_node/src/comm/mod.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/promotion.rs, sn_node/src/node/node_starter.rs
- Updates comms on member changes.
- Only adds connections to local cache if from a member.
Supersedes #1965.
=> feat(comm): only cache conns of members

sn_api/src/app/files/mod.rs, sn_api/src/app/resolver/mod.rs, sn_cli/src/subcommands/dog.rs, sn_cli/tests/cli_dog.rs, sn_client/src/api/file_apis.rs, sn_client/src/api/mod.rs, sn_client/src/api/queries.rs, sn_client/src/api/register_apis.rs, sn_client/src/api/spentbook_apis.rs, sn_client/src/lib.rs
- Exposing also an `sn_api` public API to fetch a file from a specified set of data replicas indexes and a `SafeUrl`.
- Adding `--replicas` arg to CLI `dog` command which allows the user to perform a check on several data replicas for the content being targeted by specifying their indexes.
- It currently supports querying data replicas only for `Files`, either with a `File`'s `XorUrl` or with any `SafeUrl` which resolves to a File.
- Non-pretty printing is also supported for the data replicas report, i.e. when passing `--output <format>` arg.
Example output from CLI querying `my-file.txt` linked from a FilesContainer to replicas with indexes 0, 2, 3, and 10 (index out of range of actual replicas), when some chunks were not found in any replica:
```
$ safe dog …
```
=> feat(client): expose a public API to query chunks to specific data replicas

sn_comms/src/lib.rs, sn_comms/src/peer_session.rs, sn_node/src/node/bootstrap/join.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/streams.rs
- Having this internal sn_node::Cmd to handle sending msg responses to nodes over a response bi-stream allows us to decouple such logic from the rest, but it also allows us to have unit tests within sn_node which verify the outcome of processing Cmds without sending any msg over the wire.
- We are here also changing Cmd::SendMsg to make/restricting it exclusively for sending msgs to nodes over uni-streams.
=> feat(node): introducing Cmd::SendNodeMsgResponse for NodeMsg responses to nodes over streams

sn_interface/src/messaging/signature_aggregator.rs, sn_node/src/node/messaging/handover.rs, sn_node/src/node/mod.rs
An attempt to fix DKG selfish termination by requiring total participation before going to Handover.
=> Require total participation for handover requests

sn_comms/src/error.rs, sn_comms/src/peer_session.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/messaging/data.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/serialize.rs, sn_node/src/node/messaging/streams.rs
- Unifying and simplifying logic to send client data cmds and queries to holders so in both cases the sn_node `Cmd::SendMsgAndAwaitResponse` is used.
- Renaming `sn_comms::Error::CmdSendError` to `SendError` since it's not specific for cmds but for any msg.
- Some internal sn_node helper functions were moved to different files/mods so they are closer to the logic making use of them.
=> refactor(node): sending client data cmds and queries to holders through Cmd::SendMsgAndAwaitResponse

sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/relocation.rs
Currently node relocations first go through a NodeIsOffline proposal flow. This flow was originally intended to check that enough elders agree that a node is faulty, i.e. detecting network connection errors, etc.
It's not needed for relocations since the relocation details has all the information we need to verify if a relocation request is valid.
This PR drops the NodeIsOffline proposal in favor of simply triggering the membership change directly.
This should allow us to more easily retry failed relocations
=> fix(relocation): skip the propose NodeIsOffline flow for relocations.

sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/messaging/client_msgs.rs
This also checks if the network knowledge provided in a `SpentbookCmd::Spend` cmd has any update against the `NodeContext`, before trying to update the actual node's network knowledge by triggering the internal `Cmd::UpdateNetworkAndHandleValidClientMsg`.
=> refactor(node): pass NodeContext within Cmd::UpdateNetworkAndHandleValidClientMsg

.github/workflows/merge.yml, .github/workflows/version_bump.yml
=> ci: prevent bors/bump version running concurrently

.github/workflows/merge.yml, Cargo.lock, sn_client/src/api/queries.rs, sn_client/src/connections/link.rs
- Re-enabling e2e sn_client tests multi-threaded mode.
- If a connection times out right after we sent a msg, but before we try to finish the stream, since we don’t await for the `finish` result we miss the chance to detect it and retry with new conn. This was made this way to avoid the await, but it seems, that at least for the client, we may want to wait for the `finish` result so we can retry in such scenarios.
- Retrying a test query only once, and only if the failure was due to receiving different responses from the data replicas, which may be due to a temporary out of sync. We've seen this very occasionally in CI with Register queries/entries.
=> fix(client): retry only once when check-replicas test query fails due to diff responses

.github/workflows/merge.yml, .github/workflows/release.yml, .github/workflows/run_pr_checks.yml, .github/workflows/version_bump.yml, resources/scripts/bump_version.sh, resources/scripts/get_release_description.sh, resources/scripts/insert_changelog_entry.py, resources/scripts/output_versioning_info.sh
- 2badf68d6 **ci: add arm builds to merge workflow**
We seen a failure on a release because an ARM build failed. The failure occurred because the `cross`
utility (which we use for cross compilation) wouldn't build correctly. Strangely, I wasn't able to
reproduce this problem, but I think it highlights the need for building on ARM before we merge. If
we are going to release on every merge, we will need to check that we can build on ARM.
- bfc96acdc **ci: slack notifications for workflow failures**
We didn't become aware of our latest release workflow failure for weeks after the event, so I've
enabled notifications for failures of either the version bumping or release workflows.
- d14f34bde **ci: add sn_comms crate to the release process**
This new crate is added to all the necessary …
=> Misc Release Process Updates

.github/workflows/release.yml, .github/workflows/version_bump.yml
The `failure` function in Github Actions only checks the failure of previous *steps* in a job, so it can only really be used on a per job basis.
It's cumbersome to have this on every job, but there appears to be no alternative way. Luckily there aren't many release-related jobs in the relevant workflows.
=> fix: correctly trigger failure notifications

.github/workflows/release.yml, .github/workflows/version_bump.yml
It looks like Github have removed `WORKFLOW_URL` as a pre-defined variable.
=> fix: provide link to workflow run on failure

resources/scripts/get_release_description.sh
The replacement for the `sn_comms` version in the release description was referencing the wrong variable.
=> fix: replace correct variable

sn_interface/src/messaging/system/join.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/messaging/joining_nodes.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/relocation.rs, sn_node/src/node/mod.rs
When a node is joining with a relocation proof, they could be rejected by one reason only: `AddressNotReachable`. This is because the other reject reason, `JoinsDisallowed`, does not apply to relocated nodes, making this state `unreachable`.
Address not reachable is an irrecoverable error, and therefore a node has to change their port configuration before starting a node again. However, this specific issue should be validated long before a relocation, by which this state is also considered `unreachable`.
Beyond those, and tampered proofs, it's just regular timeouts. 
So this feature allows a joining node with a relocation proof, to retry when the join times out.
=> feat(relocation): add retry for relocating node

sn_comms/src/lib.rs, sn_comms/src/listener.rs, sn_comms/src/peer_session.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/mod.rs
- We now use Comm::sessions as the list of members we keep sessions with, which is updated only when the user wants to update the set of known peers.
- Removing unnecessary PeerSession's SessionStatus, disconnect fn, and SessionCmd.
- Never remove sessions from Comm::sessions unless the set of known members is updated/changed by the user. Even if we failed to send using all peer session's connections, we keep the session since it's been set as a known and connectable peer.
=> refactor(comms): removing Comm::members and unnecessary private types

.github/workflows/merge.yml, .github/workflows/run_pr_checks.yml, sn_comms/src/lib.rs, sn_comms/src/peer_session.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs
- `sn_comms::Comm::send_out_bytes` was spawning a task when sending a msg, now it's the caller's duty to do so if required.
- Run sn_comms unit tests in CI/Bors.
=> fix(comms): send_out_bytes was not reporting send failures

sn_node/src/node/messaging/dkg.rs
Writes the debug to a var and uses that instead.
Dkg vote clones are a low hanging mem fruit
=> chore(node): remove a dkg vote clone only for logging.

sn_interface/src/messaging/data/errors.rs, sn_node/src/node/error.rs, sn_node/src/storage/chunks.rs, sn_node/src/storage/errors.rs, sn_node/src/storage/mod.rs, sn_node/src/storage/registers.rs
- The data storage is idempotent, and it's not an error that data already exists.
=> fix(storage): make data exists not be an error

Makefile
We're going to do some testnet experimentation with tracing so we want our releases to have the `otlp` feature enabled.
=> ci: enable the otlp feature on the release build

sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/mod.rs
- We were serializing before hitting the branch where it was needed.
- Also aligns fn name withy doc. The cases when no cmd is generated are the unreachable and invalid msg cases.
=> refactor: moves serialize call to where needed

sn_cli/src/operations/helpers.rs, sn_node/src/bin/sn_node/log/mod.rs
- 1c83fd880 **fix: pull the correct version of sn_node**
We added a new crate but forgot to account for the new version in the `node install` command, so it
was using sn_client's version number.
- 41fc52222 **feat: only submit traces if environment var is set**
We will only configure the tracing infrastructure if the `otlp` feature is enabled *and* the
`OTEL_EXPORTER_OTLP_ENDPOINT` environment variable is set.
=> Fix Misc User Experience Issues

sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_peers.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/membership/mod.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/promotion.rs, sn_node/src/node/messaging/relocation.rs, sn_node/src/node/mod.rs
- fix(relocation): retain comms to members undergoing relocation
- We retain comms to the relocating members which are signed by our current SectionKey
- This should allow us to send the `Relocate` msg to the relocating node
- chore(membership): send NodeApprovals for the joining nodes only
- Produced approval messages with empty recipients
- feat(test): use TestMsgCounter to keep track of NodeMsgs
- Make the Comms in the tests to be asynchronous. Hence we cannot rely on empty buffers to terminate the tests.
- Instead, use `MsgId` to terminate the tests if the peers receive all the sent messages.
- This commit also makes the tests more accurate and hence removes a dkg test which was invalid.
=> relocation: tests + comm fixes

.github/workflows/merge.yml
When `e2e-msg-happy-path` tests fails, the uploaded log filename clashes with the one uploaded by a failed `e2e` action loosing them.
=> fix(ci): set different name for node logs on `e2e-msg-happy-path` action run

sn_client/src/sessions/listeners.rs, sn_interface/src/messaging/data/errors.rs, sn_interface/src/messaging/data/mod.rs, sn_node/src/node/messaging/streams.rs
- `ClientDataResponse` variant `CommunicationIssues` was not differentiated on client, and was carrying the exact same error enum as the variant `NetworkIssue`.
=> chore: remove redundant enum variant

sn_interface/src/messaging/system/join.rs, sn_node/src/node/messaging/join_section.rs, sn_node/src/node/messaging/joining_nodes.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/relocation.rs
TryJoin wasn't previously answered over the bi-stream. This adds a
'Considering' response that is sent back over the same stream.
=> refactor(node): send response to joiner

sn_comms/Cargo.toml, sn_comms/src/error.rs, sn_comms/src/lib.rs, sn_comms/src/listener.rs, sn_comms/src/peer_session.rs, sn_interface/src/messaging/data/errors.rs, sn_interface/src/messaging/system/mod.rs, sn_interface/src/types/log_markers.rs, sn_node/src/node/connectivity.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_builder.rs, sn_node/src/node/messaging/data.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/handover.rs, sn_node/src/node/messaging/join_section.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/relocation.rs, sn_node/src/node/messaging/streams.rs, sn_node/src/node/node_starter.rs
This removes dashmap use for sessions in comms.
It also makes comms error handling and issue reporting focused to one place.
Additional thing to note is that Elders now relay responses back to client as soon as they are received.
The way the requests are designed now, that would only be more than one response when storing data,
since queries from a Client, only go out to one data holder from the Elders.
=> refactor(comms): remove use of dashmap

sn_comms/src/lib.rs, sn_comms/src/peer_session.rs
- Removes some unnecessary spawning and channel faff, since we're already on a new thread.
=> refactor(comms): simplify peer_session

sn_node/src/node/cfg/config_handler.rs
=> test: fix failing test after rustup update

.github/workflows/merge.yml, sn_client/src/api/cmds.rs, sn_client/src/errors.rs, sn_client/src/sessions/messaging.rs, sn_node/src/node/messaging/streams.rs
Running all sn-client tests multi-threaded in CI/Bors.
=> feat(client)!: include msg-id in sn_client::Error::CmdAckValidationTimeout

sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/join_section.rs, sn_node/src/node/messaging/joining_nodes.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/relocation.rs, sn_node/src/node/messaging/streams.rs
- refactor(test_utils): bundle `TestMsgTracker` along with `Dispatcher`
- This removes a lot of boilerplate code from the tests, eliminating potential sources for bugs.
- refactor(cmd): include `MsgId` with the stream response Cmd
- The `SendNodeMsgResponse` and the `SendClientResponse` now contain both the `msg_id` and the `correlation_id`
- fix(test): send the stream response
- Sends back a response through the bidi-stream eliminating the error msgs that were popping up.
=> refactor: `Cmd` + test utils

sn_node/src/storage/mod.rs, sn_node/src/storage/register_store.rs
As nodes fill up they check if there's any data they are no longer responsible for, and clean it up.
It was missing the removal of registers.
NB: This can be made more granular, by looking at close nodes instead of prefix.
=> fix: extend cleanup to registers

sn_client/src/sessions/listeners.rs, sn_comms/src/lib.rs, sn_comms/src/listener.rs, sn_interface/src/messaging/anti_entropy.rs, sn_interface/src/messaging/data/mod.rs, sn_interface/src/messaging/mod.rs, sn_interface/src/messaging/msg_kind.rs, sn_interface/src/messaging/msg_type.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/messaging/system/mod.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/statemap.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/join_section.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/relocation.rs, sn_node/src/node/messaging/serialize.rs, sn_node/src/node/messaging/streams.rs, sn_node/src/node/mod.rs
Since `AE` msgs are not specifically node or client type, but used by both, this type is extracted out and lifted up one level. Thereby the duplication in `DataResponse` variant is removed.
=> refactor(msg): split out ae

sn_client/src/api/client_builder.rs, sn_client/src/api/cmds.rs, sn_client/src/api/file_apis.rs, sn_client/src/api/mod.rs, sn_client/src/api/queries.rs
sn_client is now set to send msgs to the network without any default timeout values, the user of the lib can still set them with SN_CMD_TIMEOUT and SN_QUERY_TIMEOUT env vars according to its own requirements.
=> feat(client): sn_client to not have any default cmd/query timeout value set

sn_interface/Cargo.toml, sn_interface/src/messaging/system/mod.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_peers.rs, sn_node/Cargo.toml, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/mod.rs
Being the first step as described within the issue https://github.com/maidsafe/safe_network/issues/2081 , the work of this PR relies on couple of TODO points that shall get addressed in the following PRs :
1, the util function of `section_signed_to_decision` shall get removed once complete the full transition
2, Decision requires the PublicKeySet to validate, however NetworkKnowledge only retains the PublicKey info currently. Need to re-enable the validation in the following PR
3, The current `update`, `merge_members` procedure is based on `node_state` as atomic. However `Decision` may contain multipe of `node_state` within one. Need to double check this won't incur any trouble.
4, The current `members` function return list of `Decision`, which may contain `Join` and `Left` in one …
=> feat(sn_node): refactor SectionPeers to use Decision

Cargo.lock, sn_cli/Cargo.toml, sn_client/Cargo.toml, sn_comms/src/lib.rs, sn_node/README.md, sn_node/examples/config_handling.rs, sn_node/src/bin/sn_node/main.rs, sn_node/src/node/cfg/config_handler.rs, sn_node/src/node/flow_ctrl/tests/network_builder.rs, sn_node/src/node/node_starter.rs, testnet/Cargo.toml
The genesis node will output a network contact file which contains its own address. This public address was specified by a separate flag but was removed, making the genesis incapable of producing a proper contacts file. This changes the `--first` flag to be used to pass in that public address, which should be done for all genesis nodes, so the proper external address can be advertised.
See https://github.com/maidsafe/sn_launch_tool/pull/136 for relevant changes in the sn_launch_tool after which this PR can be turned into review mode.
=> refactor(node): pass public addr in --first

.github/workflows/benchmarks_pages.yml, Cargo.lock
=> ci: limit charts to 500 entries

sn_node/examples/config_handling.rs, sn_node/src/bin/sn_node/main.rs, sn_node/src/node/cfg/config_handler.rs
- docs(node): fix documentation about verbose flag
- chore(node): remove deprecated clap setting
- refactor(node): instantiate Config without runtime
=> refactor config instantiate

.github/workflows/merge.yml, .github/workflows/run_pr_checks.yml, sn_cli/Cargo.toml, sn_cli/src/cli.rs, sn_cli/src/subcommands/cat.rs, sn_cli/src/subcommands/dog.rs, sn_cli/src/subcommands/files.rs, sn_cli/src/subcommands/files_get.rs, sn_cli/src/subcommands/helpers.rs, sn_cli/src/subcommands/mod.rs, sn_cli/src/subcommands/nrs.rs
This gives a first simple version of a `payment-network`.
Storing data needs enabling of the `data-network` feature.
NB: This does not gate it in `sn_node`, thus with a custom client, data operations could still be available.
As the current wallet impl is dependent on the data storage, we cannot gate data without updating the wallet to work without it. That is a larger change suitable for a follow up PR.
=> chore: feat gate data

.github/workflows/release.yml, Cargo.lock, Cargo.toml, resources/scripts/bump_version.sh, resources/scripts/get_release_description.sh, resources/scripts/insert_changelog_entry.py, resources/scripts/output_versioning_info.sh, sn_cli/Cargo.toml, sn_cli/src/cli.rs, sn_cli/src/operations/helpers.rs, sn_cli/src/operations/mod.rs, sn_cli/src/operations/node.rs, sn_cli/src/subcommands/mod.rs, sn_cli/src/subcommands/update.rs, sn_node/Cargo.toml, sn_node/examples/config_handling.rs, sn_node/src/bin/sn_node/main.rs, sn_node/src/node/cfg/config_handler.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_updater/CHANGELOG.md, sn_updater/Cargo.toml, sn_updater/README.md, sn_updater/src/errors.rs, sn_updater/src/lib.rs
- 00c77f428 **chore: introduce sn_updater library crate**
This library crate provides utility code to be shared between the `safe` and `sn_node` binaries so
they can update themselves to the latest version.
We can no longer use the `self_update` crate to do this with a single statement because
`self_update` is designed for use with single-crate repositories, though we do still make use of
utility code it happens to make public.
The crate makes an `update_binary` function available. The doc comments in the diff provide details
of how it works, so I won't repeat that here.
- 7d6b2c5ff **fix: restore sn_node update command**
The updating mechanisms for the `safe` and `sn_node` binaries stopped working when we switched to
using a workspace repository.
We now make use of the newly introduced …
=> Restore Updating Mechanisms for `safe` and `sn_node` Binaries

.github/workflows/merge.yml
This may mean that bump versions are blocked at the moment, but it actually seems like it was no longer used?
=> ci: attempt to enable running pr checks with a comment

sn_client/src/api/file_apis.rs, sn_client/src/api/queries.rs
Also, avoid retrying the query to check a chunk is stored. If the 'check-replicas' feature is enabled it will already retry upon receiving different responses from replicas.
=> fix(client): use max_backoff_interval when retrying checking replicas

sn_cli/src/subcommands/files_get.rs, sn_fault_detection/src/lib.rs, sn_interface/src/lib.rs, sn_interface/src/messaging/authority.rs, sn_interface/src/messaging/data/cmd.rs, sn_interface/src/messaging/data/mod.rs, sn_interface/src/messaging/data/query.rs, sn_interface/src/messaging/data/register.rs, sn_interface/src/messaging/msg_kind.rs, sn_interface/src/messaging/serialisation/wire_msg.rs, sn_interface/src/messaging/serialisation/wire_msg_header.rs, sn_interface/src/messaging/system/dkg.rs, sn_interface/src/messaging/system/join.rs, sn_interface/src/messaging/system/mod.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_peers.rs, sn_interface/src/network_knowledge/section_tree/mod.rs, sn_interface/src/types/address/mod.rs, sn_interface/src/types/mod.rs, sn_interface/src/types/peer.rs, sn_interface/src/types/register/mod.rs, sn_interface/src/types/register/policy.rs, sn_node/src/node/api.rs, sn_node/src/node/cfg/config_handler.rs, sn_node/src/node/mod.rs, sn_node/src/node/node_test_api.rs
This PR was produced with the help of [warnalyzer](https://github.com/est31/warnalyzer), which attempts to analyze a workspace like `safe_network` and spot APIs that are not used within the project. This is not picked up by default tools, as these are marked with `pub`.
Interesting to see if this might have an impact on build times.
- refactor: remove unused pub fn/methods
- refactor: fix clippy lints; fmt
- refactor: remove more unused pub
=> Remove unused pub interface

sn_interface/src/network_knowledge/mod.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/promotion.rs, sn_node/src/node/mod.rs
We were only updating members if the SAP changed. We were attempting to terminate DKG runs if members changed.
Now those two flows are distinct
=> fix: ae updates and affects split into sap and member updates

sn_interface/src/messaging/system/mod.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/node_state/mod.rs, sn_interface/src/network_knowledge/node_state/relocation.rs, sn_interface/src/network_knowledge/section_peers.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/relocation.rs
This is intended to make it a little bit easier to get an intuition for what the back-and-forward process here is about.
The reason this was implemented in the first place is that due to membership changes being limited to one at a time, we needed the node to drive the process and keep polling the elders to get it to proceed, so that it in the end could be completed even in the presence of concurrent membership changes.
| 1. Elders->Node  | 2. Node->Elders (polling) | 3. Elders->Node |
| ------------- | ------------- | ------------- |
| PrepareToRelocate | ProceedRelocation | CompleteRelocation |
=> chore: clarify relocation flow

.github/workflows/benchmark_prs.yml, .github/workflows/benchmarks_pages.yml, .github/workflows/merge.yml, resources/scripts/all_nodes_joined.sh
- This is also changing the script to not only compare the nodes' IPs but also their names.
- Changing CI to use 14 nodes for testnets launched.
Example output of a detection reported by updated script:
```
Checking nodes log files to verify all nodes have joined. Logs path: /home/runner/.safe/node/local-test-network
Number of nodes: 14
All nodes have joined. Nodes names and IPs:
bfdafe(10111111)->127.0.0.1:34480 sn-node-12
1e8e67(00011110)->127.0.0.1:60079 sn-node-genesis
28f7dd(00101000)->127.0.0.1:55884 sn-node-7
8c89de(10001100)->127.0.0.1:57425 sn-node-2
777f6a(01110111)->127.0.0.1:46141 sn-node-8
29c050(00101001)->127.0.0.1:55646 sn-node-10
58c1b4(01011000)->127.0.0.1:49787 sn-node-9
6a21d7(01101010)->127.0.0.1:55231 sn-node-3
67bcd1(01100111)->127.0.0.1:34405 sn-node-4 …
```
=> fix(ci): adapt script to check joined nodes to log msgs changes

resources/scripts/all_nodes_joined.sh, sn_node/src/node/relocation.rs
If section size is equal to the recommended section size, we would look up for relocation candidates but we were actually discarding them.
=> chore(node): avoid unnecessary relocation candidates look up

Makefile
Without this `safe` doesn't have certain commands, which has been confusing to users.
=> ci: add data-network feature to release process

sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/mod.rs
When membership is updated by an AE message, we check if our ongoing DKGs contain any non-member candidates as to avoid wasting energy on messages for nodes that are not in our section anymore. 
This fixes some DKG gossip loops we've been seeing, with nodes ignoring DKG gossip because they where relocated and the others gossiping forever in the hopes of seeing them back!
=> Remove DKG sessions with absent members on membership update

.github/workflows/merge.yml
=> ci: remove concurrency limitations

sn_interface/src/network_knowledge/node_state/relocation.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/membership/mod.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/relocation.rs
=> Chore update logs around relocation

sn_interface/Cargo.toml, sn_interface/src/messaging/system/mod.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/node_state/mod.rs, sn_interface/src/network_knowledge/node_state/relocation.rs, sn_interface/src/network_knowledge/section_member_history.rs, sn_interface/src/network_knowledge/test_utils.rs, sn_node/Cargo.toml, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/membership.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/relocation.rs, sn_node/src/node/mod.rs, sn_node/src/node/relocation.rs
In this PR:
- `CurhnId` moved to network_knowledge
- `RelocationDst` replaced with `RelocationTrigger` 
- `RelocationTrigger` has decision and therefore it is verifiable
- Test are updated to use trigger (result of decision)
It fixes #2011 
Perhaps we can mock the decision (consensus) for faster tests.
=> fix: verifiable relocation trigger

.github/workflows/merge.yml, sn_client/examples/churn.rs, sn_client/src/api/mod.rs
Currently, the E2E churn test fails once in a while. This is mostly due to the client not connecting properly while nodes are added to the network.
This PR introduces the client not retrying connecting by default. This will be the responsibility of the API user. In the case of the client churn example, it will be retried up to 5 times with a delay of 1.5s.
Also, the CI will build the churn example in a separate step so we more tightly see how long the example runs for.
=> feat(client): do not re-attempt connect

sn_interface/src/types/keys/public_key.rs, sn_interface/src/types/mod.rs, sn_node/src/node/api.rs, sn_node/src/node/cfg/keypair_storage.rs, sn_node/src/node/flow_ctrl/tests/network_builder.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/mod.rs, sn_node/src/node/node_starter.rs
This is the first step to simple dbc tx fees and rewards for Elders.
It allows Elders to check if dbc transactions contain any output for them.
***
Follow up PRs:
- Including Elders in outputs (any value) when spending DBCs.
- Elders confirming that spends contain outputs destined for them.
- Implementing a commonly known deterministic transfer/store cost and distribution to nodes.
- Including transfer/store cost in outputs when spending DBCs.
- Elders confirming that the amounts in those outputs are sufficient.
=> feat(rewards): add bls pub key to node

.github/workflows/merge.yml
We are using [skip-duplicate-actions](https://github.com/fkirc/skip-duplicate-actions) to detect the duplicated jobs. This helps to reduce the time merge. However,  are situations that the skip won't trig the merger job and as a result the PR won't be merged (even if it is in merge queue) . 
In this PR we check all jobs are not failed before merging in the last job
=> fix(github_action): check if all jobs are not failed before merging

sn_interface/src/messaging/system/dkg.rs, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/types/identities/client_id.rs, sn_interface/src/types/identities/mod.rs, sn_interface/src/types/identities/node_id.rs, sn_node/src/node/flow_ctrl/cmds.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/messaging/data.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/handover.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/section_state.rs, sn_node/src/node/messaging/update_section.rs
=> chore: clean up a few things from commit 4097de4

sn_comms/src/listener.rs, sn_node/src/node/flow_ctrl/mod.rs
The serialization is only for logging and we already have 
the serialized msg earlier in the flow, so the log can be moved to that place.
=> chore(msgs): remove unnecessary serializing

sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/cmd_ctrl.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/flow_ctrl/tests/cmd_utils.rs, sn_node/src/node/messaging/mod.rs
Moves heaps of non critical Cmds out of the blocking mut MyNode context. Allows them to run w/ latest context; only pushing a subset of Cmds into the blocking process loop
=> feat(node): push non-blocking Cmds off thread

sn_api/src/app/wallet.rs, sn_client/src/api/mod.rs, sn_client/src/api/queries.rs, sn_client/src/api/spend_queries.rs, sn_client/src/sessions/messaging.rs, sn_interface/src/messaging/data/mod.rs
This PR adds concurrent querying of each elder for their respective reward
key and fee, and replaces the dummy fee with the result from the implemented query.
***
1. Including Elders in outputs (any value) when spending DBCs.
1.1 `Previous PR`: The query and handling of it on Elders for their reward keys and hard coded fee (#2184).
1.2 `Previous PR`: The logic for including Elders to outputs (#2180).
1.3 `This PR`: ✔️ Connecting the two above, by the client logic for querying Elders for their reward keys and fee.
PRs in the overall feature:
- <s> 1. Including Elders in outputs (any value) when spending DBCs.</s>
- Elders confirming that spends contain outputs destined for them.
- Implementing a commonly known deterministic transfer/store cost and distribution to nodes.
- Including …
=> feat(rewards): send fee query to elders

sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/node_starter.rs
=> fix(node): update flowctrlcmd NodeContext during join

sn_interface/src/messaging/system/join.rs, sn_interface/src/messaging/system/mod.rs, sn_node/src/bin/sn_node/main.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/messaging/join_section.rs, sn_node/src/node/messaging/joining_nodes.rs, sn_node/src/node/messaging/node_msgs.rs
The join response about the node not being reachable is something we
will never get or send. This is because we do not check specifically for
reachability anymore.
=> refactor(node): remove unused join response

sn_interface/src/network_knowledge/section_authority_provider.rs, sn_interface/src/network_knowledge/test_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/flow_ctrl/tests/network_builder.rs, sn_node/src/node/flow_ctrl/tests/test_utils.rs, sn_node/src/node/membership/mod.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/join_section.rs, sn_node/src/node/messaging/relocation.rs
- Adds some improvements to the `TestNetworkBuilder` by integrating the `TestSapBuilder` into it.
- The relocation tests were using an old flow ( `VoteNodeOff`) which was not representative of the actual flow. Thus now we actually trigger relocation by a membership change and go through the entire relocation process.
=> tests: relocation fix + refactor utils

sn_client/src/api/data/pac_man.rs, sn_client/src/api/mod.rs, sn_interface/src/types/chunk.rs, sn_interface/src/types/mod.rs
- The used value was not linked to actual self_encryption value.
=> fix: use max self_encryption chunk size

.github/workflows/release.yml, .github/workflows/version_bump.yml, Makefile
Renames the `sn_cli` assets on the Github Release from `sn_cli` to `safe`. This was supposed to be done as part of the last modification to the process, but I seem to have accidentally missed it.
I'm also re-enabling the release and version bumping workflows to run on push now that I've cleared out the last bad release.
=> ci: rename sn_cli asset name

.github/workflows/release.yml, .github/workflows/version_bump.yml, Cargo.lock, sn_api/Cargo.toml, sn_client/Cargo.toml, sn_comms/Cargo.toml, sn_interface/Cargo.toml, sn_node/Cargo.toml
These crates already have published versions at 0.20.6 and 0.78.6, so reverting the commits didn't work correctly for these.
Also temporarily disabling the release and merge workflows again because I don't want to trigger a release before I tag these manually.
=> chore: manually bump sn_interface and sn_node

Cargo.lock, sn_interface/Cargo.toml, sn_interface/src/network_knowledge/mod.rs, sn_interface/src/network_knowledge/section_member_history.rs, sn_node/Cargo.toml, sn_node/src/node/handover/handover_consensus.rs, sn_node/src/node/membership/mod.rs, sn_node/src/node/messaging/node_msgs.rs
This should slim down the size of consensus decisions substantially. Validation should be much quicker as well.
=> chore(deps): bump consensus

.github/workflows/release.yml, .github/workflows/version_bump.yml
The tags from the last release have now been deleted and the version bump commit has been reverted. Merging this should cause the same version bump again, but with the `sn_interface` issue resolved this time.
=> ci: re-enable version and release workflows

sn_testnet/src/main.rs
Running cargo clippy on win machine was borked with the conditional
over an error in a fn, as the following code became unreachable.
Placing it in the if clause body removes this clippy error, as the
rest of the code in that can still be executed if the flame arg was not
set.
=> fix(testnet): move os cond. to if-clause body

sn_interface/src/network_knowledge/node_state/relocation.rs, sn_node/src/node/context.rs, sn_node/src/node/flow_ctrl/periodic_checks.rs, sn_node/src/node/messaging/node_msgs.rs, sn_node/src/node/messaging/relocation.rs, sn_node/src/node/mod.rs
This also adds an improvement to the relocation process where we try to finalise an ongoing relocation both when we receive the join approval, or with our periodic checks. 
This prevents from having unnecessary delays in updating the node's internal state, i.e. if the join approval is received we update our state and members right away, without having to wait till the periodic check's timer goes off. If, on the contrary, we missed the join approval msg but we've got an AE msg where we learned we've been approved, then we'll perform the node's internal state update with the periodic check as usual.
=> fix(node): node to update its own members list upon being relocated

.github/workflows/release.yml, .github/workflows/version_bump.yml
I am currently working on changing the release process for the addition of the new testnet crate, so we will continue to get version bumping errors until that work is finished.
This temporarily disables the process.
=> ci: temporarily disable version bumping

sn_node/Cargo.toml, sn_testnet/src/main.rs
=> refactor(node): remove unused wiremsg-debuginfo ft

.github/workflows/merge.yml, sn_node/src/node/messaging/mod.rs
The previous check for "is from me" was failing due to a local 0.0.0.0 representation in testnets vs 127 from other nodes...
This was leading to looping.
But only checking if it was forwarded from ourselves would mean if an elder was a storage node, we'dsee and forward on the same message several times (as each elder sends it on to us, and its not from us, so we forward to the adults in question etc).
This check solves both situations
=> fix(node): check when handling msg if is from member

Cargo.lock, Justfile, log_cmds_inspector/Cargo.toml, sn_api/CHANGELOG.md, sn_api/Cargo.toml, sn_cli/CHANGELOG.md, sn_cli/Cargo.toml, sn_client/CHANGELOG.md, sn_client/Cargo.toml, sn_cmd_test_utilities/Cargo.toml, sn_comms/CHANGELOG.md, sn_comms/Cargo.toml, sn_interface/CHANGELOG.md, sn_interface/Cargo.toml, sn_node/CHANGELOG.md, sn_node/Cargo.toml, sn_testnet/CHANGELOG.md, sn_testnet/Cargo.toml
- 404e0a7a2 **fix: check release commit correctly**
I was led to believe that the parentheses would need to be escaped, but seemingly this is not the
case.
- 4cf488c00 **Revert "chore(release): sn_testnet-0.1.3/sn_interface-0.20.7/sn_comms-0.6.4/sn_client-0.82.4/sn_node-0.80.1/sn_api-0.80.3/sn_cli-0.74.2"**
This reverts commit b0627339e2458fd762084cc4805d7adedfd8c05e.
=> Fix commit check

Justfile
Without the subshell it tries to change from the previous directory.
Also remove the constraint to run from a version commit. This will not always be the case when you need to do manual fix ups, like right now when this change is merged.
=> fix: use subshell to change directory

Cargo.lock, sn_interface/Cargo.toml, sn_interface/src/types/fees/errors.rs, sn_interface/src/types/fees/fee_ciphers.rs, sn_interface/src/types/fees/mod.rs, sn_interface/src/types/fees/required_fee.rs, sn_interface/src/types/fees/required_fee_content.rs, sn_interface/src/types/mod.rs, sn_node/src/node/error.rs
These types allow Elders to verify that a fee amount, and a sufficient
amount, has been included in a spend output.
***
The fee amount is hidden both ways between Elders and Clients.
The ciphers of the derivation index and blinding factor is included in the spend request 
sent to elders. By that, an Elder can now verify that it has been paid the required fee amount.
**NB**: The elders do not yet verify that they have been paid (that is done in PR #2246).
=> feat(fees): add fee types

sn_api/src/app/test_helpers.rs, sn_api/src/app/wallet.rs, sn_api/src/errors.rs, sn_client/src/api/mod.rs, sn_client/src/api/spentbook_apis.rs, sn_client/src/api/transfers/errors.rs, sn_client/src/api/transfers/mod.rs, sn_client/src/errors.rs, sn_interface/src/types/keys/secret_key.rs, sn_node/src/node/flow_ctrl/tests/dbc_utils.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/client_msgs.rs
With this PR an Elder now verifies that a spend contains an output for them
with correct amount.
This is done by decrypting the fee ciphers sent from client in a spend,
confirming that there is an output to the key derived from the elder reward key,
and that the amount of the output is equivalent to the decrypted amount.
The basic rule for now is that if the paid fee is over 1% less than the required fee, we don't accept the fee.
This is a temporary diff value/design.
(And yes, this means that for now, the Client can try to get away cheaper by sending in up to 1% lower fee than they were asked for.)
***
1.  ✔️ `Previous feat`: Including Elders in outputs (any value) when spending Dbcs.
2. ✔️ `Previous feat`: Including fee ciphers for Elders in spend: #2249.
3. `This PR`: Elders confirming …
=> feat(fees): verify amount at elder 

sn_interface/src/network_knowledge/section_authority_provider.rs, sn_node/src/bin/safenode/main.rs, sn_node/src/node/flow_ctrl/dispatcher.rs, sn_node/src/node/flow_ctrl/mod.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/handover/handover_consensus.rs, sn_node/src/node/messaging/anti_entropy.rs, sn_node/src/node/messaging/dkg.rs, sn_node/src/node/messaging/handover.rs, sn_node/src/node/messaging/mod.rs, sn_node/src/node/messaging/relocation.rs, sn_node/src/node/mod.rs
This PR contains fixes to resolve CI faiures due to network startup problem:
1, do not cast outdated handover vote after aggregated
This will cause blocking to followup votes due to ChangeCote error
2, Do not carry out update when handling DKG outcome
This shall be carried out AFTER handover completion
3, Do not promote elder when having enough elders
This is to reduce the DKG & voting workload. May not be necessary anymore with other fixes deployed.
4, Do not carry out relocation within the genesis section
The CI script currently doesn't support parsing relocated node info from logs
5, Remove incorrect cmds variable
That's a coding bug
=> fixes to resolve CI failures due to network startup problem

.github/workflows/merge.yml, Justfile
Enables the RPC service in the released `safenode` bin, as well as enabling CLI `node` subcommands for interacting with such service.
=> feat: enable RPC service in released safenode

sn_interface/src/network_knowledge/section_authority_provider.rs, sn_node/src/node/handover/handover_consensus.rs
Ensures that the fix in #2248 also applies during a split
=> fix(handover): check current elders against all pks in case of split

.github/workflows/merge.yml
removes the pre_job check and related job deps
this was not at all stable and proving to be more
pain than it was worth
=> ci: remove duplicate run skipping

sn_interface/src/lib.rs, sn_interface/src/op_cost/mod.rs, sn_node/src/node/context.rs, sn_node/src/node/error.rs, sn_node/src/node/flow_ctrl/tests/mod.rs, sn_node/src/node/messaging/client_msgs.rs, sn_node/src/node/mod.rs, sn_node/src/storage/mod.rs
This PR adds an algorithm to calculate a fee with supply/demand adjusting properties - although indirect and therefore arguably sluggish - based on:
1. Network size (contributing to the deflationary character of SNT).
2. Storage used.
3. Requirements for space margin (1/3).
4. Requirement for as low fee as possible for as long as possible.
(Point 3. and 4. are achieved by the specific design of the required tokens curve.)
***
To do transfers on the network, clients are required to pay a number of tokens as a fee. The fees are the source of rewards for Elders in a payment-network, which is essential to the network security as it gives incentive to node operators to run a node and handle the requests, thus allowing for the network to grow.
**NB 1**: This is not a replacement for a true …
=> feat(fees): impl supply/demand-adjusted fee
