.github/workflows/all_prs.yml

chore(ci): switch cargo udeps to use dedicated github action

---

.github/workflows/all_prs.yml
.github/workflows/e2e.yml
.github/workflows/pr_client.yml
.github/workflows/pr_messaging.yml
.github/workflows/pr_node.yml
.github/workflows/pr_routing.yml
examples/client_blob.rs
examples/config_handling.rs
src/client/client_api/blob_apis.rs
src/client/client_api/map_apis.rs
src/client/client_api/mod.rs
src/client/client_api/sequence_apis.rs
src/client/client_api/transfer_actor/balance_management.rs
src/client/client_api/transfer_actor/mod.rs
src/client/client_api/transfer_actor/simulated_payouts.rs
src/client/mod.rs

Ci update workflows

---

LICENSE
README.md

chore: update repo name in readme

---

.github/workflows/pr_client.yml
.github/workflows/pr_messaging.yml
.github/workflows/pr_node.yml
.github/workflows/pr_routing.yml

ci: allow all jobs to run, but only test with specific patterns

---

src/routing/routing_api/bootstrap/join.rs
src/routing/routing_api/core/anti_entropy.rs
src/routing/routing_api/core/messaging/handling/mod.rs

Cherry pick works of 
https://github.com/maidsafe/sn_routing/pull/2591
and
https://github.com/maidsafe/sn_routing/pull/2586

Cherry pick fixes

---

.github/workflows/bump_version.yml
.github/workflows/generate_dependency_graphs.yml
.github/workflows/main.yml
.github/workflows/tag_release.yml

ci: rename master->main workflow

---

.github/workflows/e2e.yml
Cargo.lock
Cargo.toml

fix: tie tokio to 1.6 for stability

---

src/client/client_api/blob_apis.rs
src/client/client_api/mod.rs
src/client/client_api/transfers/balance_management.rs
src/client/client_api/transfers/mod.rs

Put improvements

---

src/client/client_api/transfers/balance_management.rs
src/client/utils/test_utils/test_client.rs

Do not filter JoinRequest messages

---

Cargo.lock
src/node/bin/sn_node.rs

fix(node-bin): log the node's addr the network failed to connect to as part of the connectivity test

---

.github/workflows/e2e.yml
Cargo.lock
src/client/client_api/commands.rs
src/client/client_api/mod.rs
src/client/client_api/register_apis.rs
src/client/client_api/sequence_apis.rs
src/client/client_api/transfers/balance_management.rs
src/client/client_api/transfers/simulated_payouts.rs
src/client/connections/listeners.rs
src/client/connections/messaging.rs
src/client/connections/mod.rs
src/messaging/client/errors.rs
src/node/bin/sn_node.rs
src/node/error.rs
src/node/node_api/mod.rs

Ae for transfers

---

Cargo.lock
Cargo.toml
src/node/bin/sn_node.rs
src/node/error.rs
src/node/utils.rs

chore: make flexi-logger async

---

Cargo.lock
src/routing/network/mod.rs

fix: merge remote section info during Sync

---

Cargo.lock
Cargo.toml
src/client/client_api/map_apis.rs
src/client/client_api/sequence_apis.rs
src/client/client_api/transfers/balance_management.rs
src/node/bin/launch_network.rs
src/node/chunks/chunk_storage.rs
src/node/chunks/mod.rs
src/node/data_store/mod.rs
src/node/data_store/tests.rs
src/node/data_store/used_space.rs
src/node/metadata/elder_stores.rs
src/node/metadata/map_storage.rs
src/node/metadata/register_storage.rs
src/node/metadata/sequence_storage.rs
src/node/node_api/handle.rs
src/node/node_api/role/adult_role.rs

Fs async and test improvements

---

.github/workflows/e2e.yml
Cargo.lock
src/client/client_api/transfers/balance_management.rs

ci: split up e2etests, dont log so aggresively

---

src/transfers/wallet_replica.rs

Remove prints

---

Cargo.lock
src/node/error.rs
src/routing/core/msg_handling/mod.rs

chore: improve logging and error message

---

Cargo.lock

chore(deps): update qp2p version in lockfile

---

src/routing/core/msg_handling/mod.rs

fix: send back bounced message within SectionKnowledge

---

src/node/data_store/mod.rs
src/node/data_store/tests.rs
src/node/metadata/chunk_records.rs
src/node/metadata/elder_stores.rs
src/node/metadata/map_storage.rs
src/node/metadata/register_storage.rs
src/node/metadata/sequence_storage.rs
src/node/node_api/role/adult_role.rs

chore: simplify datastore w/r/t mutability

---

src/client/client_api/blob_apis.rs
src/client/connections/messaging.rs
src/client/utils/test_utils/mod.rs

fix(tests): add delay before reading a chunk write

---

src/dbs/event_store.rs
src/node/capacity/mod.rs
src/node/metadata/adult_liveness.rs
src/node/metadata/chunk_records.rs
src/node/metadata/elder_stores.rs
src/node/metadata/mod.rs
src/node/metadata/register_storage.rs
src/node/metadata/sequence_storage.rs

Removes mut references to chunk records at Elders.

feat(metadata): improve concurrency

---

examples/config_handling.rs
src/client/client_api/mod.rs
src/client/config_handler.rs
src/dbs/event_store.rs
src/dbs/mod.rs
src/node/bin/launch_network.rs
src/node/bin/sn_node.rs
src/node/config_handler.rs
src/node/metadata/map_storage.rs
src/node/metadata/register_storage.rs
src/node/metadata/sequence_storage.rs
src/node/node_api/mod.rs

chore: use tokio::fs

---

src/client/client_api/blob_storage.rs
src/client/connections/messaging.rs
src/client/connections/mod.rs
src/client/errors.rs
src/client/mod.rs
src/dbs/data_store/data.rs
src/dbs/data_store/mod.rs
src/dbs/data_store/to_db_key.rs
src/dbs/data_store/used_space.rs
src/dbs/encoding.rs
src/dbs/errors.rs
src/dbs/event_store.rs
src/dbs/mod.rs
src/node/metadata/mod.rs

- fbc1508f1 **fix(client): Fix a doc comment typo**
- f0e739d38 **refactor(client): Fix `unreachable_pub` lints**
This was mostly a case of updating method visibility to match their
types, with one case of unmerging a multi-item `use` (in
`src/client/mod.rs`).
- 4bf87c90f **refactor(dbs): Fix `unreachable_pub` lints**
This also affected a single method in `node` in order to prevent
'private type in public interface' errors.

Fix unreachable pub in client & dbs

---

Cargo.toml

feat: add client build feature to ignore igd on clients

---

src/node/event_mapping/client_msg.rs
src/node/metadata/chunk_records.rs
src/node/metadata/mod.rs
src/node/node_api/handle.rs
src/routing/core/comm.rs

fix: retain the original dst_location

---

.github/workflows/e2e.yml
examples/network_split.rs
src/bin/sn_node.rs
src/bin/testnet.rs
src/client/connections/messaging.rs
src/messaging/node/signed.rs
src/node/capacity/mod.rs
src/node/chunk_store/mod.rs
src/node/metadata/adult_liveness.rs
src/node/node_api/member_churn.rs
src/routing/core/bootstrap/join.rs
src/routing/core/signature_aggregator.rs
src/routing/routing_api/mod.rs
src/routing/routing_api/tests/mod.rs
src/types/keys/keypair.rs
src/types/register/reg_crdt.rs
src/url/mod.rs
src/url/url_parts.rs

fix: remove the backlog cache for bootstrapping node

---

src/client/client_api/blob_apis.rs
src/client/client_api/mod.rs
src/client/client_api/register_apis.rs
src/client/config_handler.rs
src/dbs/data_store/tests.rs
src/dbs/register_op_store.rs
src/node/state_db.rs
src/routing/cache/item.rs
src/routing/cache/mod.rs
src/routing/core/bootstrap/join.rs
src/routing/core/comm.rs
src/routing/routing_api/tests/mod.rs
src/routing/tests/bootstrap.rs
src/routing/tests/drop.rs
src/routing/tests/messages.rs

ci: use multi-threaded tests

---

src/client/client_api/commands.rs
src/client/connections/messaging.rs

Further down we just access the address, so that's all we need to
pass in.

fix: remove unneeded clone

---

Cargo.lock
src/types/keys/public_key.rs

fix: adjust for breaking change in blsttc

---

.github/workflows/e2e.yml
src/client/connections/messaging.rs

fix: remove un-necessary disconnection handler

---

.github/workflows/e2e.yml
src/client/client_api/blob_apis.rs
src/client/utils/test_utils/mod.rs
src/dbs/errors.rs
src/dbs/event_store.rs
src/dbs/kv_store/mod.rs
src/dbs/kv_store/tests.rs
src/dbs/kv_store/to_db_key.rs
src/messaging/authority.rs
src/routing/core/api.rs
src/routing/core/chunk_store/mod.rs
src/routing/core/enduser_registry.rs
src/routing/core/mod.rs
src/routing/core/msg_handling/data_msgs.rs
src/routing/core/msg_handling/mod.rs
src/routing/core/msg_handling/section_info.rs
src/routing/core/register_storage.rs
src/routing/routing_api/command.rs
src/routing/routing_api/dispatcher.rs
src/routing/routing_api/tests/mod.rs

Remove locking routing core on msgs

---

src/messaging/serialisation/wire_msg_header.rs

- 3507db02c **refactor(messaging): Use serde for wire message metadata**
Our wire message header begins with some metadata: the total header
length (inclusive of the metadata itself) and the protocol version.
These are (de)serialized with `(from_)to_be_bytes`.
This is exactly the format that `bincode` would serialize a struct of
two `u16`s, when configured to use big-endian and fixed-length encoding.
So, we can replace our hand-crafted, artisinal serialization code with
more straightforward serde calls, whilst maintaining the exact same
format.
Overall this is more code, due to the `HeaderMeta` struct and
`BINCODE_OPTS`, but the `from_bytes` and `write` methods are much
simpler.

refactor(messaging): Use serde for wire message metadata

---

src/routing/core/msg_handling/anti_entropy.rs

fix: avoid looping AntiEntropyDirect

---

examples/routing_stress.rs
src/messaging/location.rs
src/routing/core/bootstrap/join.rs
src/routing/core/bootstrap/relocate.rs
src/routing/core/delivery_group.rs
src/routing/core/messaging.rs
src/routing/core/msg_handling/anti_entropy.rs
src/routing/dkg/session.rs
src/routing/routing_api/tests/mod.rs

chore: remove DirectAndUnRouted dst location

---

src/routing/core/msg_handling/anti_entropy.rs
src/routing/core/msg_handling/mod.rs

- 4adb70428 **fix: Redirect service messages from adults to elders**
Previously, if an adult (non-elder) node received a `ServiceMsg` we
would silently ignore it. This commit changes the behaviour to instead
return an anti-entropy redirect to the client, redirecting them to the
current section's elders.
This might not be the desired long-term solution, since we don't really
want adults to be on the receiving end of messages from clients.

Redirect from adults

---

src/routing/core/msg_handling/service_msgs.rs

fix: full adults being chunk holders as well

---

src/messaging/serialisation/mod.rs
src/messaging/system/mod.rs
src/prefix_map/mod.rs
src/routing/core/messaging.rs
src/routing/core/mod.rs
src/routing/core/msg_handling/agreement.rs
src/routing/core/msg_handling/anti_entropy.rs
src/routing/core/msg_handling/bad_msgs.rs
src/routing/core/msg_handling/mod.rs
src/routing/core/msg_handling/update_section.rs
src/routing/messages/msg_authority.rs
src/routing/routing_api/command.rs
src/routing/routing_api/dispatcher.rs
src/routing/routing_api/tests/mod.rs
src/routing/section/mod.rs

No sync plz

---

src/routing/core/mod.rs
src/routing/core/msg_handling/agreement.rs
src/routing/core/msg_handling/anti_entropy.rs
src/routing/core/msg_handling/mod.rs
src/routing/core/msg_handling/update_section.rs
src/routing/routing_api/command.rs
src/routing/section/mod.rs

fix: AE-Update return earlier so when update isnt wanted do nothing.

---

src/client/connections/listeners.rs
src/routing/core/chunk_records.rs
src/routing/core/msg_handling/anti_entropy.rs
src/routing/core/msg_handling/mod.rs

fix: add missing await for liveness tracking.

---

src/prefix_map/mod.rs

chore: explain one case of untrusted proof_chain

---

src/bin/testnet.rs

fix: make DEFAULT_NODE_COUNT of testnet effective

---

src/routing/core/msg_handling/mod.rs
src/routing/routing_api/dispatcher.rs

- There were occurrences of the old naming (infrastructure msg).

chore: finish renaming to system msg

---

src/lib.rs

chore: fix logo url

---

src/node/config_handler.rs

feat: read genesis config from file if non provided

---

src/client/connections/listeners.rs
src/client/connections/messaging.rs

fix: query subset on AERedirect

---

src/routing/core/msg_handling/anti_entropy.rs

fix: check dst_name for self first

---

examples/network_split.rs

fix(example): remove deprecated arg

---

src/dbs/kv_store/used_space.rs

fix: avoid adding root_dir into used_space

---

Cargo.lock
Cargo.toml
src/client/client_api/blob_apis.rs
src/client/client_api/data/mod.rs
src/client/client_api/data/pac_man.rs

- `SecretKey` renamed to `DataMap`.

refactor: update for SE name change

---

.github/workflows/all_prs.yml
Cargo.lock
Cargo.toml
benches/upload_bytes.rs
src/client/client_api/blob_apis.rs
src/client/client_api/queries.rs
src/client/client_api/register_apis.rs
src/client/utils/mod.rs
src/client/utils/test_utils/mod.rs

Backoff for retries

---

src/routing/core/mod.rs
src/routing/routing_api/dispatcher.rs

chore: log probe errors, remove unneeded async

---

src/routing/core/api.rs
src/routing/core/mod.rs
src/routing/core/msg_handling/agreement.rs

feat: wrap SplitBarrier in arc/rwlock for better concurrency

---

src/routing/core/msg_handling/dkg.rs
src/routing/core/msg_handling/mod.rs
src/routing/dkg/session.rs
src/routing/dkg/voter.rs
src/routing/routing_api/command.rs
src/routing/routing_api/dispatcher.rs

feat: make DKG voter concurrent and cloneable

---

src/routing/core/msg_handling/anti_entropy.rs

fix: return ae retry when unkown key is provided

---

src/routing/core/api.rs
src/routing/core/chunk_records.rs
src/routing/core/connectivity.rs
src/routing/core/messaging.rs
src/routing/core/mod.rs
src/routing/core/msg_handling/agreement.rs
src/routing/core/msg_handling/anti_entropy.rs
src/routing/core/msg_handling/dkg.rs
src/routing/core/msg_handling/join.rs
src/routing/core/msg_handling/mod.rs
src/routing/core/msg_handling/relocation.rs
src/routing/routing_api/command.rs
src/routing/routing_api/dispatcher.rs
src/routing/routing_api/mod.rs
src/routing/routing_api/tests/mod.rs
src/routing/section/section_keys.rs

Feat non blocking section_keys

---

src/client/client_api/blob_apis.rs

The included test cases in `seek_in_data` were sequential. 
Running them in parallel improved speed ~`550%` locally (12 threads).
NB: The improvement will be less notable on CI while running E2E on 2 core machines.

refactor(test): improve seek_in_data test speed

---

src/routing/core/messaging.rs
src/routing/core/mod.rs
src/routing/core/msg_handling/agreement.rs

fix: using prefix name as dst_location

---

.github/workflows/pr_tests.yml
Cargo.lock
src/client/client_api/blob_apis.rs
src/client/client_api/mod.rs
src/client/client_api/queries.rs
src/client/client_api/register_apis.rs
src/client/config_handler.rs
src/client/connections/listeners.rs
src/client/connections/messaging.rs
src/client/connections/mod.rs
src/client/errors.rs
src/client/utils/test_utils/mod.rs
src/client/utils/test_utils/test_client.rs
src/routing/routing_api/dispatcher.rs

chore: remove self from spans, start test spans after logging

---

.github/workflows/arm_tests.yml
.github/workflows/pr_tests.yml
Cargo.lock
Cargo.toml
src/client/client_api/blob_apis.rs
src/client/connections/messaging.rs
src/lib.rs
src/routing/core/chunk_records.rs
src/routing/core/chunk_store/mod.rs
src/routing/core/msg_handling/mod.rs
src/routing/core/msg_handling/service_msgs.rs
src/routing/log_markers.rs
src/routing/mod.rs
src/testnet_assert/mod.rs

Idea here is basically to provide some helper for grepping the testnet logs for certain things.

Feat enable network log asserts

---

src/client/utils/test_utils/test_client.rs

refactor(log): add time to log messages

---

.github/workflows/pr_tests.yml
src/client/client_api/blob_apis.rs
src/client/client_api/commands.rs
src/client/client_api/mod.rs
src/client/client_api/register_apis.rs
src/client/connections/listeners.rs
src/client/connections/messaging.rs
src/client/connections/mod.rs
src/client/utils/test_utils/test_client.rs
src/prefix_map/mod.rs
src/routing/core/msg_handling/mod.rs
src/routing/core/msg_handling/service_msgs.rs
src/routing/log_markers.rs

Adds regsiter network asserts
Adds small delay on `send_cmd` relateive to to `query_timeout` to wait for full AE flows eg.

Feat reg net assert

---

src/routing/core/bootstrap/join.rs

fix: bootstrap proper dst_location and self prefix

---

.github/workflows/digital_ocean_testnet.yml

this was previously done by commenting launch-testnet when approving a PR

feat(actions): run Digital Ocean testnet action on PRs with approval

---

src/messaging/system/section/mod.rs
src/routing/core/connectivity.rs
src/routing/core/messaging.rs
src/routing/core/msg_handling/agreement.rs
src/routing/core/msg_handling/dkg.rs
src/routing/core/msg_handling/join.rs
src/routing/core/msg_handling/relocation.rs
src/routing/core/msg_handling/service_msgs.rs
src/routing/core/msg_handling/update_section.rs
src/routing/relocation.rs
src/routing/routing_api/dispatcher.rs
src/routing/routing_api/mod.rs
src/routing/section/mod.rs
src/routing/section/section_peers.rs

chore: make section peers concurrent by using Arc<DashMap>

---

Cargo.lock
Cargo.toml
src/bin/log_cmds_inspector.rs

Tool to analyse `routing::Command`s trace logs in search of not completed commands. It can be used by running it against local testnet logs, e.g. `cargo run --release --bin log_cmds_inspector -- ~/.safe/node/local-test-network`, it searches in all logs for each individual node.
Example output when it detects some inconsistencies:
```
$ cargo run --release --bin log_cmds_inspector -- ~/.safe/node/local-test-network
Inspecting testnet logs folder: ~/.safe/node/local-test-network/
-------------------------
Inspecting node's folder: ~/.safe/node/local-test-network/sn-node-38
-------------------------
Inspecting log file: ~/.safe/node/local-test-network/sn-node-38/sn_node.log.2021-10-14-15
Node is Elder?: false
Commands Spawned: 366, Started: 366, Succeeded: 366, Failed: 0
Commands handled …
```

Chore log analysis tool

---

.github/workflows/sn_pr_tests.yml
sn/src/lib.rs
sn/src/prefix_map/stats.rs
sn/src/routing/log_markers.rs
sn/src/testnet_grep/mod.rs

test: update elder count check to be general one split health check

---

sn/Cargo.toml
sn_api/Cargo.toml
sn_cli/Cargo.toml
sn_cmd_test_utilities/Cargo.toml

- 5dafa23a6 **chore: bump rust edition**
The few breaking changes in this edition did not affect us.

chore: bump rust edition

---

sn/src/routing/core/back_pressure.rs

chore: reduce the report check interval

---

sn/src/routing/core/msg_handling/anti_entropy.rs

fix: match on name

---

sn/README.md

It looks like this was missed in #595.

Fix crates.io badge

---

Cargo.lock
sn/src/messaging/serialisation/wire_msg.rs
sn/src/routing/core/msg_handling/mod.rs
sn/src/routing/network_knowledge/mod.rs

chore: reduce clone and lock during message handling

---

sn/src/routing/core/msg_handling/anti_entropy.rs

fix: update logs during AEUpdate

---

.github/workflows/sn_pr_tests.yml
resources/scripts/has_split.sh
resources/scripts/network_is_ready.sh
resources/scripts/network_is_ready_cli.sh
resources/scripts/network_is_ready_win.sh
sn/benches/upload_bytes.rs
sn/examples/client_blob.rs
sn/examples/network_split.rs
sn/src/client/client_api/blob_apis.rs
sn/src/client/client_api/mod.rs
sn/src/client/config_handler.rs
sn/src/client/connections/listeners.rs
sn/src/client/mod.rs
sn/src/client/utils/test_utils/test_client.rs
sn/src/lib.rs
sn/src/routing/core/bootstrap/join.rs
sn/src/routing/core/mod.rs
sn/src/routing/core/msg_handling/agreement.rs
sn/src/routing/core/msg_handling/mod.rs
sn/src/routing/log_markers.rs
sn/src/routing/network_knowledge/section_keys.rs
sn/src/routing/routing_api/command.rs
sn/src/routing/routing_api/dispatcher.rs
sn/src/routing/routing_api/tests/mod.rs
sn/src/testnet_grep/mod.rs
sn_api/src/app/safe_client.rs

chore: remove blocking/non blocking msg handling distinction

---

sn/src/client/config_handler.rs

fix: client config test timeout/keepalive needed updating

---

sn/src/routing/core/bootstrap/join.rs
sn/src/routing/core/bootstrap/mod.rs
sn/src/routing/core/bootstrap/relocate.rs

fix: refactor the Join process regarding used_recipients

---

.github/workflows/sn_pr_tests.yml
resources/scripts/api_tests.sh
resources/scripts/has_split.sh
sn_api/src/app/multimap.rs
sn_api/src/app/register.rs
sn_api/src/app/safe_client.rs

Ci fix api test setup

---

sn/src/bin/sn_node.rs
sn/src/bin/testnet.rs

This also prints out the log dir path when a node fails to start.

feat(testnet): allow to change the default interval for testnet nodes

---

sn/src/routing/core/mod.rs
sn/src/routing/core/msg_handling/join.rs

Also increases concurrent joins allowed

chore: reuse join permits for relocated nodes too.

---

.github/workflows/sn_pr_tests.yml
sn/src/bin/testnet.rs

ci: increase network startup interval

---

sn/src/routing/core/comm.rs

- cc061379a **refactor(sn): retry on connection loss of reused connection**
The `routing::Comm::send` method uses an instance of `ConnectedPeers` to
reuse existing connections. This saves a lot of connections during busy
exchanges between few nodes, such as DKG. However, should the connection
retrieved for reuse have become invalid (e.g. closed by the peer or
timed out), that recipient would be recorded as failed.
Since connection timeouts are to be expected, particularly for stored
connections with keep-alives disabled as in `ConnectedPeers`, it makes
sense to retry the recipient with a fresh connection before declaring
it failed.
The implementation has been bolted on to the existing `send` mechanism.
The `send` closure will return an additional boolean indicating whether
or not the …

refactor(sn): retry on connection loss of reused connection

---

.github/workflows/arm_tests.yml
.github/workflows/benchmarks.yml
.github/workflows/sn_client_tests_against_do_testnet.yml
.github/workflows/sn_pr_checks.yml
.github/workflows/sn_pr_tests.yml

refactor(actions): use rust-cache action for smarter caching of rust builds

---

sn/src/routing/core/bootstrap/join.rs

fix: during bootstrap, handling the case prefix_map was loaded

---

sn/src/node/event_mapping/mod.rs
sn/src/node/network.rs
sn/src/routing/core/mod.rs
sn/src/routing/core/msg_handling/agreement.rs
sn/src/routing/routing_api/dispatcher.rs
sn/src/routing/routing_api/tests/mod.rs

More matches

---

resources/scripts/bump_version.sh

We need to determine if each individual crate has changes and then only run smart-release with the
crates that do have changes. The way it behaves varies based on whether there's changes to just one
crate, or many, and which crates you specify in the command.
It's a shame you can't just run it without a crate name and have the tool determine which of the
crates have changes. I wonder if this is due to the fact that the safe_network crate doesn't
correspond to the 'sn' directory name, but not sure.

ci: check each crate for changes individually

---

resources/scripts/bump_version.sh

I had so many 'fix' branches, I think I accidentally pushed changes to remote before I was ready,
then I got some kind of conflict when I was rebasing. Despite taking everything from the 'right'
side, I appear to have lost some changes. Not sure exactly what happened. Luckily the saved '.orig'
file had the changes that were overwritten.

ci: accept correct changes for version bump

---

.github/workflows/bump_version.yml

This one is newly generated and associated with a user that has permissions on the repo.

ci: try a new token

---

.github/workflows/sn_pr_tests.yml
Cargo.lock
sn/Cargo.toml
sn/proptest-regressions/routing/dkg/session.txt
sn/src/lib.rs
sn/src/messaging/system/mod.rs
sn/src/routing/core/bootstrap/join.rs
sn/src/routing/core/msg_handling/dkg.rs
sn/src/routing/core/msg_handling/mod.rs
sn/src/routing/dkg/session.rs
sn/src/routing/dkg/voter.rs
sn/src/routing/node.rs
sn/src/routing/routing_api/tests/mod.rs

Implement AE for DKG messages as well

---

.github/workflows/bump_version.yml

I want to check the user being assigned to the version bump commit and also exactly which user is performing the push.

ci: more debugging text to try to discern problem

---

.github/workflows/sn_client_tests_against_do_testnet.yml

this prevents the approving of individual steps of the testnet action

refactor(actions): trigger DigitalOcean testnet on labels instead

---

sn/src/routing/core/bootstrap/join.rs

feat: deduce expected_prefix from expected_age

---

Cargo.lock
sn/Cargo.toml
sn/src/routing/core/msg_handling/mod.rs
sn/src/routing/dkg/session.rs
sn/src/routing/dkg/voter.rs

Rebased avoid broadcast

---

sn/src/bin/testnet.rs
sn/src/routing/core/bootstrap/join.rs
sn/src/routing/core/msg_handling/agreement.rs

chore: minor changes

---

.github/README.md

If we want to document any of the other workflows, we could do so in this README.

docs: describe the new release process

---

sn/src/routing/core/mod.rs
sn/src/types/utils.rs

chore: spawn writing prefix_map to disk as separate thread

---

sn/src/client/connections/listeners.rs
sn/src/client/connections/messaging.rs
sn_cli/src/cli.rs
sn_cli/src/subcommands/keys.rs

BREAKING CHANGE: this also temporarily removes some payment flags/args from CLI commands
since they are not yet supported by the network without payments.

chore(client): include remote addrs in listerners threads log entries

---

resources/scripts/has_split.sh
sn/src/lib.rs
sn/src/routing/core/mod.rs
sn/src/routing/core/msg_handling/anti_entropy.rs
sn/src/routing/core/msg_handling/dkg.rs
sn/src/routing/core/msg_handling/mod.rs
sn/src/routing/log_markers.rs
sn/src/routing/network_knowledge/mod.rs

fix: reduce backoff time; avoid start DKG shrink elders

---

.github/workflows/sn_pr_tests.yml
sn/src/bin/testnet.rs
sn/src/messaging/system/join.rs
sn/src/routing/core/bootstrap/join.rs
sn/src/routing/core/msg_handling/join.rs
sn/src/routing/dkg/session.rs
sn/src/routing/dkg/voter.rs

Remove DkgUnderway, Aggregate join sigs per key

---

sn/src/routing/core/msg_handling/dkg.rs
sn/src/routing/core/msg_handling/mod.rs

fix: avoid network_knowledge loopup when sending DkgRetry or DkgSessionInfo

---

sn/src/client/client_api/mod.rs
sn/src/client/connections/messaging.rs
sn/src/client/connections/mod.rs
sn/src/dbs/event_store.rs
sn/src/messaging/system/node_msgs.rs
sn/src/node/logging/system.rs
sn/src/node/node_api/mod.rs
sn/src/routing/core/msg_count.rs
sn/src/routing/core/register_storage.rs
sn/src/routing/relocation.rs
sn/src/routing/routing_api/event.rs
sn_api/src/app/files/mod.rs
sn_api/src/url/url_parts.rs
sn_cli/src/subcommands/files.rs

chore: clippy tidyup for rust 1.57

---

sn/src/routing/dkg/voter.rs

fix: aovid overwrite pervious session by  accident

---

sn/src/bin/sn_node.rs

fix: keep trying even with connection error w/ always-joinable flag

---

sn_api/src/app/multimap.rs
sn_api/src/app/nrs/mod.rs
sn_api/src/app/nrs/nrs_map.rs
sn_api/src/errors.rs

- NRS with multimaps instead or registers, saving both network space and ops
- restore multimap remove and tombstones
- manage register fork resolution and add informative errors

Nrs on multimap

---

resources/scripts/has_split.sh
sn/src/messaging/system/join.rs
sn/src/messaging/system/join_as_relocated.rs
sn/src/messaging/system/mod.rs
sn/src/messaging/system/section/mod.rs
sn/src/routing/core/api.rs
sn/src/routing/core/bootstrap/join.rs
sn/src/routing/core/bootstrap/relocate.rs
sn/src/routing/core/msg_handling/join.rs
sn/src/routing/core/msg_handling/mod.rs
sn/src/routing/core/msg_handling/relocation.rs
sn/src/routing/log_markers.rs
sn/src/routing/network_knowledge/mod.rs
sn/src/routing/network_knowledge/section_peers.rs
sn/src/routing/routing_api/command.rs
sn/src/routing/routing_api/dispatcher.rs

fix: complete the relocation flow

---

sn/src/routing/core/bootstrap/join.rs
sn/src/routing/core/msg_handling/join.rs

fix: avoid change name by mistake when Join

---

sn/src/client/client_api/blob_apis.rs
sn/src/client/client_api/data/mod.rs
sn/src/client/client_api/mod.rs
sn/src/client/config_handler.rs
sn/src/client/connections/messaging.rs
sn/src/client/errors.rs

chore: remove Generic client error

---

.github/workflows/sn_pr_tests.yml

ci: split out various jobs into their own runs

---

.github/workflows/sn_pr_tests.yml
sn/src/messaging/system/agreement.rs
sn/src/routing/core/msg_handling/agreement.rs
sn/src/routing/core/msg_handling/dkg.rs
sn/src/routing/core/msg_handling/proposals.rs
sn/src/routing/core/proposal.rs
sn/src/routing/core/split_barrier.rs
sn/src/routing/log_markers.rs
sn/src/routing/network_knowledge/mod.rs
sn/src/routing/routing_api/command.rs
sn/src/routing/routing_api/dispatcher.rs
sn/src/routing/routing_api/tests/mod.rs

chore: rename enum variants for improved clarity on flows

---

sn/src/routing/relocation.rs
sn/src/routing/routing_api/tests/mod.rs

feat: limit the relocations at one time

---

.github/workflows/sn_pr_tests.yml
sn/src/node/node_api/mod.rs
sn/src/routing/network_knowledge/mod.rs

Ci improve runs

---

sn/src/routing/core/chunk_store/mod.rs
sn/src/routing/core/msg_handling/mod.rs

chore(sn): add more logs regarding storage levels

---

.github/workflows/release.yml

fix: only use self hosted for ubuntu release

---

.github/workflows/release.yml

ci: remove self hosted runner from release

---

Cargo.lock
sn/CHANGELOG.md
sn/Cargo.toml
sn_api/Cargo.toml

chore(release): safe_network-0.51.6

---

sn/src/client/client_api/blob_apis.rs
sn/src/client/client_api/data/pac_man.rs
sn/src/client/connections/messaging.rs
sn/src/client/errors.rs
sn_api/src/app/files/file_system.rs
sn_api/src/app/files/files_map.rs
sn_api/src/app/files/mod.rs

BREAKING CHANGE: changes in Error types definitions which are part of the public API.

refactor(client): minor refactor to error types definitions

---

.github/workflows/sn_pr_tests.yml

fix: enable log from bin/sn_node.rs

---

.github/workflows/sn_pr_tests.yml
sn_api/src/app/files/mod.rs

fix: enable logging from api tests; resolve one failing test

---

.github/workflows/bors.yml
.github/workflows/sn_client_tests_against_do_testnet.yml
.github/workflows/sn_pr_tests.yml
bors.toml

ci: tweak bors.toml to only require unit and e2e tests for now

---

sn/src/node/routing/core/register_storage.rs

Substract space from used_space on register delete

---

sn/src/types/register/reg_crdt.rs
sn_api/src/app/files/mod.rs
sn_api/src/app/nrs/mod.rs
sn_api/src/app/safe_client.rs
sn_api/src/safeurl/mod.rs
sn_api/src/safeurl/version_hash.rs

chore: log EntryHash with XorName

---

sn/src/lib.rs

fix: set DEFAULT_CHUNK_COPY_COUNT to 4 once again

---

sn/src/types/register/reg_crdt.rs
sn_api/src/safeurl/version_hash.rs

fix: VersioinHash use Display for encode

---

.github/workflows/bors.yml
.github/workflows/sn_pr_tests.yml

ci: use self hosted ubuntu runners

---

.github/workflows/sn_pr_tests.yml
resources/scripts/all_nodes_joined.sh
resources/scripts/wait_for_nodes_to_join.sh
sn/src/bin/sn_node.rs
sn/src/client/client_api/mod.rs
sn/src/client/connections/messaging.rs
sn/src/client/utils/test_utils/test_client.rs
sn/src/node/routing/core/bootstrap/join.rs
sn/src/types/log_markers.rs

Before a client can perform put/query we shoud have at least one full
section's info to work properly

fix(sn/client): wait for a full section's info

---

Cargo.lock
sn/src/messaging/system/mod.rs
sn/src/node/routing/api/tests/mod.rs
sn/src/node/routing/core/messaging.rs
sn/src/node/routing/core/msg_handling/anti_entropy.rs
sn/src/node/routing/core/msg_handling/mod.rs

BREAKING CHANGE: change in messaging type definition.

chore(messaging): making section members list non optional in AntiEntropyUpdate message type

---

sn/src/client/client_api/file_apis.rs

tests: ignore many_client tests

---

sn/src/node/routing/core/msg_handling/anti_entropy.rs
sn/src/node/routing/core/msg_handling/update_section.rs

Also gives the method a better name.

chore: lessen nesting and indentation

---

sn/src/client/client_api/file_apis.rs
sn/src/client/client_api/mod.rs
sn/src/client/connections/listeners.rs
sn/src/client/connections/messaging.rs
sn/src/client/connections/mod.rs
sn/src/client/errors.rs

Client tracks failed conns to try again

---

.github/workflows/sn_pr_tests.yml

ci: use normal ubuntu for e2e; add e2e-split with self-hosted

---

sn/src/client/client_api/mod.rs
sn/src/client/client_api/register_apis.rs
sn/src/client/connections/listeners.rs
sn/src/client/connections/messaging.rs
sn/src/client/connections/mod.rs
sn/src/client/errors.rs
sn/src/messaging/data/mod.rs
sn/src/messaging/msg_id.rs
sn/src/messaging/system/node_msgs.rs
sn/src/node/core/data_records/mod.rs
sn/src/node/core/msg_handling/mod.rs
sn/src/node/core/msg_handling/service_msgs.rs

Closes https://github.com/maidsafe/safe_network/issues/909

send CmdAck for client cmd during test

---

sn/src/client/client_api/mod.rs
sn/src/client/client_api/register_apis.rs
sn/src/client/connections/listeners.rs
sn/src/client/connections/messaging.rs
sn/src/client/connections/mod.rs
sn/src/client/errors.rs
sn/src/messaging/data/mod.rs
sn/src/messaging/msg_id.rs
sn/src/messaging/system/node_msgs.rs
sn/src/node/core/data_records/mod.rs
sn/src/node/core/msg_handling/mod.rs
sn/src/node/core/msg_handling/service_msgs.rs

DO NOT MERGE for testing logs only

---

.github/workflows/bors.yml
.github/workflows/sn_pr_tests.yml
sn/src/client/client_api/file_apis.rs
sn/src/client/connections/listeners.rs
sn/src/client/connections/messaging.rs
sn/src/messaging/data/mod.rs
sn/src/messaging/data/query.rs
sn/src/messaging/data/register.rs
sn/src/messaging/system/node_msgs.rs
sn/src/node/core/data_records/mod.rs
sn/src/node/core/liveness_tracking.rs
sn/src/node/core/mod.rs
sn/src/node/core/msg_handling/service_msgs.rs

Fix : dont map pending reqs by data address

---

.github/workflows/bors.yml
.github/workflows/sn_pr_tests.yml
sn/src/client/connections/messaging.rs
sn/src/messaging/system/join.rs
sn/src/node/core/api.rs
sn/src/node/core/bootstrap/join.rs
sn/src/node/core/msg_handling/mod.rs

Fixing ci failures

---

.github/workflows/bors.yml
bors.toml

Ci bors timeout

---

sn/CHANGELOG.md
sn/benches/upload_bytes.rs
sn/examples/client_files.rs
sn/examples/network_split.rs
sn/examples/routing_stress.rs
sn/src/client/client_api/commands.rs
sn/src/client/client_api/file_apis.rs
sn/src/client/client_api/mod.rs
sn/src/client/client_api/queries.rs
sn/src/client/config_handler.rs
sn/src/client/connections/listeners.rs
sn/src/client/connections/messaging.rs
sn/src/client/connections/mod.rs
sn/src/client/mod.rs
sn/src/client/utils/test_utils/test_client.rs
sn/src/messaging/location.rs
sn/src/node/api/command.rs
sn/src/node/api/dispatcher.rs
sn/src/node/api/mod.rs
sn/src/node/core/api.rs
sn/src/node/core/data_records/mod.rs
sn/src/node/core/data_storage/mod.rs
sn/src/node/core/msg_handling/mod.rs
sn/src/node/core/msg_handling/service_msgs.rs
sn/src/node/core/msg_handling/update_section.rs
sn/src/types/log_markers.rs
sn_api/src/app/mod.rs
sn_api/src/authenticator/mod.rs
sn_cli/src/cli.rs

Cmd retries

---

bors.toml

- requires PRs are reviews
- does not squash commits
- does not merge with relevant label

ci: bors config updated

---

.github/workflows/sn_pr_tests.yml
sn/src/client/client_api/cmds.rs
sn/src/client/client_api/mod.rs
sn/src/client/config_handler.rs
sn/src/client/connections/listeners.rs
sn/src/client/connections/messaging.rs
sn/src/client/connections/mod.rs
sn/src/client/mod.rs
sn/src/client/utils/test_utils/test_client.rs
sn/src/node/core/bootstrap/join.rs
sn/src/node/core/comm.rs
sn/src/node/core/msg_handling/anti_entropy.rs
sn/src/node/network_knowledge/mod.rs

Update client messaging

---

.github/workflows/benchmarks.yml
.github/workflows/bors.yml
.github/workflows/daily_droplet_run.yml
.github/workflows/sn_client_tests_against_do_testnet.yml
.github/workflows/sn_pr_tests.yml
Cargo.lock
resources/scripts/network_is_ready.sh
sn/Cargo.toml
sn/examples/network_split.rs
sn/src/bin/sn_node.rs
sn/src/bin/testnet.rs
sn/src/client/config_handler.rs
sn/src/client/connections/messaging.rs
sn/src/messaging/sap.rs
sn/src/node/api/mod.rs
sn/src/node/core/data/records/mod.rs
sn/src/node/core/messaging/handling/agreement.rs
sn/src/node/core/messaging/handling/service_msgs.rs
sn/src/node/network_knowledge/section_authority_provider.rs

Increases wait for acks slightly.

chore: tweak command ack wait and interval looping.

---

.github/workflows/bors.yml
.github/workflows/sn_pr_tests.yml

Reduce ci client logging

---

sn_cli/README.md

Several changes were made to bring the user guide up-to-date:
* Move the XorUrl section to near the top of the document, below the network setup section. I done
this because I think it makes sense to explain the URL concept early, since it's used by every
command.
* Add a new section on Keys, where it's relevant to current network functionality. The previous Keys
documentation was removed because it referred to out-of-date features.
* Re-write the NRS, Cat and Dog documentation to make it a bit leaner.
* Remove the section on shell completions. I'm going to come back to this very shortly and possibly
include the completions to install them along with the application.
* Remove links to the 'Safe Dev Hub' from the Further Help section.
The new sections have been written with a line length …

docs: further updates for cli user guide

---

Cargo.lock
sn/Cargo.toml
sn/src/bin/sn_node.rs
sn/src/messaging/authority.rs
sn/src/messaging/msg_kind.rs
sn/src/messaging/serialisation/mod.rs
sn/src/node/core/messaging/handling/mod.rs
sn/src/node/logging/mod.rs
sn/src/node/messages/msg_authority.rs
sn/src/types/keys/signature.rs

chore(refactor) Update deps, ED node key rename 
Updated dependencies and removed a test that no longer is valid (signature format test). Serde now reportedly much faster but I have not benchmarked that. Also renamed node: public_key to node_ed_pk tp make it more explicit and not to be confused with the PublicKey type.

Naming refactor

---

README.md
sn/README.md

chore(docs): Add testing documentation

---

sn/src/bin/log_cmds_inspector.rs
sn/src/dbs/event_store.rs
sn/src/node/core/data/storage/registers.rs
sn/src/node/network_knowledge/mod.rs
sn_api/src/safeurl/mod.rs
sn_cli/tests/cli_files.rs

chore: changes to appease clippy 1.59

---

Cargo.lock
sn/src/node/api/cmds.rs
sn/src/node/api/dispatcher.rs
sn/src/node/api/tests/mod.rs
sn/src/node/core/messaging/handling/mod.rs
sn_api/src/app/files/mod.rs
sn_api/src/app/nrs/mod.rs
sn_api/src/app/resolver/mod.rs

chore(refactor): remove unneeded HandleSystemMsg command

---

sn/src/node/core/messaging/handling/anti_entropy.rs
sn/src/types/prefix_map/mod.rs

Close https://github.com/maidsafe/safe_network/issues/1057

feat: prune parent whenever a child inserted

---

sn/src/node/logging/mod.rs

Superseding https://github.com/maidsafe/safe_network/pull/1044.
Thanks for the suggestions @Thierry61 :)

chore: make resource logging consistent

---

Cargo.lock
log_cmds_inspector/Cargo.toml
sn/CHANGELOG.md
sn/Cargo.toml
sn/src/node/api/dispatcher.rs
sn/src/node/core/messaging/handling/service_msgs.rs
sn/src/node/core/mod.rs
sn_api/CHANGELOG.md
sn_api/Cargo.toml
sn_cli/CHANGELOG.md
sn_cli/Cargo.toml
sn_cmd_test_utilities/Cargo.toml
sn_dysfunction/CHANGELOG.md
sn_dysfunction/src/connections.rs
sn_dysfunction/src/detection.rs
sn_dysfunction/src/lib.rs
sn_dysfunction/src/network_knowledge.rs

Feat more dysfunction improvement

---

resources/scripts/insert_changelog_entry.py
sn_dysfunction/CHANGELOG.md

Fixes a little bug that was introduced for release process.
Also contains a manual release commit to hopefully get the release workflow to run again.

fix: add missing argument to function call

---

.github/workflows/scheduled_release_run.yml
sn/src/node/api/mod.rs
sn/src/node/core/mod.rs

Chore debug promotion

---

sn/src/node/network_knowledge/mod.rs

fix: adult shall update to new SAP

---

.github/workflows/README.md

I think this covers everything in the process. It's based on a review of df66875627aa41d06b7613085f05a97187c7175d, which was the addition of the `sn_dysfunction` crate.

docs: adding a new crate to release process

---

.github/workflows/release.yml
resources/scripts/bump_version.sh
resources/scripts/get_release_description.sh
resources/scripts/insert_changelog_entry.py
resources/scripts/output_versioning_info.sh
sn_interface/CHANGELOG.md
sn_interface/README.md

sn_interface release changes

---

.github/workflows/benchmarks_pages.yml

Removes unneeded mac/win conditionals. Updates bench command

ci: tweaks to github-pages benchmark workflow.

---

.github/workflows/benchmark_prs.yml
.github/workflows/benchmarks_pages.yml

Chore bench teaks

---

.github/workflows/benchmarks_pages.yml

ci: another git hook removal attempt

---

sn/benches/upload_bytes.rs

ci(bench): Increase target time. Add upload only benches

---

sn/benches/upload_bytes.rs

ci(bench): fix upload only clippy

---

.github/workflows/daily_droplet_run.yml

ci: remove sn working dir from droplet run after sn_client/node refactor

---

resources/jq-filters/README.md
resources/scripts/bump_version.sh
sn_node/examples/routing_minimal.rs
sn_node/src/bin/sn_node.rs
testnet/bin.rs

fix: update some instances of safe_network->sn_node

---

sn_cli/src/subcommands/networks.rs
sn_node/examples/config_handling.rs
sn_node/examples/routing_minimal.rs
sn_node/examples/routing_stress.rs
sn_node/src/node/cfg/config_handler.rs
sn_node/src/node/mod.rs

- This also removes some outdated warning message shown by CLI.

chore(node): change default node max cpacity to 10GB

---

sn_interface/Cargo.toml
sn_interface/src/messaging/auth_kind.rs
sn_interface/src/messaging/data/cmd.rs
sn_interface/src/messaging/data/query.rs
sn_interface/src/messaging/serialisation/mod.rs
sn_interface/src/messaging/serialisation/wire_msg.rs
sn_interface/src/messaging/system/mod.rs
sn_interface/src/messaging/system/node_msgs.rs

Feat interface service flag

---

sn_node/src/node/core/messaging/handling/membership.rs
sn_node/src/node/membership/mod.rs

The membership was requesting AE whenever we hit an error when processing a vote. This can lead to an infinite loop if the error is not related to lacking information:
1. node A sends bad vote to B.
2. B processes bad vote and returns error and B requests AE from A
3. node A processes the AE request and re-sends the bad vote to B
4. goto 1.
Fix is to only request AE when we are in the wrong generation.

fix(membership): avoid AE loop by being judicious with AE requests

---

.github/workflows/sn_pr_tests.yml
sn_client/src/api/queries.rs
sn_interface/src/messaging/system/agreement.rs
sn_interface/src/network_knowledge/mod.rs
sn_node/src/bin/sn_node.rs
sn_node/src/node/api/cmds.rs
sn_node/src/node/api/dispatcher.rs
sn_node/src/node/core/connectivity.rs
sn_node/src/node/core/messaging/handling/agreement.rs
sn_node/src/node/core/messaging/handling/dkg.rs
sn_node/src/node/core/messaging/handling/handover.rs
sn_node/src/node/core/messaging/handling/mod.rs
sn_node/src/node/core/messaging/handling/proposals.rs
sn_node/src/node/core/messaging/sending/handover.rs
sn_node/src/node/core/mod.rs
sn_node/src/node/core/proposal.rs
sn_node/src/node/core/split_barrier.rs
sn_node/src/node/dkg/session.rs
sn_node/src/node/dkg/voter.rs
sn_node/src/node/handover/handover_consensus.rs
testnet/bin.rs

Dkg generations

---

.github/workflows/sn_pr_tests.yml
sn_client/src/api/queries.rs
sn_client/src/connections/messaging.rs
sn_interface/src/lib.rs
sn_interface/src/messaging/serialisation/mod.rs
sn_interface/src/messaging/system/mod.rs
sn_interface/src/network_knowledge/mod.rs
sn_interface/src/network_knowledge/prefix_map/mod.rs
sn_interface/src/network_knowledge/section_authority_provider.rs
sn_interface/src/types/log_markers.rs
sn_node/src/node/api/tests/mod.rs
sn_node/src/node/core/messaging/handling/agreement.rs
sn_node/src/node/core/messaging/handling/handover.rs
sn_node/src/node/core/messaging/handling/mod.rs
sn_node/src/node/core/messaging/sending/dkg_start.rs
sn_node/src/node/core/messaging/sending/handover.rs
sn_node/src/node/core/mod.rs
sn_node/src/node/dkg/session.rs
sn_node/src/node/dkg/voter.rs
sn_node/src/node/error.rs
sn_node/src/node/handover/errors.rs
sn_node/src/node/handover/handover_consensus.rs
sn_node/src/node/handover/mod.rs
sn_node/src/node/mod.rs

Handover [W/o generation work]

---

.github/workflows/sn_pr_tests.yml

I transferred this action from my own personal namespace to the `maidsafe` organisation.

chore: use the nextest action from maidsafe org

---

sn_interface/src/types/log_markers.rs
sn_node/src/node/core/messaging/handling/agreement.rs

chore: add ProposalAgreed log marker

---

README.md
sn_node/src/node/api/dispatcher.rs

In addition removed unneeded map_err

docs: Add recursive flag to rm of dir

---

.github/workflows/sn_pr_tests.yml
resources/scripts/api_tests.sh

Ci remove query limit

---

sn_node/src/node/core/relocation.rs

feat: sort relocate candidates by distance to the churn_id

---

log_cmds_inspector/bin.rs
sn_node/src/node/core/comm/mod.rs

Tidy cmd insp

---

.github/workflows/sn_pr_tests.yml
sn_interface/src/messaging/system/agreement.rs
sn_interface/src/network_knowledge/mod.rs
sn_node/src/node/api/cmds.rs
sn_node/src/node/api/dispatcher.rs
sn_node/src/node/core/messaging/handling/agreement.rs
sn_node/src/node/core/messaging/handling/dkg.rs
sn_node/src/node/core/messaging/handling/handover.rs
sn_node/src/node/core/messaging/handling/mod.rs
sn_node/src/node/core/messaging/handling/proposals.rs
sn_node/src/node/core/messaging/sending/handover.rs
sn_node/src/node/core/mod.rs
sn_node/src/node/core/proposal.rs
sn_node/src/node/core/split_barrier.rs
sn_node/src/node/dkg/dkg_msgs_utils.rs
sn_node/src/node/dkg/session.rs
sn_node/src/node/dkg/voter.rs
testnet/bin.rs

Handover w/ Dkg Generations

---

sn_client/src/connections/messaging.rs

This should unblock client threads on initial contact and on queries

chore(client): send some msgs in bg threads

---

.github/workflows/benchmark_prs.yml
.github/workflows/benchmarks_pages.yml
Cargo.lock
sn_node/Cargo.toml
sn_node/benches/data_storage.rs
sn_node/src/dbs/chunk_store.rs
sn_node/src/dbs/lru_cache.rs
sn_node/src/node/cfg/mod.rs
sn_node/src/node/core/data/mod.rs
sn_node/src/node/core/data/storage/chunks.rs
sn_node/src/node/core/data/storage/mod.rs
sn_node/src/node/core/data/storage/registers.rs
sn_node/src/node/core/mod.rs
sn_node/src/node/mod.rs

Fix lru cache deadlock

---

.github/workflows/benchmark_prs.yml
.github/workflows/benchmarks_pages.yml
sn_dysfunction/src/lib.rs
sn_node/benches/data_storage.rs

Fix dysf potential deadlock

---

sn_node/src/bin/sn_node.rs

this should hopefully shutdown any bg processes running which may be blocking ports on reconnect
Co-authored-by: David Rusu <david.rusu@maidsafe.net>

fix: shutdown runtime in node loop

---

sn_node/benches/data_storage.rs
sn_node/src/dbs/event_store.rs
sn_node/src/dbs/mod.rs
sn_node/src/node/core/data/storage/registers.rs
sn_node/src/node/core/messaging/handling/service_msgs.rs

Chore improve data storage bench

---

sn_node/src/node/core/data/storage/registers.rs

chore: remove accidental log commit

---

.github/workflows/sn_pr_tests.yml
sn_node/src/node/logging/mod.rs

Chore logs ci

---

.github/workflows/sn_pr_tests.yml
Cargo.lock
sn_dysfunction/proptest-regressions/detection.txt
sn_dysfunction/src/detection.rs
sn_dysfunction/src/lib.rs
sn_interface/src/types/connections/link.rs
sn_interface/src/types/log_markers.rs
sn_node/src/bin/sn_node.rs
sn_node/src/node/api/dispatcher/background_tasks.rs
sn_node/src/node/api/dispatcher/mod.rs
sn_node/src/node/core/api.rs
sn_node/src/node/core/bootstrap/join.rs
sn_node/src/node/core/comm/link.rs
sn_node/src/node/core/comm/mod.rs
sn_node/src/node/core/comm/peer_session.rs
sn_node/src/node/core/messaging/handling/agreement.rs
sn_node/src/node/core/messaging/handling/dkg.rs
sn_node/src/node/core/messaging/handling/mod.rs
sn_node/src/node/core/mod.rs
sn_node/src/node/membership/mod.rs
testnet/bin.rs

This is atop #1232 so need that in first

Enable DKG issue tracking

---

resources/scripts/network_is_ready.sh

fix: update network_is_ready.sh for sn_client dir

---

.github/workflows/sn_pr_tests.yml
Cargo.lock
sn_dysfunction/Cargo.toml
sn_dysfunction/proptest-regressions/detection.txt
sn_dysfunction/src/detection.rs
sn_node/src/node/api/dispatcher/background_tasks.rs

test: improving dysf test, reproducible issues

---

sn_client/benches/upload_bytes.rs

test: make the measurement of client bench test more accurate

---

sn_client/benches/upload_bytes.rs

chore: more tweaks to benchmarks for clippy

---

sn_node/src/comm/link.rs
sn_node/src/comm/mod.rs
sn_node/src/comm/peer_session.rs
sn_node/src/node/api/cmds.rs
sn_node/src/node/api/dispatcher.rs
sn_node/src/node/core/messaging/handling/join.rs
sn_node/src/node/core/messaging/handling/mod.rs

Channel based multi-threading in Comm

---

sn_node/src/bin/sn_node.rs

chore(cleanup): small cleanup tweaks to node bin

---

sn_node/src/node/api/dispatcher.rs
sn_node/src/node/api/flow_ctrl/cmd_ctrl.rs
sn_node/src/node/api/flow_ctrl/mod.rs
sn_node/src/node/api/mod.rs
sn_node/src/node/api/tests/mod.rs
sn_node/src/node/core/api.rs
sn_node/src/node/core/connectivity.rs
sn_node/src/node/core/data/records/mod.rs
sn_node/src/node/core/messaging/handling/agreement.rs
sn_node/src/node/core/messaging/handling/anti_entropy.rs
sn_node/src/node/core/messaging/handling/dkg.rs
sn_node/src/node/core/messaging/handling/handover.rs
sn_node/src/node/core/messaging/handling/join.rs
sn_node/src/node/core/messaging/handling/left.rs
sn_node/src/node/core/messaging/handling/membership.rs
sn_node/src/node/core/messaging/handling/mod.rs
sn_node/src/node/core/messaging/handling/relocation.rs
sn_node/src/node/core/messaging/handling/resource_proof.rs
sn_node/src/node/core/messaging/handling/service_msgs.rs
sn_node/src/node/core/messaging/handling/update_section.rs
sn_node/src/node/core/messaging/sending/anti_entropy.rs
sn_node/src/node/core/messaging/sending/handover.rs
sn_node/src/node/core/messaging/sending/proposal.rs
sn_node/src/node/core/messaging/sending/services.rs
sn_node/src/node/core/messaging/sending/system.rs
sn_node/src/node/core/mod.rs
sn_node/src/node/logging/log_ctx.rs

chore: add RwLock to Node inside dispatcher

---

sn_node/src/comm/mod.rs
sn_node/src/comm/peer_session.rs

Previous work on PeerSessions had removed SendJob retries, this PR adds that functionality back.

fix(comm): re-enable send job retries on transient errors

---

sn_client/src/connections/messaging.rs
sn_node/examples/routing_minimal.rs
sn_node/examples/routing_stress.rs
sn_node/src/bin/sn_node.rs
sn_node/src/node/api/mod.rs
sn_node/src/node/core/bootstrap/join.rs

Ed fix join atop main

---

Cargo.lock
log_cmds_inspector/Cargo.toml
log_cmds_inspector/bin.rs
sn_cli/Cargo.toml
sn_cli/src/cli.rs
sn_cli/src/operations/config.rs
sn_cli/src/subcommands/cat.rs
sn_cli/src/subcommands/config.rs
sn_cli/src/subcommands/dog.rs
sn_cli/src/subcommands/files.rs
sn_cli/src/subcommands/keys.rs
sn_cli/src/subcommands/mod.rs
sn_cli/src/subcommands/networks.rs
sn_cli/src/subcommands/node.rs
sn_cli/src/subcommands/nrs.rs
sn_cli/src/subcommands/safe_id.rs
sn_cli/src/subcommands/setup.rs
sn_cli/src/subcommands/wallet.rs
sn_cli/src/subcommands/xorurl.rs
sn_client/Cargo.toml
sn_client/examples/churn.rs
sn_client/examples/network_split.rs
sn_node/Cargo.toml
sn_node/examples/config_handling.rs
sn_node/examples/routing_minimal.rs
sn_node/examples/routing_stress.rs
sn_node/src/bin/sn_node.rs
sn_node/src/node/cfg/config_handler.rs
testnet/Cargo.toml
testnet/bin.rs

Experimenting with build timings in CI

Replace StructOpt with Clap

---

sn_node/src/node/api/cmds.rs
sn_node/src/node/api/flow_ctrl/cmd_ctrl.rs

This facilitates correlation in logging.

feat(cmd): add parent id

---

sn_api/src/app/files/mod.rs
sn_api/src/app/nrs/nrs_map.rs
sn_api/src/app/resolver/safe_data.rs
sn_api/src/ipc/mod.rs
sn_api/src/ipc/req.rs
sn_api/src/safeurl/mod.rs
sn_api/src/safeurl/url_parts.rs
sn_api/src/safeurl/version_hash.rs
sn_cli/src/cli.rs
sn_cli/src/operations/auth_and_connect.rs
sn_cli/src/subcommands/mod.rs
sn_interface/src/messaging/data/mod.rs
sn_interface/src/messaging/serialisation/mod.rs
sn_interface/src/messaging/serialisation/wire_msg_header.rs
sn_interface/src/messaging/system/join_as_relocated.rs
sn_interface/src/types/keys/keypair.rs
sn_node/src/comm/back_pressure.rs
sn_node/src/node/api/event.rs
sn_node/src/node/core/messaging/system_msgs.rs

chore(clippy): bit more low hanging clippy fruit

---

sn_client/Cargo.toml

- chore(deps): move to dev-dependencies
- style: tweak sn_client/Cargo.toml formatting TOML

chore deps dev

---

sn_api/src/app/wallet.rs
sn_cli/src/subcommands/helpers.rs

- Display the owner of each DBC when `cat`-ing a wallet.
- Align to the right the balance of each DBC when `cat`-ing a wallet.
- Shorten the default name set to DBC when deposited in a wallet.
- Make the name of the change DBC automatically deposited in the wallet unique.
Example output:
```
$ safe cat safe://hyryynyw5jg6rw87x795yjqbaz1rc9e4w8yhqu8x45zksrb4f9h9g9ejf8yb6o 
Spendable balances of wallet at "safe://hyryynyw5jg6rw87x795yjqbaz1rc9e4w8yhqu8x45zksrb4f9h9g9ejf8yb6o":
+------------------------+----------------------+-----------------+---------------------+
| Spendable balance name | Balance              | Owner           | DBC Data            |
|------------------------+----------------------+-----------------+---------------------|
| dbc-6892553f           |          1.987000000 | …
```

feat(cli): show the DBC owner in the wallet displayed by cat cmd

---

.github/workflows/daily_droplet_run.yml
.github/workflows/release.yml
.github/workflows/sn_pr_tests.yml
sn_interface/src/network_knowledge/mod.rs
sn_node/src/node/messaging/join.rs

logging sn_concensus and tweak expected age calculation for joining node

---

sn_dysfunction/src/lib.rs
sn_interface/src/messaging/authority.rs
sn_interface/src/messaging/signature_aggregator.rs
sn_interface/src/network_knowledge/mod.rs
sn_interface/src/network_knowledge/section_keys.rs
sn_interface/src/network_knowledge/section_peers.rs
sn_node/src/node/api.rs
sn_node/src/node/connectivity.rs
sn_node/src/node/data/records/mod.rs
sn_node/src/node/delivery_group.rs
sn_node/src/node/messaging/agreement.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/handover.rs
sn_node/src/node/messaging/join.rs
sn_node/src/node/messaging/left.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/messaging/mod.rs
sn_node/src/node/messaging/proposal.rs
sn_node/src/node/messaging/relocation.rs
sn_node/src/node/messaging/resource_proof.rs
sn_node/src/node/messaging/service_msgs.rs
sn_node/src/node/messaging/system_msgs.rs
sn_node/src/node/mod.rs
sn_node/src/node/node_api/dispatcher.rs
sn_node/src/node/node_api/flow_ctrl/mod.rs
sn_node/src/node/node_api/mod.rs
sn_node/src/node/node_api/tests/mod.rs
sn_node/src/node/relocation.rs

Changes:
- remove unused async
- remove RefCell in NetworkKnowledge
- remove Locks in SignatureAggregator and SectionKeyProvider

Clear out more async

---

sn_client/src/connections/messaging.rs

fix(client): Remove unused Arc(RwLock) structure

---

.github/workflows/sn_pr_tests.yml

chore: tar the log files before upload-artifact

---

sn_node/src/bin/sn_node.rs

This means that once written a log file's name will not change.
This hould make debugging a live network easier (your log file is less likely to change while viewing), and also pulling logs from a network via rsync fafster (as the namess/content aren't changing all the time).

chore: use timestamp for log files

---

.github/workflows/sn_pr_tests.yml

fix: resolve script error for tar

---

sn_node/src/node/data/records/mod.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/mod.rs
sn_node/src/node/messaging/service_msgs.rs
sn_node/src/node/mod.rs
sn_node/src/node/node_api/dispatcher.rs

tweaks to reduce SendMsg cmd load.
as https://github.com/maidsafe/safe_network/pull/1342 but without the change to the Sendmsg priority

Chore refactor send msg cmd

---

sn_node/src/comm/link.rs
sn_node/src/comm/peer_session.rs
sn_node/src/node/node_api/cmds.rs

Testing this on droplets just now

chore: increase CleanUpPeerLinks prio

---

sn_node/src/node/node_api/dispatcher.rs
sn_node/src/node/node_api/flow_ctrl/mod.rs

fix(node): drop RwLock guards after job is done

---

sn_interface/src/messaging/system/agreement.rs
sn_node/src/node/dkg/session.rs
sn_node/src/node/dkg/voter.rs
sn_node/src/node/messaging/agreement.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/handover.rs
sn_node/src/node/messaging/proposal.rs
sn_node/src/node/messaging/system_msgs.rs
sn_node/src/node/node_api/cmds.rs
sn_node/src/node/node_api/dispatcher.rs
sn_node/src/node/proposal.rs
sn_node/src/node/split_barrier.rs

It was later introduced in the SAP, which is already part of the types where the generation field was previously added.

fix(proposal): remove redundant generation field

---

sn_node/src/node/api.rs
sn_node/src/node/data/records/mod.rs
sn_node/src/node/node_api/cmds.rs
sn_node/src/node/node_api/dispatcher.rs
sn_node/src/node/node_api/mod.rs

As it always results in a delivery group of 1. Which is pointless

chore: use SendMsg for send_node_msg_to_nodes

---

sn_node/src/comm/peer_session.rs

chore: reduce number of Send retries in PeerSession

---

sn_node/src/node/flow_ctrl/cmds.rs

High prio sends

---

.github/workflows/sn_pr_tests.yml

add a PR check for linting docs
E.g. checks broken links in the documentation

CI: Add check for checking docs

---

.github/workflows/sn_pr_tests.yml
sn_dysfunction/src/detection.rs
sn_dysfunction/src/lib.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/system_msgs.rs
sn_node/src/node/mod.rs

Dysfunction tweaks

---

sn_api/src/app/wallet.rs
sn_cli/src/subcommands/wallet.rs
sn_cli/tests/cli_wallet.rs
sn_cmd_test_utilities/src/lib.rs

This is a follow up PR (10th PR) to https://github.com/maidsafe/safe_network/pull/1317, PR https://github.com/maidsafe/safe_network/pull/1351, PR https://github.com/maidsafe/safe_network/pull/1226, PR https://github.com/maidsafe/safe_network/pull/1301, PR https://github.com/maidsafe/safe_network/pull/1274, PR https://github.com/maidsafe/safe_network/pull/1235, PR https://github.com/maidsafe/safe_network/pull/1097, PR https://github.com/maidsafe/safe_network/pull/1105, and PR https://github.com/maidsafe/safe_network/pull/1143.
- Expose a public `is_dbc_spent` API which allows users to check if a DBC's `KeyImage` has been already spent on the network.
- Have the CLI `wallet deposit` command to perform a verification is the supplied DBC has been already spent before depositing into a wallet. …

feat(api): expose a public API which allows users to check if a DBC has been already spent on the network

---

sn_interface/src/network_knowledge/errors.rs
sn_interface/src/network_knowledge/node_state.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/membership/mod.rs

Health check with traceroute fix

---

.github/workflows/sn_pr_tests.yml

ci: prebuild tests before running cargo nextest

---

sn_node/benches/data_storage.rs
sn_node/src/node/flow_ctrl/event.rs
sn_node/src/node/flow_ctrl/mod.rs

chore: simplify data replication msg sending

---

.github/workflows/sn_pr_tests.yml

chore: enale client log during API tests

---

.github/workflows/sn_pr_tests.yml
Cargo.lock
sn_client/Cargo.toml
sn_node/Cargo.toml

Chore tracedefault

---

sn_api/src/app/test_helpers.rs

test: fix test helper for reissuing dbcs

---

sn_interface/src/types/cache/mod.rs
sn_interface/src/types/log_markers.rs
sn_node/examples/routing_stress.rs
sn_node/src/node/data/records/mod.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/messaging/mod.rs
sn_node/src/node/messaging/service_msgs.rs

Lock tweaks2

---

.github/workflows/daily_droplet_run.yml

ci: ensure we prebuild in the crate dir before running the tests

---

.github/workflows/sn_pr_tests.yml
sn_api/src/app/wallet.rs
sn_client/src/api/spentbook_apis.rs

increase reissue query attempts and reduce the dbc CI testing threads

---

sn_api/examples/fetch_file.rs
sn_api/examples/file_upload.rs
sn_api/src/app/mod.rs
sn_api/src/app/test_helpers.rs
sn_cli/src/operations/auth_and_connect.rs
sn_client/src/api/client_builder.rs
sn_client/src/api/mod.rs
sn_client/src/bin/query-adult/log.rs
sn_client/src/bin/query-adult/main.rs
sn_client/src/config_handler.rs

- feat(client): ClientBuilder to instantiate Client

Add ClientBuilder to instantiate client

---

sn_node/src/node/flow_ctrl/cmd_ctrl.rs

fix(node): make cmd ctrl response quicker

---

sn_node/src/comm/mod.rs
sn_node/src/comm/peer_session.rs
sn_node/src/lib.rs
sn_node/src/node/bootstrap/join.rs
sn_node/src/node/flow_ctrl/cmd_ctrl.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/messaging/anti_entropy.rs

Log Sleep with unique id

---

sn_cli/src/operations/config.rs
sn_node/src/node/mod.rs

Small semantic Rust tweaks

---

testnet/bin.rs

chore(testnet): small improvements to flamegraph init and cos

---

sn_client/src/connections/listeners.rs
sn_interface/src/types/log_markers.rs
sn_node/src/comm/mod.rs
sn_node/src/node/bootstrap/join.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/membership/mod.rs
sn_node/src/node/messaging/membership.rs

Gossip all votes when we notice no membership progress; Start timer after first vote

---

sn_node/src/bin/sn_node/main.rs
sn_node/src/lib.rs
sn_node/src/node/bootstrap/join.rs
sn_node/src/node/messaging/anti_entropy.rs

modify the join process timeout mechanism

---

sn_api/src/app/mod.rs

fix: update prefixmap getter call after name change

---

Cargo.lock
sn_interface/src/messaging/system/mod.rs

chore: add partial eq for rust 1.63; dep updates

---

sn_dysfunction/src/detection.rs
sn_interface/src/messaging/msg_type.rs
sn_interface/src/messaging/system/agreement.rs
sn_interface/src/messaging/system/mod.rs
sn_interface/src/network_knowledge/mod.rs
sn_node/src/node/connectivity.rs
sn_node/src/node/flow_ctrl/cmds.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/tests/cmd_utils.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/messaging/agreement.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/proposal.rs
sn_node/src/node/messaging/relocation.rs
sn_node/src/node/messaging/system_msgs.rs
sn_node/src/node/mod.rs
sn_node/src/node/proposal.rs
testnet/bin.rs

Add ae probe as health check

---

sn_client/src/connections/messaging.rs

chore: retry more times for connection fails w/ client

---

sn_interface/src/messaging/system/mod.rs
sn_node/src/node/mod.rs

Now we differentiate queries per adult/index, we may need more queries.

chore(node): increase data query limit

---

sn_node/src/node/README.md

Fix typo in README.md.
Thanks @willief!

Trivialy typo fix (by willief)

---

sn_client/src/connections/listeners.rs
sn_client/src/connections/messaging.rs

chore(client): associated functions to methods

---

sn_cli/src/cli.rs
sn_cli/src/operations/config.rs
sn_cli/src/subcommands/networks.rs
sn_cli/src/subcommands/node.rs
sn_interface/src/network_knowledge/section_tree/stats.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/mod.rs

E.g. if we have the following network configured with the CLI:
```
$ safe networks
+----------+-----------------------+-----------------------+---------------------------------------------------------+
| Networks |                       |                       |                                                         |
|----------+-----------------------+-----------------------+---------------------------------------------------------|
| Current  | Network name          | Genesis Key           | Network map info                                        |
|----------+-----------------------+-----------------------+---------------------------------------------------------|
| *        | baby-fleming          | PublicKey(044d..33b5) | Local: "~/.safe/network_contacts/PublicKey(044d..33b5)" | …
```

feat(cli): new cmd to display detailed information about a configured network

---

sn_node/src/comm/listener.rs
sn_node/src/node/bootstrap/join.rs
sn_node/src/node/error.rs
sn_node/src/node/flow_ctrl/cmd_ctrl.rs
sn_node/src/node/flow_ctrl/cmds.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/event.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/monitoring/event_rates.rs
sn_node/src/node/node_starter.rs
sn_node/src/node/node_test_api.rs

Working cmd clone gone

---

sn_api/src/app/files/realpath.rs
sn_cli/src/subcommands/files.rs
sn_interface/src/types/cache/mod.rs
sn_node/src/node/dkg/session.rs
testnet/bin.rs

chore(node): fix clippy some/none issues

---

sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/mod.rs

Small tweaks

---

Cargo.lock
sn_client/Cargo.toml
sn_interface/Cargo.toml
sn_interface/src/network_knowledge/errors.rs
sn_interface/src/network_knowledge/mod.rs
sn_interface/src/network_knowledge/sections_dag.rs
sn_node/Cargo.toml

- Use Merkle reigsters to implement SecuredLinkedList

feat: SecuredLinkedList using Merkle registers

---

sn_client/Cargo.toml

chore: adds missing bench to cargo.toml for client

---

.github/workflows/daily_droplet_run.yml

ci: remove 'always()' conditions for release run tests

---

sn_node/benches/data_storage.rs

ci: fix missing await in data_storage bench

---

sn_node/benches/data_storage.rs

ci: fix missing block on in data_store bench

---

sn_interface/src/network_knowledge/section_authority_provider.rs
sn_node/src/node/dkg/session.rs
sn_node/src/node/dkg/voter.rs
sn_node/src/node/messaging/dkg.rs

chore: pass by reference instead of by value

---

sn_node/src/node/flow_ctrl/cmds.rs
sn_node/src/node/flow_ctrl/dispatcher.rs

feat: don't HandlePeerFailedSend for ServiceMsgs

---

sn_client/src/api/file_apis.rs
sn_client/src/api/queries.rs
sn_client/src/connections/mod.rs
sn_client/src/errors.rs
sn_interface/src/messaging/data/mod.rs

chore(client): retry DataNotFound errors for data_copy_count

---

sn_node/src/node/mod.rs

feat: remove unnecessary double init for handover

---

sn_interface/src/network_knowledge/sections_dag.rs

Adding `single_branch_dag_for_key` API to get a partial `SectionsDAG` with a single branch which contains the given `key`, from the genesis to the last key of any of its children branches.
The API also returns the last key of the (single) branch it contains.

feat(section-dag): add API to retrieve a single-branch partial DAG containing a given key

---

Cargo.lock

chore: update axum dep for security

---

sn_interface/src/types/register/reg_crdt.rs

test(RegisterCrdt): RegisterCrdt generates entry hash properly

---

sn_node/src/node/flow_ctrl/cmd_ctrl.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs

- fix: pass id of parent to cmd

fix parent id cmd

---

Cargo.lock
sn_client/Cargo.toml
sn_interface/Cargo.toml
sn_node/Cargo.toml

chore: cleanup unused deps

---

sn_client/src/api/register_apis.rs
sn_interface/src/types/register/mod.rs

test: verify entry_hash generation

---

sn_node/src/node/bootstrap/join.rs

fix(sn_node): restart after accumulated retry_response

---

Cargo.lock
sn_interface/Cargo.toml
sn_node/Cargo.toml
sn_node/src/node/dkg/mod.rs
sn_node/src/node/messaging/dkg.rs

- integrate with the latest `sn_sdkg` changes

Integrate recursive sn_sdkg changes

---

sn_node/src/node/cfg/config_handler.rs
sn_node/src/node/node_starter.rs

refactor: pull out bootstrap functions for normal and genesis nodes

---

sn_node/src/node/dkg/README.md

Adapt DKG docs to sigshare change

---

sn_node/src/node/flow_ctrl/periodic_checks.rs

as well as resending out last vote

fix(node): request membership AE when we have stalled votes

---

sn_client/src/api/queries.rs

chore(sn_client): cleanup un-necessary attempts counter

---

.github/workflows/sn_pr_tests.yml
Cargo.lock
sn_client/Cargo.toml
sn_interface/src/types/connections/link.rs
sn_node/Cargo.toml
sn_node/src/comm/mod.rs
sn_node/src/node/flow_ctrl/tests/cmd_utils.rs
sn_node/src/node/flow_ctrl/tests/mod.rs

Node comm test tweaks

---

sn_node/src/node/flow_ctrl/cmds.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/messaging/mod.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/mod.rs

Another wave of removal towards the complete removal of unnecessary Auths:  
- Removes now unused message aggregators

refactor: remove msg aggregators

---

.github/workflows/sn_pr_tests.yml

ci: reenable api tests

---

sn_interface/src/types/connections/link.rs

bidi streams were always creating new conns. Now they will reuse existing

fix(client): use existing conns when available

---

sn_api/examples/fetch_file.rs
sn_api/src/app/files/mod.rs
sn_api/src/app/nrs/mod.rs
sn_api/src/app/resolver/mod.rs
sn_node/src/comm/mod.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/messaging/join.rs
sn_node/src/node/messaging/node_msgs.rs

chore(node): remove reachability checks.

---

sn_node/src/bin/sn_node/main.rs
sn_node/src/node/messaging/anti_entropy.rs

reset ae_backoff_cache

---

sn_node/src/node/messaging/join.rs
sn_node/src/node/messaging/node_msgs.rs

chore(node): remove reachability check from inital join

---

.github/workflows/sn_pr_tests.yml

ci: set sn_client tests as --release

---

sn_node/src/node/messaging/handover.rs
sn_node/src/node/messaging/proposal.rs

Removing done TODOs

---

sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/mod.rs

feat(sn_node): remove ae_backoff_cache

---

.github/workflows/sn_pr_tests.yml
sn_node/src/comm/link.rs
sn_node/src/comm/mod.rs
sn_node/src/comm/peer_session.rs
sn_node/src/node/bootstrap/join.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/messaging/agreement.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/handover.rs
sn_node/src/node/messaging/join.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/relocation.rs
sn_node/src/node/mod.rs
sn_node/src/storage/register_store.rs

Reduce async in node

---

README.md

Minor tidy up re the number of crates in the top level Readme.md

Minor tidy up re the number of crates 

---

sn_interface/src/types/log_markers.rs
sn_node/src/node/messaging/anti_entropy.rs

feat(sn_node): remove AE hold back

---

.github/workflows/benchmark_prs.yml
.github/workflows/benchmarks_pages.yml
.github/workflows/merge.yml
.github/workflows/run_pr_checks.yml

Ci improve flow

---

sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/messaging/agreement.rs
sn_node/src/node/messaging/handover.rs

fix(sn_node): only proposal when reached handover consensus first time

---

.github/workflows/merge.yml
.github/workflows/run_pr_checks.yml

that ci red when things are fine is annoying.

ci: dont run cargy deny until we can get it green.

---

.github/workflows/merge.yml
.github/workflows/run_pr_checks.yml
sn_client/src/api/cmds.rs
sn_client/src/api/file_apis.rs
sn_client/src/api/queries.rs
sn_client/src/connections/listeners.rs
sn_client/src/connections/messaging.rs
sn_interface/src/types/connections/link.rs
sn_interface/src/types/connections/mod.rs
sn_node/src/comm/peer_session.rs
sn_node/src/node/flow_ctrl/cmd_ctrl.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/mod.rs

Client connect to link on creation

---

sn_interface/src/messaging/system/dkg.rs
sn_interface/src/messaging/system/mod.rs
sn_interface/src/messaging/system/proposal.rs
sn_interface/src/messaging/system/section_sig.rs
sn_node/src/node/dkg/README.md
sn_node/src/node/dkg/mod.rs
sn_node/src/node/messaging/agreement.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/handover.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/proposal.rs
sn_node/src/node/mod.rs

Closes https://github.com/maidsafe/safe_network/pull/1716

refactor: make Proposal saner and add docs

---

sn_node/src/node/flow_ctrl/periodic_checks.rs

chore(sn_node): less logs

---

sn_node/src/node/flow_ctrl/periodic_checks.rs

chore: another log removed

---

Cargo.lock

chore: update qp2p

---

sn_client/src/connections/listeners.rs
sn_client/src/errors.rs

Fix client ae response logic to use knowledge

---

testnet/bin.rs

ci: revert testnet bin changes to get windows jobs going

---

sn_interface/src/messaging/data/register.rs
sn_interface/src/messaging/system/join.rs
sn_interface/src/messaging/system/mod.rs
sn_interface/src/network_knowledge/section_tree/mod.rs
sn_interface/src/network_knowledge/sections_dag.rs
sn_node/src/node/bootstrap/join.rs
sn_node/src/node/flow_ctrl/tests/cmd_utils.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/messaging/join.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/messaging/node_msgs.rs

Bootstrap section tree before starting join process

---

sn_node/src/node/messaging/dkg.rs

- https://github.com/maidsafe/safe_network/commit/fed9eed1b4459a5c7f6e6ba97b31f678cae2d5db Simulate a DKG round from start till termination and verify the newly generated `SecretKeyShare` for each node. The test bypasses the comm module and passes the `NodeMsgs` directly to the corresponding peers.
- https://github.com/maidsafe/safe_network/commit/6868415191ae8bed30b42da31f90b9775db47b09 After DKG termination, each node proposes a new `SectionInfo` to denote the change in the `SectionKey`. But if a lagging node (DKG in-progress) has received the `SectionAuthorityProvider` from a terminated node through AE, then the lagging node should not propose `SectionInfo`.
- https://github.com/maidsafe/safe_network/commit/e81b205339275a8f18122ecf97bdeabbe55403bc DKG requires all the votes from the …

tests: DKG

---

.github/workflows/run_pr_checks.yml
sn_client/src/connections/messaging.rs
sn_node/src/node/flow_ctrl/dysfunction.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/mod.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/mod.rs

chore(node): pass in context to NodeMsg handling

---

sn_client/src/connections/listeners.rs
sn_interface/src/types/log_markers.rs

fix(sn_client): make client receive stream log clearer

---

sn_cli/src/subcommands/files_get.rs
sn_cli/tests/cli_cat.rs
sn_cli/tests/cli_dog.rs
sn_cli/tests/cli_files.rs
sn_cli/tests/cli_nrs.rs
sn_client/src/api/register_apis.rs
sn_client/src/api/spentbook_apis.rs
sn_interface/src/dbcs.rs
sn_interface/src/network_knowledge/mod.rs
sn_interface/src/network_knowledge/section_keys.rs
sn_interface/src/network_knowledge/section_tree/mod.rs
sn_interface/src/types/utils/mod.rs
sn_node/src/node/flow_ctrl/tests/dbc_utils.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/storage/register_store.rs
sn_node/src/storage/registers.rs

Ran nightly by accident so made use of it to apply some fixes anyway.
Mainly lints `iter_kv_map` (e.g. use `keys()`, instead of `iter()`, which iterates over both keys and values where the value is not used) and `needless_borrow`.

style: applied clippy nightly

---

sn_interface/src/network_knowledge/section_tree/mod.rs
sn_node/src/comm/mod.rs

fix(sn_node): log cleanup

---

sn_node/src/comm/mod.rs
sn_node/src/comm/peer_session.rs
sn_node/src/node/bootstrap/join.rs
sn_node/src/node/connectivity.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/dysfunction.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/mod.rs
sn_node/src/node/node_starter.rs

Standardise channel sizes

---

sn_node/src/comm/listener.rs
sn_node/src/comm/mod.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/client_msgs.rs

chore(node): don't store client peer sessions

---

testnet/bin.rs

For platform independent separation style.

chore(testnet): push dirs separately

---

sn_client/src/api/file_apis.rs

Limiting the maximum number of chunks per file concurrently uploaded/retrieved to 5.

feat(client): cap the number of concurrent chunks to be uploaded/retrieved for a file

---

sn_client/src/connections/link.rs
sn_client/src/sessions/messaging.rs

chore(client): retry conns on any LinkError

---

sn_node/src/bin/sn_node/main.rs

fix(node): wait before retrying creation on node instance error

---

.github/workflows/merge.yml
.github/workflows/run_pr_checks.yml
sn_client/examples/churn.rs

Churn on gha infra

---

sn_api/Cargo.toml
sn_cli/Cargo.toml

fix(feats): add upload limit to cli cfg

---

sn_node/src/node/data/capacity.rs
sn_node/src/node/data/records.rs
sn_node/src/node/mod.rs

fix: remove full adults from data storage algos

---

sn_node/benches/data_storage.rs

test: add reg edit bench

---

Cargo.lock
sn_node/Cargo.toml
sn_node/examples/config_handling.rs
sn_node/src/bin/sn_node/main.rs
sn_node/src/comm/link.rs
sn_node/src/comm/listener.rs
sn_node/src/comm/mod.rs
sn_node/src/comm/peer_session.rs
sn_node/src/node/cfg/config_handler.rs

refactor: update qp2p (quinn)

---

sn_interface/src/messaging/serialisation/wire_msg.rs
sn_node/src/comm/peer_session.rs
sn_node/src/node/data/records.rs
sn_node/src/node/flow_ctrl/cmds.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/messages.rs

This change also includes a minor refactor within `comm` mod.

chore(messaging): removing unused payload_debug field from msgs

---

sn_node/src/node/flow_ctrl/mod.rs

fix: send all data batches, not just the first

---

README.md
sn_node/src/lib.rs

chore(release): readme change to trigger release

---

sn_node/src/node/bootstrap/join.rs

fix(sn_node): update network knowledge AFTER sent join request

---

sn_interface/src/messaging/system/join.rs
sn_node/src/node/bootstrap/join.rs
sn_node/src/node/messaging/join.rs

This reverts commit 8aa694171b1dd5c2505259e67d6e3434ee94d213.

Revert "feat(join): prevent joins from nodes behind NAT"

---

sn_node/src/bin/sn_node/log/mod.rs
sn_node/src/bin/sn_node/main.rs
sn_node/src/node/error.rs

This should close all existing endpoints and other spawned tasks and get us a proper fresh ndoe instance

fix(node): ues a fresh runtime every node_run call

---

sn_node/src/comm/peer_session.rs

This avoids many many connection attempts to the same node if one is in progress already.

fix(node): make initial get/connect blocking

---

resources/scripts/all_nodes_joined.sh
sn_client/src/sessions/messaging.rs

- Additional checks added to all_nodes_joined.sh script to be able to detect nodes in the network knowledge which are not those that effectively joined the network.
- Also some minor improvements to sn_client log msgs.
Example output when there is a mismatch of members and joined nodes:
```
Checking nodes log files to verify all nodes have joined. Logs path: ~/.safe/node/local-test-network
Number of nodes: 15
All nodes have joined. Nodes IPs:
127.0.0.1:57739
127.0.0.1:57751
127.0.0.1:57745
127.0.0.1:57740
127.0.0.1:57747
127.0.0.1:57748
127.0.0.1:57749
127.0.0.1:57754
127.0.0.1:57744
127.0.0.1:57741
127.0.0.1:57742
127.0.0.1:57743
127.0.0.1:57752
127.0.0.1:57750
127.0.0.1:57753
Checking if nodes in network knowledge match the list of nodes IPs...
Node 127.0.0.1:57750 is a valid member …
```

feat(ci): verify members in network knowledge are the expected

---

sn_node/src/bin/sn_node/main.rs

- opentelemetry tracing requires a tokio runtime to be present, hence leave a separate rt running if `otlp` feature is enabled

fix(log): initialize logging just once

---

resources/testdata/large_markdown_file.md
sn_cli/README.md
sn_node/src/bin/sn_node/main.rs
sn_node/src/node/cfg/config_handler.rs

chore(docs): remove references to IGD

---

sn_node/src/comm/link.rs

This should allow DashMap to be in sync and prevent a harsh loop killing us here (as it has done)

fix(node): add tiny delay to bidi retry

---

sn_node/src/node/messaging/update_section.rs

chore(node): request missing data from the entire section

---

sn_node/benches/data_storage.rs
sn_node/src/node/cfg/config_handler.rs
sn_node/src/node/cfg/mod.rs
sn_node/src/node/data/records.rs
sn_node/src/node/flow_ctrl/tests/network_builder.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/mod.rs
sn_node/src/node/node_starter.rs
sn_node/src/storage/chunks.rs
sn_node/src/storage/mod.rs
sn_node/src/storage/register_store.rs
sn_node/src/storage/registers.rs
sn_node/src/storage/used_space.rs

This PR adds a section growth system where we:
- trigger joins on min capacity reached
- add nodes as used space grows
- vote node offline when a node is prematurely full
- remove data outside of our range

Feat section growth system

---

sn_node/src/node/messaging/node_msgs.rs
sn_node/src/storage/mod.rs
sn_node/src/storage/used_space.rs

- The operator was a remnant from previous version, that had not yet been replaced.
- Also updates some comments.

fix(storage): replace modulo op with div

---

sn_interface/src/network_knowledge/mod.rs
sn_interface/src/network_knowledge/section_tree/mod.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/messaging/mod.rs
sn_node/src/node/mod.rs

This PR reduces ae messaging which is currently causing excess load.
Also, global network section knowledge is refactored to target 1 rand elder in 3 rand sections, every 5 minutes.

Optimize ae probing

---

resources/scripts/all_nodes_joined.sh

The script was using only one of the nodes' logs to find inconsistency in the membership list, but there are cases where this inconsistency is not seen by all nodes by the time we check, thus this PR changes the script to use all nodes' logs to extract a unique list of nodes/members in the network knowledge.

fix(script): 'all_nodes_joined.sh' script to use all nodes logs instead of only one

---

sn_node/src/bin/sn_node/main.rs
sn_node/src/comm/link.rs
sn_node/src/comm/peer_session.rs
sn_node/src/node/data/records.rs

Improve logs + ensure Comms faults tracked + make rt shutdown explicit on error

---

sn_node/src/node/bootstrap/join.rs

chore(node): log current name on join attempt

---

sn_interface/src/network_knowledge/section_tree/mod.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/mod.rs

chore(sn_node): some optimisations during AE probe

---

sn_node/src/bin/sn_node/main.rs

chore(node): retry recoverable errors on node start

---

sn_interface/src/network_knowledge/section_tree/mod.rs
sn_interface/src/network_knowledge/sections_dag.rs

chore(sn_node): skip section_tree update earlier for outdated sap

---

sn_interface/src/types/keys/ed25519.rs

- This becomes more important after a few splits.

feat(keypair): improves perf for smaller ranges

---

sn_fault_detection/Cargo.toml
sn_fault_detection/src/detection.rs
sn_node/src/node/flow_ctrl/fault_detection.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs

Fault improvements

---

sn_interface/src/messaging/data/mod.rs
sn_interface/src/messaging/msg_type.rs
sn_interface/src/messaging/system/mod.rs

chore(node): remove unused priority

---

sn_fault_detection/src/detection.rs
sn_fault_detection/src/lib.rs
sn_node/src/node/connectivity.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/fault_detection.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/section_state.rs
sn_node/src/node/mod.rs

Feat track and untrack proposal knowledge

---

sn_interface/src/network_knowledge/node_state.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/membership/mod.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/relocation.rs

1, not to relocate elder to self section, 
2, not counter join_as_relocated node as elder candidate immediately

feat(sn_node): extra criteria when relocate elder related node

---

.github/workflows/merge.yml
.github/workflows/version_bump.yml

ci: attempt to fix bors staging/trying concurrency

---

sn_node/src/node/flow_ctrl/cmds.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/tests/cmd_utils.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/messaging/data.rs
sn_node/src/node/messaging/join_network.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/streams.rs

Make joins bidi

---

sn_comms/src/listener.rs

This should prevent us blocking qp2p should a channel itself be blocked

fix(comm): Handle sending msgs off the incoming msg loop

---

sn_comms/src/error.rs
sn_comms/src/lib.rs

Feat no external section conns

---

sn_node/src/node/messaging/node_msgs.rs

Fixes a deadlock that causes test failures in https://github.com/maidsafe/safe_network/pull/1977

fix(sn_node): fix a deadlock during relocation

---

sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/mod.rs

chore(node): remove readlock where we have context

---

.github/workflows/merge.yml
.github/workflows/run_pr_checks.yml
sn_comms/src/lib.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/streams.rs

ci: add check for expected number of elders after startup

---

sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/data.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/handover.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/section_state.rs
sn_node/src/node/messaging/update_section.rs
sn_node/src/node/mod.rs

Remove unnecessary send msg indirection

---

sn_node/src/node/flow_ctrl/periodic_checks.rs

this should vastly reduce allocations coming from membership.clone() (which accounts for the vast majority of alloc in a runnning node just now

chore(node): only clone membership when needed

---

sn_comms/src/lib.rs
sn_interface/src/types/log_markers.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/data.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/messaging/promotion.rs
sn_node/src/node/messaging/update_section.rs
sn_node/src/node/mod.rs
sn_node/src/storage/chunks.rs

Elders update data on membership change

---

sn_node/src/node/mod.rs

Reduce the amount of old DKG sessions we keep

---

sn_node/src/node/flow_ctrl/periodic_checks.rs

We check if anything has expired before we grab context

chore(node): prevent unnecessary clones in periodics

---

sn_node/src/node/messaging/membership.rs

fix(relocation): always run the DKG checks on membership decision

---

sn_node/src/node/flow_ctrl/periodic_checks.rs

use a ref for membership during periodics, removes a repetitive, costly clone

chore: further reduce membership clones

---

sn_node/src/node/mod.rs

This reverts commit 5257295c18fd98d383bd70bbbe1fd3de1d0f9ea7.

Revert "feat: reduce the amount of old DKG sessions we keep"

---

sn_comms/src/lib.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/messaging/promotion.rs
sn_node/src/node/mod.rs

Chore comms remove unused async

---

sn_cli/src/operations/node.rs
sn_cli/src/subcommands/files_get.rs

.. plus two typos right where code changed

chore: fix additional issues from updated clippy

---

Cargo.lock
sn_node/Cargo.toml
sn_node/src/bin/sn_node/log/appender.rs

Chore deps

---

sn_node/src/node/mod.rs

Remove extra dkg trigger

---

.github/workflows/merge.yml
.github/workflows/run_pr_checks.yml

ci: make client tests single threaded once more

---

sn_client/src/api/file_apis.rs
sn_client/src/api/mod.rs
sn_client/src/api/queries.rs
sn_client/src/api/register_apis.rs
sn_client/src/api/spentbook_apis.rs
sn_client/src/bin/query-adult/main.rs
sn_client/src/errors.rs
sn_client/src/sessions/messaging.rs
sn_client/src/sessions/mod.rs

refactor(client): remove query result indirection

---

sn_api/src/authenticator/mod.rs
sn_client/src/lib.rs
sn_client/src/sessions/messaging.rs
sn_comms/src/lib.rs
sn_fault_detection/src/lib.rs
sn_interface/src/lib.rs
sn_node/src/lib.rs
sn_node/src/node/api.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/flow_ctrl/tests/cmd_utils.rs
sn_node/src/node/flow_ctrl/tests/network_builder.rs
sn_node/src/node/messaging/client_msgs.rs
sn_node/src/node/messaging/data.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/mod.rs
sn_node/src/node/mod.rs
sn_node/src/node/node_starter.rs
sn_node/src/storage/registers.rs

- refactor(client): unused async removal
- refactor(node): unused async removal
- chore: add clippy check for unused async

Removal of unused async and add clippy check

---

sn_client/src/connections/link.rs

If we call finish, but the node has already signalled `stop(0)`, then
our bytes are already received successfully, so we do not need to error
out or retry.

fix(client): ignore successfully stopped stream on

---

sn_node/src/node/messaging/relocation.rs

chore(sn_node): enable relocation in first section

---

.github/workflows/merge.yml
.github/workflows/version_bump.yml

ci: attempt to remove concurrency limit on bors try

---

sn_node/src/node/node_starter.rs

feat(node): retry as same node when joining

---

sn_node/README.md

docs: update Jaeger in README.md

---

sn_node/src/node/messaging/mod.rs

fix(node): prevent endlessly forwarding client msg if we're data holder

---

.github/workflows/merge.yml
.github/workflows/run_pr_checks.yml
Cargo.lock
sn_client/src/api/file_apis.rs

ci: enable 40/100mb tests

---

Cargo.lock
sn_cli/Cargo.toml
sn_cli/README.md
sn_cli/src/operations/node.rs
sn_cli/src/subcommands/node.rs
sn_client/Cargo.toml
sn_node/README.md
sn_node/src/node/cfg/config_handler.rs
testnet/Cargo.toml

refactor(node/cli): remove skip port forward flag

---

sn_interface/src/messaging/system/mod.rs
sn_interface/src/network_knowledge/mod.rs
sn_interface/src/network_knowledge/node_state/mod.rs
sn_interface/src/network_knowledge/node_state/relocation.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/flow_ctrl/tests/network_builder.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/relocation.rs
sn_node/src/node/mod.rs
sn_node/src/node/relocation.rs

Closes https://github.com/maidsafe/safe_network/issues/2080

feat(relocation): request to relocate

---

sn_api/src/app/mod.rs
sn_api/src/authenticator/mod.rs
sn_interface/src/network_knowledge/node_info.rs
sn_interface/src/types/keys/ed25519.rs
sn_interface/src/types/mod.rs
sn_interface/src/types/peer.rs
sn_interface/src/types/utils/mod.rs

Adding a new helper (inline function) to calculate the age from peer name.
Fixing #2101

fix: adding a helper func to calculate the age

---

sn_api/src/safeurl/mod.rs

refactor(api): use single const declaration

---

sn_node/src/node/messaging/anti_entropy.rs

- It is an unnecessary work started if node was removed from section.

refactor: call nodes after check still in section

---

sn_node/benches/data_storage.rs
sn_node/src/node/mod.rs
sn_node/src/storage/chunks.rs
sn_node/src/storage/mod.rs
sn_node/src/storage/register_store.rs
sn_node/src/storage/registers.rs

This is probably a remainder from old code where the paths had potential errors.

chore: removing unnecessary results

---

sn_client/src/errors.rs
sn_client/src/sessions/listeners.rs
sn_comms/src/lib.rs
sn_comms/src/listener.rs
sn_interface/src/messaging/data/mod.rs
sn_interface/src/messaging/mod.rs
sn_interface/src/messaging/msg_kind.rs
sn_interface/src/messaging/network_msg.rs
sn_interface/src/messaging/serialisation/wire_msg.rs
sn_interface/src/messaging/serialisation/wire_msg_header.rs
sn_interface/src/messaging/system/mod.rs
sn_interface/src/network_knowledge/mod.rs
sn_node/src/node/flow_ctrl/cmds.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/tests/cmd_utils.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/client_msgs.rs
sn_node/src/node/messaging/data.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/join_section.rs
sn_node/src/node/messaging/mod.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/relocation.rs
sn_node/src/node/messaging/serialize.rs
sn_node/src/node/messaging/streams.rs

This better reflects the domain.

Rename MsgType to NetworkMsg

---

Cargo.lock
sn_api/Cargo.toml
sn_api/src/app/wallet.rs
sn_cli/Cargo.toml
sn_cli/src/subcommands/wallet.rs
sn_client/Cargo.toml
sn_client/src/api/spentbook_apis.rs
sn_client/src/errors.rs
sn_interface/Cargo.toml
sn_interface/src/dbcs.rs
sn_interface/src/messaging/data/spentbook.rs
sn_interface/src/network_knowledge/section_keys.rs
sn_interface/src/network_knowledge/test_utils.rs
sn_node/Cargo.toml
sn_node/src/node/flow_ctrl/tests/dbc_utils.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/messaging/client_msgs.rs

- Integrates with the latest RingCT removal in `sn_dbc`

sn_dbc without ringcts integration

---

Cargo.lock
sn_node/Cargo.toml
sn_node/src/bin/sn_node/main.rs

chore(node): use parking lot and setup deadlock detection

---

.github/workflows/merge.yml
.github/workflows/version_bump.yml
bors.toml

Ci remove bors

---

README.md

This should help test merge queue

chore: arbitrary readme change

---

.github/workflows/merge.yml

ci: fix merge worlkflow

---

.github/workflows/merge.yml

ci: simplify Run All Test conditions

---

.github/workflows/merge.yml

ci: output node logs for churn test

---

sn_node/src/node/flow_ctrl/cmd_ctrl.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/tests/cmd_utils.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/flow_ctrl/tests/network_builder.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/join_section.rs
sn_node/src/node/messaging/relocation.rs
sn_node/src/node/node_starter.rs

Feat node out of dispatcher

---

.github/workflows/merge.yml

ci: dont run tests on version bump commit again

---

sn_interface/src/messaging/system/mod.rs
sn_node/src/node/connectivity.rs
sn_node/src/node/flow_ctrl/cmds.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/relocation.rs
sn_node/src/node/messaging/section_state.rs
sn_node/src/node/mod.rs

Removes joins_allowed voting, refactors section proposals

Remove joins allowed voting

---

sn_node/src/node/flow_ctrl/cmds.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/relocation.rs
sn_node/src/node/mod.rs
sn_node/src/node/relocation.rs
testnet/bin.rs

Improve relcoation logs

---

sn_node/src/node/messaging/client_msgs.rs
sn_node/src/node/messaging/data.rs

Some renaming, restructuring and shuffle of code to more easily follow what is happening.

chore: clarify spend flow

---

sn_api/src/app/auth.rs
sn_api/src/app/files/file_system.rs
sn_api/src/app/files/files_map.rs
sn_api/src/app/files/metadata.rs
sn_api/src/app/files/mod.rs
sn_api/src/app/multimap.rs
sn_api/src/app/nrs/mod.rs
sn_api/src/app/nrs/nrs_map.rs
sn_api/src/app/register.rs
sn_api/src/app/resolver/handlers.rs
sn_api/src/app/resolver/mod.rs
sn_api/src/app/wallet.rs
sn_api/src/authd_client/authd_client_api.rs
sn_api/src/authd_client/notifs_endpoint.rs
sn_api/src/common.rs

chore(logs): update to use tracing

---

.github/workflows/merge.yml

chore(ci): add sn_api tests logging

---

.github/workflows/merge.yml

This should speed up the queue where we've already run actions on a PR and it goes to the top directly.

ci: skip duplicate actions if content is the same.

---

sn_client/benches/upload_bytes.rs
sn_client/examples/churn.rs
sn_client/src/api/file_apis.rs

Better concurrent bench

---

Cargo.lock
sn_api/Cargo.toml
sn_api/src/app/test_helpers.rs
sn_api/src/app/wallet.rs
sn_cli/Cargo.toml
sn_cli/src/subcommands/wallet.rs
sn_client/Cargo.toml
sn_client/src/api/spentbook_apis.rs
sn_interface/Cargo.toml
sn_interface/src/dbcs.rs
sn_interface/src/dbcs/mod.rs
sn_interface/src/dbcs/reasons.rs
sn_interface/src/messaging/data/spentbook.rs
sn_interface/src/network_knowledge/section_keys.rs
sn_interface/src/network_knowledge/test_utils.rs
sn_node/Cargo.toml
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/messaging/client_msgs.rs

DBC reasons

---

sn_node/src/node/dkg/mod.rs
sn_node/src/node/messaging/dkg.rs

Fix overflow in DKG log

---

sn_api/src/app/wallet.rs

1. Including Elders in outputs (any value) when spending DBCs.
1.1 `Previous PR`: The query and handling of it on Elders for their reward keys and hard coded fee (#2184).
1.2 `This PR`: ✔️ The logic for including Elders to outputs (were they to be given keys and fee from Elders, see 1.3 below).
1.3 `Next PR`: Connecting the two above, by the client logic for querying Elders for their reward keys and fee (#2189).
Follow up PRs:
- <s>Including Elders in outputs (any value) when spending DBCs.</s>
- Elders confirming that spends contain outputs destined for them.
- Implementing a commonly known deterministic transfer/store cost and distribution to nodes.
- Including transfer/store cost in outputs when spending DBCs.
- Elders confirming that the amounts in those outputs are sufficient.

feat(rewards): add elders to dbc outputs

---

sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/messaging/anti_entropy.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/join_section.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/messaging/promotion.rs
sn_node/src/node/messaging/relocation.rs
sn_node/src/node/messaging/streams.rs
sn_node/src/node/mod.rs

Improvements to concurrency

---

.github/workflows/benchmarks_pages.yml
sn_client/src/api/file_apis.rs
sn_comms/src/lib.rs
sn_interface/src/types/log_markers.rs
sn_node/src/bin/safenode/main.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/messaging/data.rs
sn_node/src/node/messaging/mod.rs

Further concurrency

---

Cargo.lock
sn_interface/Cargo.toml
sn_node/Cargo.toml
sn_node/src/node/context.rs
sn_node/src/node/dkg/mod.rs
sn_node/src/node/flow_ctrl/dispatcher.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/node_msgs.rs
sn_node/src/node/mod.rs

Tidy cmd handling

---

sn_node/src/bin/safenode/main.rs
sn_node/src/node/context.rs
sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/periodic_checks.rs
sn_node/src/node/messaging/dkg.rs
sn_node/src/node/messaging/membership.rs
sn_node/src/node/mod.rs

Improve periodics

---

sn_node/src/node/flow_ctrl/mod.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/flow_ctrl/tests/test_utils.rs

fix(tests): process both blocking and non-blocking cmds

---

sn_interface/src/network_knowledge/mod.rs
sn_interface/src/network_knowledge/section_member_history.rs

chore(sn_node): enable decision validation during update

---

.github/workflows/release.yml

Trying to figure out what is going on with this artifacts directory...

WIP - fix: correct usage of artifacts directory

---

resources/scripts/all_nodes_joined.sh
sn_node/src/node/messaging/anti_entropy.rs

chore(test): parse network knowledge members from logs

---

.github/workflows/release.yml

This should hopefully fix the error when trying to upload the artifacts to S3.

fix: specify region for aws cli

---

Cargo.lock
sn_api/Cargo.toml
sn_api/src/app/test_helpers.rs
sn_api/src/app/wallet.rs
sn_cli/Cargo.toml
sn_cli/src/subcommands/helpers.rs
sn_client/Cargo.toml
sn_client/src/api/spentbook_apis.rs
sn_interface/Cargo.toml
sn_interface/src/dbcs/mod.rs
sn_interface/src/network_knowledge/section_keys.rs
sn_interface/src/network_knowledge/test_utils.rs
sn_node/Cargo.toml
sn_node/src/node/flow_ctrl/tests/dbc_utils.rs
sn_node/src/node/flow_ctrl/tests/mod.rs
sn_node/src/node/messaging/client_msgs.rs

Updates to the new names in sn_dbc.

chore(deps): bump sn_dbc to 11.0.0

---

sn_node/src/node/membership/mod.rs

fix(sn_node): not to cast outdated membership vote

---

Cargo.lock
sn_fault_detection/Cargo.toml
sn_fault_detection/src/lib.rs
sn_interface/Cargo.toml
sn_interface/src/messaging/anti_entropy.rs
sn_interface/src/messaging/serialisation/wire_msg.rs
sn_testnet/Cargo.toml

Chore remove deps
